### ISSUE TITLE
Cannot see if the stream is online without entering another page.

### ISSUE THREAD

**Issue by diegogarciaa** [bastimeyer/livestreamer-twitch-gui#100]
On another version, I could see if the stream was or not offline in the favorites page without having to click on it.

It is kinda annoying having to click into the stream just to see that it is not online.

**Comment by bastimeyer** [comment]
Sorry, but I don't understand what you're trying to say.
The stream list is not a live representation of online streams. Channels that went offline won't be removed automatically from the list, you need to refresh it. It has always been like this...

**Comment by diegogarciaa** [comment]
Strange... When I logged into the application and went to the My -> Channels, I can see all channels I'm following right?

In the previous version, I could see only the channels that were online, but now I see all of them, even if it is offline: http://imgur.com/K8ujYD8

I think a green/red circle to indicate if the stream is online or not would be nice, maybe with a background thread to check every 5 minutes to see if the channel is still online, and update the ui status.

**Comment by bastimeyer** [comment]
I've renamed the menu. What you are looking for is "My streams", not "My channels"

**Comment by diegogarciaa** [comment]
Lmao, just found it. Thanks : ), sry for the inconvenience.

**Comment by bastimeyer** [comment]
Np :stuck_out_tongue_winking_eye:
