### ISSUE TITLE
Stream page not updating without a manual click, and Desktop notification not showing up

### ISSUE THREAD

**Issue by Mangos02** [bastimeyer/livestreamer-twitch-gui#101]
hope you fix if you can and please, i dont know anything about github and source files so if you can compile it for me that would be amazing, OR you can make an easy youtube tutorial that would also be great. thank you for your great work, and have a nice day.

**Comment by bastimeyer** [comment]
> Stream page not updating without a manual click

Right, the page content does not refresh automatically and needs to be reloaded manually. That's how it is, it's a design choice...

> Desktop notification not showing up

Yeah, I've already noticed that something is wrong, but thanks for the report. It's a shame that this stupid mistake went into the v0.9.0 release. I just fixed it in fc74729... I guess I have to release v0.9.1 today then....

**Comment by bastimeyer** [comment]
[v0.9.1 released](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.9.1)
