### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by Casarella** [bastimeyer/livestreamer-twitch-gui#102]
Hi, I seem to be having issues with the livestreamer-gui on my 32-bit Ubuntu. Streams load fine via command line livestreamer, but when I try to use the gui, I get:

Error: Couldn't launch the stream
usage: livestreamer [OPTIONS] [URL] [STREAM]

![screenshot from 2015-05-27 11 07 44](https://cloud.githubusercontent.com/assets/12628699/7839523/a6fb08fa-0460-11e5-9768-92ddd5583211.png)

I've (at least I think) pointed to the correct livestreamer executable location (/usr/bin/livestreamer), which is currently version 1.11.1, but now I'm more or less stuck on what to do next.

Thanks for your help in advance!

**Comment by bastimeyer** [comment]
#90 #78

**Comment by Casarella** [comment]
Oh wow, I completely missed #78. It is odd that the Ubuntu repositories are out-dated.

Thanks for the quick response!
