### ISSUE TITLE
Error: Module loading did not complete for: main, app

### ISSUE THREAD

**Issue by bastimeyer** [bastimeyer/livestreamer-twitch-gui#104]
On some systems, the build process fails due to a `grunt:requirejs` error. This may be a requirejs/r.js related issue and needs to be tracked down further. c04413d tried to fix the issue, but didn't solve it completely.

See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/77#issuecomment-96381723 and the following comments.

**Comment by VirtualPorygon** [comment]
Yes I confirm that the error is gone with this new revision. Thanks for you very quick reaction!

**Comment by bastimeyer** [comment]
Do you want to debug the grunt task? Then you need to debug the nodejs/io.js process running the grunt script with the corresponding parameters. Just google how to do this... I'm using the WebStorm IDE, so it's pretty easy. The script can be found at `/usr/local/bin/grunt` or whereever it was installed by the `grunt-cli` package...

**Comment by VirtualPorygon** [comment]
Thanks for the answer but I think I'm going to forget this idea. It's beyond my skills I guess, maybe one day if I have time to do some research on it.
