### ISSUE TITLE
Comboboxes are not working with touch input

### ISSUE THREAD

**Issue by fortunerayzor** [bastimeyer/livestreamer-twitch-gui#108]
Hi,
I guess this is not really a significant issue but I just wanted to let you know that comboboxes (e.g. changing quality) get broken with touch input. They can be opened, but can't be selected afterwards. I'm using it on my Windows tablet (x64).

**Comment by bastimeyer** [comment]
Hi, thanks for reporting!
A simple upgrade of the `Selecter` dependency was the fix of this issue.
