### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by isamu99** [bastimeyer/livestreamer-twitch-gui#109]
Not an issue, just wanted to say the latest releases ROCK, Bestimeyer! I've been waiting for the "Followed games" feature for a long time and it's finally here! Just tested it out and it's working but it seems it's displaying ALL the games I follow, whether they're currently live or not. Is there an option to set the "Followed Games" tab to display only followed games that are currently being live streamed instead of all of them?

Anyway thanks again for this app and all the work you're putting in for making it better. Livestreamer's the best!

**Comment by bastimeyer** [comment]
Thank you very much (again :sweat_smile:)!

> display only followed games that are currently being live streamed

No, I can't do this. You'd have to make another API call for each game, which would be incredibly inefficient. It's basically the same question as in #107. This is the payload of the `/api/users/:user/follows/games` request:
```json
{
	"_total": ...,
	"follows": [
		{
			"name": "Dota 2",
			"_id": 29595,
			"giantbomb_id": 32887,
			"box": {
				"large": "http://static-cdn.jtvnw.net/ttv-boxart/Dota%202-272x380.jpg",
				"medium": "http://static-cdn.jtvnw.net/ttv-boxart/Dota%202-136x190.jpg",
				"small": "http://static-cdn.jtvnw.net/ttv-boxart/Dota%202-52x72.jpg",
				"template": "http://static-cdn.jtvnw.net/ttv-boxart/Dota%202-{width}x{height}.jpg"
			},
			"logo": {
				"large": "http://static-cdn.jtvnw.net/ttv-logoart/Dota%202-240x144.jpg",
				"medium": "http://static-cdn.jtvnw.net/ttv-logoart/Dota%202-120x72.jpg",
				"small": "http://static-cdn.jtvnw.net/ttv-logoart/Dota%202-60x36.jpg",
				"template": "http://static-cdn.jtvnw.net/ttv-logoart/Dota%202-{width}x{height}.jpg"
			},
			"properties": { },
			"_links": { }
		}
	]
}
```

I don't know if there's a query parameter which can be set while requesting the data, because this is part of the undocumented API.

**Comment by isamu99** [comment]
OK don't sweat it bro, no big deal :)
