### ISSUE TITLE
Error: Livestreamer was not found

### ISSUE THREAD

**Issue by thundrfang** [bastimeyer/livestreamer-twitch-gui#110]
I'm on Windows 8 and whenever I try to watch any stream I am confronted with this error message, even though I have already installed the livestreamer. I have tried reinstalling it and it still does not work.

**Comment by bastimeyer** [comment]
Did the livestreamer installer upgrade your PATH variable? If it did not, you have to choose the livestreamer executable manually in the settings.
You can see the value of the PATH variable by typing `echo %PATH%` in the windows command prompt (press Win+R and run `cmd`)

**Comment by thundrfang** [comment]
This worked, thanks
