### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by Pedrozzak** [bastimeyer/livestreamer-twitch-gui#112]
![](http://i.imgur.com/XBeAwSh.png)

Please help me I downloaded it today (6/28) and when I see one live appears this error. I do not know what to do.

**Comment by Pedrozzak** [comment]
My sistem is OSX Yosemite 10.10.3

**Comment by bastimeyer** [comment]
One of Livestreamer's dependencies is complaining about the old Python version you're using.
See #69 and #96...

**Comment by Pedrozzak** [comment]
thanks :)
