### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by ejshear** [bastimeyer/livestreamer-twitch-gui#115]
Hello, 
Just installed this cool program, and I get this error any time I try to open a stream. I'm using Linux mint 17. Doesn't work from terminal either using "livestreamer twitch.tv/channel best". Thanks!

![twitchlivestream](https://cloud.githubusercontent.com/assets/13245997/8585195/b5a7e13a-25ac-11e5-9ccb-9175bc24e588.png)

**Comment by bastimeyer** [comment]
Hi,
that has already been asked in #112, #96 and #69...

You're using an old python version and one of livestreamer's dependencies is complaining about that... Either upgrade python or do what the error message is telling you: install the alternative python libraries

```bash
sudo pip install pyopenssl ndg-httpsclient pyasn1
```

**Comment by ejshear** [comment]
Thanks, fixed :+1:  :)

**Comment by bastimeyer** [comment]
Awesome :sunglasses:
