### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by xDanneee** [bastimeyer/livestreamer-twitch-gui#116]
Whenever I try to open a twitch stream I receive an error saying; "Error: Couldn't launch the stream. Failed to load plugin afreeca:". 

This error has only started today, I could watch streams fine yesterday.

**Comment by bastimeyer** [comment]
Well, this is clearly a [livestreamer related issue](https://github.com/chrippa/livestreamer/issues). The GUI is just reacting to this error message and is then displaying it in the popup.

Try to disable the livestreamer plugin of this streaming site (afreeca) and see if it fixes this issue...

**Comment by xDanneee** [comment]
I tried opening a stream using the livestreamer cli and it turns out all my plugins were broken. I reinstalled livestreamer and I no longer receive the error. Thanks.
