### ISSUE TITLE
[Feature request] Setting for past broadcast

### ISSUE THREAD

**Issue by ss2q1** [bastimeyer/livestreamer-twitch-gui#120]
Please include "past broadcast" function in one of the next versions.

https://api.twitch.tv/kraken/channels/[CHANNELNAME]/videos?broadcasts=true

i.e.
https://api.twitch.tv/kraken/channels/moondye7/videos?broadcasts=true

Thank you.

**Comment by bastimeyer** [comment]
There's already a VOD feature request thread
See #81
