### ISSUE TITLE
Warning "InsecurePlatformWarning" is treated as an error

### ISSUE THREAD

**Issue by marcorinck** [bastimeyer/livestreamer-twitch-gui#123]
Livestreamer is outputting a warning when starting it on a standard macos installation.

```
Marcos-iMac:~ marco$ livestreamer http://www.twitch.tv/streamurl medium
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/streamurl
/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source (best)
[cli][info] Opening stream: medium (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
````

If I understand this correctly, an update to a newer python version would fix this (Apple is installing python 2.7.6 on macos 10.10.4). The stream is working just fine though, its just a warning. 

Unfortunately livestreamer-twitch-gui is displaying a "Couldn't start the stream" error message with exactly this message. The stream was started fine though. 

Maybe you should ignore warnings?

When I click "close" in the error message, the stream window is getting closed, even though it was running fine ... really :- ) 

BTW: The text in the error message box can't be selected with mouse

**Comment by bastimeyer** [comment]
Yep, I know (#115, #112, #96, #69 and https://github.com/bastimeyer/livestreamer-twitch-gui/issues/69#issuecomment-97127886 :weary:)

I've already started working on a reimplementation of the stream launch procedure, so warnings like these can be handled in a better way and can be separated from the error messages. I'm also rewriting the modal dialog system for this, so it's quite a bit of work...


> The text in the error message box can't be selected with mouse

Noted, thanks!

**Comment by marcorinck** [comment]
hehe, maybe you should leave the issue open then and really fix it :smile:
