### ISSUE TITLE
livestreamer not working at all

### ISSUE THREAD

**Issue by llite** [bastimeyer/livestreamer-twitch-gui#125]
Ok, so this is most likely a newbie issue but my gui isn't working at all. Could just be me not have installing something right or an issue with windows 10 
![issue](https://cloud.githubusercontent.com/assets/13774387/9241184/b4763718-4135-11e5-8f93-9ceb7ddda700.PNG)

**Comment by bastimeyer** [comment]
This error just means that the GUI couldn't reach the twitch servers. It's either their fault (servers down or under a high load, etc.) or your own internet connection (connection to `api.twitch.tv` in particular). It could also be a misconfigured firewall preventing network access.

**Comment by llite** [comment]
Ok, so I've disabled my firewall completely, same thing happened. Ran it on another computer on the same network works perfectly fine. So have no idea of what is causing this problem. As well when I go to api.twitch.tv in browser it's the same on both computers (the one where it is working and the one where it isn't)

**Comment by bastimeyer** [comment]
Well, I don't know how I can help you here, it's clearly not the fault of the GUI itself.

Maybe you can find some more informations in the dev tools:
Start the application with the `--remote-debugging-port=8888` parameter, open `http://localhost:8888` in your browser and choose "Livestreamer Twitch GUI". In the network tab you'll see all requests being made by the GUI.
