### ISSUE TITLE
no way to simply paste a stream URL?

### ISSUE THREAD

**Issue by poopsock** [bastimeyer/livestreamer-twitch-gui#126]
I got the GUI for one purpose, I wanted to be able to open the program and paste a streaming URL, such as this:

http://www.twitch.tv/gamesdonequick/v/8647104?t=50h56m55s

into the interface and have it just play. When I paste that into the search box, it tries to search. I can't find anywhere on the interface where I can simply paste a URL to pass to livestreamer. This seems like a huge huge missing feature. Either detect a streaming URL when I paste one into the search box, or have a place for me to enter one -- or if it already exists -- make it more clear that it exists!

**Comment by bastimeyer** [comment]
> I got the GUI for one purpose, I wanted to be able to open the program and paste a streaming URL

That's what the livestreamer CLI is used for, if you want to open a specific url. The purpose of the GUI is to browse streams and channels, not providing an input field for pasting URLs...

**Comment by acidgold** [comment]
Yes but opening the command line and pasting the URL is *ugly* and you already made such a beautiful GUI... can you just add a link under "Misc" that says "Open Stream URL"? I think you might underestimate how many people would LOVE this!

**Comment by rihardsp** [comment]
I can only agree on this. I'd love to be able to optionally paste a whole twitch URL in the bar.

**Comment by bastimeyer** [comment]
> I'd love to be able to optionally paste a whole twitch URL in the bar.

I can only see myself implementing a simple URL parser for **twitch channel** URLs, so that channel pages can be found a bit quicker. VOD URLs and anything else will be rejected though (since VODs are not supported yet)
