### ISSUE TITLE
feature request: auto-download livestreamer and VLC

### ISSUE THREAD

**Issue by poopsock** [bastimeyer/livestreamer-twitch-gui#127]
The most cumbersome part for new users is having to download and install livestreamer and VLC, and then go into settings and point to the executable. It would be great if the program auto-downloaded these apps when prompting that they are missing.

There is an open source program called ShareX that does this with ffmpeg. If you don't have it installed, it says "download ffmpeg now?" and then auto-downloads and uses the latest ffmpeg build for your OS:

https://github.com/ShareX/ShareX

https://github.com/ShareX/ShareX/blob/251849aedad988be531fdb487df92c3cabb0694d/ShareX.HelpersLib/FFmpegDownloader.cs

**Comment by bastimeyer** [comment]
I personally don't like the idea of automatic downloads and installations, especially on different platforms. You'd have to implement this for Windows, OSX and multiple linux distros with different package managers. I don't think that this is a good idea.

The GUI will already notify you if livestreamer hasn't been installed yet and it will also ask to open [this](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.3/package.json#L49) URL in the user's browser. You don't need to point to the executable as long as livestreamer is registered to your `$PATH` variable, it will find it automatically then.

The **chocolatey** #54 and **arch** #58 packages have those dependencies defined (livestreamer), installing the GUI by using those package managers automatically solves this problem. This is the proper way of doing this, implementing something like this into the application itself is usually bad.

**Comment by mawekuwe** [comment]
I think it is a good idea, at least for Windows and mpv. It is a single executable for mpv. It could be simply placed in a subfolder of the GUI and use them by default if no other is specified in the parameters.
MPV windows builds here http://mpv.srsfckn.biz/

As for livestreamer, it is also possible to include it in a sub folder in its portable version (no python required)
http://docs.livestreamer.io/install.html#zip-archive

**Comment by bastimeyer** [comment]
Dependencies need to be resolved by a package manager or by the user himself (if he's not using one). Including/bundling other software is a terrible idea.

**Comment by mawekuwe** [comment]
with the link I gave there is no dependencies: 1) download 2) unzip 3) launch

**Comment by bastimeyer** [comment]
Sorry, but this is not going to happen.
