### ISSUE TITLE
language filter

### ISSUE THREAD

**Issue by preovaleo** [bastimeyer/livestreamer-twitch-gui#133]
Hello,

I reopen #113 because now there is a solution to filter by language :
for example :
http://api.twitch.tv/kraken/streams?limit=60&offset=0&broadcaster_language=en&on_site=1

perhaps the on_site thing broke everything but ...

can you do something with that?

good job

**Comment by bastimeyer** [comment]
Hi, thanks for the info!
Yes, I can do something with that. Multiple languages can also be selected, so this basically means that the faded-out streams can be completely removed (or I'll add a switch to the settings for that).

https://api.twitch.tv/kraken/streams?broadcaster_language[]=de&broadcaster_language[]=fr

**Comment by bastimeyer** [comment]
Streams can now be completely filtered out, but this has to be enabled in the settings first. Search results won't be filtered out.
