### ISSUE TITLE
Bug stream offline when i wan't to show stream that i watch

### ISSUE THREAD

**Issue by preovaleo** [bastimeyer/livestreamer-twitch-gui#135]
Hello,

When a stream end and go offline and i wan't to see stream that i watch on the top button.
It cause a bug.
I think it can be solve by check if stream is online when i wan't to see stream that i watch

![screenshot from 2015-09-08 12-29-53](https://cloud.githubusercontent.com/assets/6892913/9732657/c6a17ac4-5625-11e5-9c0d-060628f9f232.png)

**Comment by bastimeyer** [comment]
Hi,
thanks for the bug report, but I'm unable to reproduce this. :confused: 

If a stream you are watching has gone offline, the livestreamer process will of course terminate. This will trigger the [removal of the "livestreamer record"](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.3/src/app/controllers/LivestreamerController.js#L394) from the [streams-being-watched list](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.3/src/app/controllers/LivestreamerController.js#L79-L82) and whenever you are visiting the WatchingRoute, the data of all streams from this list will then be [reloaded (refreshed)](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.3/src/app/routes/WatchingRoute.js#L8-L12). As you can see, there is no `id` being read from any (missing) object, at least in the application code.

I'd like to know how to reproduce this (in the latest build from the master branch), so I can find out where this unknown id property error is coming from.
