### ISSUE TITLE
right click tray menu option toggle notifications

### ISSUE THREAD

**Issue by natostanco** [bastimeyer/livestreamer-twitch-gui#139]
What about an entry option in the tray right click menu to toggle desktop notifications?

**Comment by bastimeyer** [comment]
Yeah, the right click menu of the tray icon needs to be improved a bit.
I don't know if toggling settings from the context menu is a good idea though. I think it's much better to just temporarily disable certain features from here, like the desktop notifications, which will should be reenabled after restarting the application. Let me see....
