### ISSUE TITLE
Every streamer has a sub button

### ISSUE THREAD

**Issue by Robby-** [bastimeyer/livestreamer-twitch-gui#142]
Everyone has a sub button in the app, even streamers that don't have one on the website. Clicking it opens the browser at `http://www.twitch.tv/streamername/subscribe` which rightfully gives an error message.

**Comment by bastimeyer** [comment]
Thanks for reporting!
The hide-logic somehow got lost during the reimplementation of the follow and sub buttons in 5623be7...
