### ISSUE TITLE
Add a link to twitchemotes.com in watching dialog

### ISSUE THREAD

**Issue by ViktorF** [bastimeyer/livestreamer-twitch-gui#143]
I think adding a link to the streamer's specific http://twitchemotes.com/ site in the watching dialog could be quite useful.

Sadly I was unable to find the right js file for the watching dialog so i couldn't try adding it myself :/

**Comment by bastimeyer** [comment]
Yep, sounds reasonable. I'll also add this to the channel page. The button will be hidden for unpartnered channels then. Maybe it should also be hidden if a custom chat method has been selected in the settings (eg. Chatty), but I'll ignore this for now; it could still be useful I think...

> I was unable to find the right js file for the watching dialog

Here you go:
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/3db4c184d5539787f8e7121f994b1a6058811f04/src/templates/modals/livestreamer.html.hbs#L41-L46
