### ISSUE TITLE
Custom Parameter ringbuffer-size 

### ISSUE THREAD

**Issue by Jeeaaasus** [bastimeyer/livestreamer-twitch-gui#146]
The custom parameter: "--ringbuffer-size VALUE"
Does not work for me. No errors, but nothing changes. Can anyone get it to work? 
It does work when I write it in the config file but not if I launch a stream with the GUI. 

I'm using v0.10.1-win32, on windows 10.

Thanks

**Comment by bastimeyer** [comment]
All parameters defined in the "custom livestreamer parameters" field in the settings menu will be parsed and then used as command line parameters for the livestreamer process. I'm not sure why it wouldn't work on your system. Command line parameters are having a higher priority than parameters defined in your config file.
You could open the task manager, and then check for the command parameters of the livestreamer process. All custom parameters can be found at the beginning of the parameters list.
If it's there, it should be an issue of livestreamer and not the GUI, since it's doing its job correctly.

**Comment by Jeeaaasus** [comment]
All other parameters work when placed in the GUI options, but not the --ringbuffer-size. Tried a lot of different things now.. Don't really know what to tell you, nothing changes when adding that parameter and it does work when using the command line.

"You could open the task manager, and then check for the command parameters of the livestreamer process. All custom parameters can be found at the beginning of the parameters list."

You've lost me here. I would appreciate it if you'd explain how to do this a little further.

**Comment by bastimeyer** [comment]
> You've lost me here. I would appreciate it if you'd explain how to do this a little further.

I'm not on Windows, so this might not be 100% accurate...
Open the task manager, go to the processes tab and add the command line column. You can do this by clicking "View -> Add columns". Then launch a stream and look for the livestreamer process...

**Comment by bastimeyer** [comment]
So, did you find out why this wasn't working for you?

**Comment by Jeeaaasus** [comment]
No I cant figure out why it isn't working. Your description was accurate, here is how it looks in task manager. When using the gui and adding --ringbuffer-size 4096M in the settings: 
![livestreamer with gui](https://cloud.githubusercontent.com/assets/15081909/10583432/3aeb487e-768d-11e5-9131-738082899e76.jpg)

And here is how it looks when starting a stream from cmd with the same parameter:
![livestreamer with cmd](https://cloud.githubusercontent.com/assets/15081909/10583459/650e79e6-768d-11e5-906f-e92ecfe8b5fb.jpg)

So it looks fine. But it doesn't work from the GUI for me. It only caches the default 16M.

**Comment by bastimeyer** [comment]
It's because of `--player-passthrough hls`. In this case, livestreamer will just return the HLS stream url to your video player and will do nothing else. Switch to http or rtmp to fix this...

**Comment by Jeeaaasus** [comment]
Okey... that seems a bit weird. Well thanks for your help and the work you do! :)

**Comment by bastimeyer** [comment]
np

> that seems a bit weird

You can find more informations about the different stream types in the [Wiki](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Livestreamer-configuration).
