### ISSUE TITLE
Only show games that have active streamers in the Games tab

### ISSUE THREAD

**Issue by riesza** [bastimeyer/livestreamer-twitch-gui#148]
Similar to the Twitch mobile app. Otherwise trying to find streams takes an unnecessary amount of time if you have a lot of games in your favorites. At least as an option maybe.

**Comment by bastimeyer** [comment]
There's no viewers/channels count data included when requesting the followed games, so this can't be done. https://github.com/bastimeyer/livestreamer-twitch-gui/issues/109#issuecomment-110548110
Just follow the channels instead...

**Comment by riesza** [comment]
Shame, thanks anyway.
