### ISSUE TITLE
Doesn't open Chatty properly when in certain folder structures (I think)

### ISSUE THREAD

**Issue by ClefAria** [bastimeyer/livestreamer-twitch-gui#150]
I normally keep my instance of Chatty in C:\Program Files\_Utilities & Portable\Chatty , and with the new version, I got an error from Java Machine Virtual Launcher whenever it tried to invoke Chatty upon opening a stream (setting to automatically open chat was enabled), which was just a dialog box:

http://i.imgur.com/PB7HeUf.png

I tried moving the folder to simply C:\Chatty , and the issue instantly went away. Maybe it doesn't like the underscore/ampersand/spaces in the other directory?

**Comment by bastimeyer** [comment]
Thanks for reporting the issue!
Spaces in the path were the cause of this :tired_face:... I'm going to reopen the thread though, so it doesn't get reported multiple times.

I may release a new version next week or the one after that, we'll see. Until then, you can *still* use the custom method to open Chatty by using these parameters:
**Win:** `javaw -jar "/path/to/chatty.jar" -single -connect -channel "{channel}"`
**Linux/OSX:** `java -jar "/path/to/chatty.jar" -single -connect -channel "{channel}"`

The `{user}` and `{token}` parameters have also been added in 25e2e42 just now (not available in `v0.11.0`)...

**Comment by ClefAria** [comment]
Thanks a lot for that workaround! Took me a moment to realize you meant the "custom application" method, and that I have to change the original backslashes to slashes when copy/pasting the path that way, but I figured it out, and it seems to be working perfectly now. :D

**Comment by bastimeyer** [comment]
[v0.11.1 released](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.11.1)
