### ISSUE TITLE
Login Doesn't Save

### ISSUE THREAD

**Issue by Jadistk** [bastimeyer/livestreamer-twitch-gui#154]
Hello, I'm on Win10 x64 and running livestreamer GUI as admin. I login just fine and can see OAuth token, but it doesn't save the login for the next time the program runs. Thanks for a great program.

**Comment by bastimeyer** [comment]
Hi...

> running livestreamer GUI as admin

Why exactly are you running the application with administrator privileges? This is not necessary and you shouldn't do this.

> it doesn't save the login for the next time the program runs

What about the application settings? Are these also lost after restarting it?
If this is the case, then you should see if the GUI is able to create its cache and config folders in `%LOCALAPPDATA%\livestreamer-twitch-gui`.

Also: Are you by accident logging in to the same twitch account on a different machine? Logging in with your password will invalidate any previously used access tokens.

Another thing you could try is starting the application with the `--remote-debugging-port=8888` parameter. Then open your web browser and open `localhost:8888`. In the console tab, paste this to see if anything has been saved in the localStorage cache:
```js
Object.keys( window.localStorage ).map(function( key ) {
  return JSON.parse( this[ key ] );
}, window.localStorage );
```

**Comment by Jadistk** [comment]
Thanks for the reply! I tried running with admin because I've needed to do that for many other programs in Win10 (even though my account is an admin) for various things to work correctly.

The application settings are saved, and there are files and folders within %LOCALAPPDATA%\livestreamer-twitch-gui

I'm not using a different machine, but I do occasionally switch between browser viewing and using your program. However, the problem still presents itself when opening your program, logging in, exiting, then reopening.

I tried what you suggested and this is what returned. It's not too big of a problem, just a minor annoyance. Thanks again for a great program and it seems like I might be the only one affected!

> Object.keys( window.localStorage ).map(function( key ) {
  return JSON.parse( this[ key ] );
}, window.localStorage );

> [Exception... "Component is not available"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: debugger eval code :: <TOP_LEVEL> :: line 1"  data: no]

> This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] developer.cdn.mozilla.net

I guess my only other question is should I be saving my OAuth key somewhere or trying to use a key with livestreamer's config file? Thanks again.

**Comment by bastimeyer** [comment]
> The application settings are saved

So choosing a different video player in the settings will be remembered after restarting the application? If it does, then it doesn't make any sense to me why the auth info doesn't get saved as well. It's just another property added to the localStorage and there is no difference between other properties.

> I do occasionally switch between browser viewing and using your program

No, I meant Livestreamer Twitch GUI on a different machine, since it then would use the same OAuth clientid, which the twitch website is of course not using.

> I tried what you suggested and this is what returned.

This looks like a Firefox specific error message... Did you paste this into the Firefox dev console? Please paste this into the remote-dev-console on `localhost:8888` (after clicking on "Livestreamer Twitch GUI")...

**Comment by Jadistk** [comment]
Thanks for the update! Just wanted to say that whatever happened seemed to fix my issue! I even tried deleting/reinstalling before the update, but there must have been some change to fix it. Much appreciated for your great program!!!
