### ISSUE TITLE
Firewall warnings in OSX El Capitan

### ISSUE THREAD

**Issue by ikiPZdU6UP3Gra** [bastimeyer/livestreamer-twitch-gui#157]
The system version of Python in OSX El Capitan is no longer signed as in previous versions of OSX. Because of this, every time you start a stream, you are now prompted to allow Python through the firewall. Perhaps the OSX release of Livestreamer should now include it's own bundled version of Python?

**To see the un-signed status of the Python.app in El Capitan, use this command:**
*sudo codesign -dvvvv /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app*

This can temporarily be fixed by creating a code signing certificate and self-signing the python.app, however this isn't recommended in the longer-term as it's more insecure. Firewall allowances should be app specific, not entire frameworks.

**Temporary fix using custom created self-signed certificate**

1. Remove Python.app from the Firewall Options list
2. Run terminal command:
   * *sudo codesign -f -s SELF_SIGNED_CERT_NAME /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app*
3. Open livestreamer and open any stream and allow through firewall.

After doing the above you'll no longer be prompted to allow through the firewall everytime you start a stream.

**Comment by bastimeyer** [comment]
Wrong repo...
All **Livestreamer** (not *Livestreamer Twitch GUI*) related issues should be reported [over there](https://github.com/chrippa/livestreamer) and not here

**Comment by ikiPZdU6UP3Gra** [comment]
Ah, ok, my apologies - I'll go ahead and close the issue here then.
