### ISSUE TITLE
Chatty jar on Linux

### ISSUE THREAD

**Issue by yunake** [bastimeyer/livestreamer-twitch-gui#159]
Hey, first of all, thank you for this amazing software, and thanks for adding direct support for Chatty.

I just wanted to let you know that at least on ArchLinux (and quite possibly on, Chatty comes with a wrapper script called simply `chatty` that has the correct path to the JAR and is right in the user's PATH, so it can be detected automatically. I think it would not be unreasonable to simply try exec'ing "chatty" if no JAR path is supplied, would be still better than current behaviour of failing silently. What do you think?

**Comment by bastimeyer** [comment]
Hello and thanks for the suggestion. This can of course be added... Should be simple...

**Comment by yunake** [comment]
you're a star!
