### ISSUE TITLE
npm install fails "Unable to find suitable version for ember-data"

### ISSUE THREAD

**Issue by skulblakka** [bastimeyer/livestreamer-twitch-gui#160]
When I try to run "npm install" the process fails with "Unable to find suitable version for ember-data".

End of the output with the error:
```
bower extract       ember#2.2.0-beta.1 archive.tar.gz
bower invalid-meta  ember is missing "ignore" entry in bower.json
bower resolved      git://github.com/components/ember.git#2.2.0-beta.1
bower ECONFLICT     Unable to find suitable version for ember-data

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pascal\\AppData\\Roaming\\npm\\node_
modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE
npm ERR! livestreamer-twitch-gui@0.11.0 postinstall: `bower --config.interactive=false install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the livestreamer-twitch-gui@0.11.0 postinstall script 'bower --config.interactive
=false install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the livestreamer-twitch-gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower --config.interactive=false install
npm ERR! You can get their info via:
npm ERR!     npm owner ls livestreamer-twitch-gui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Dev\livestreamer-twitch-gui\npm-debug.log
```

I uploaded the npm-debug.log here: https://tresor.it/s#gKvyEj18ageYQVHMXeWaNw

Last time I tried building was when 1.11.0 was released which worked without any problem.

What I tried so far:
* Updating Node.js to 4.2.1 (LTS) and after this didn't work I updated to 5.0.0 (stable)
* Updating npm
* Clean bower cache
* Delete the local copy of the repo and clone it again

**Comment by bastimeyer** [comment]
Thanks...
This is a version conflict caused by a1fede1... I'm going to fix this tomorrow.

It's because of `ember-localstorage-adapter`, which is requiring
```js
"dependencies": {
  "ember-data": "~1.13.11 || ~2.0.0",
  "ember": "~1.13.9 || ~2.0.0"
}
```
instead of
```js
"dependencies": {
  "ember-data": "~1.13.11 || ^2.0.0",
  "ember": "~1.13.9 || ^2.0.0"
}
```

If you like, you can temporaily fix this by adding
```js
"resolutions": {
  "ember": "2.2.0-beta.1",
  "ember-data": "2.2.0-beta.3"
}
```
to the [bower.json](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/a1fede15f1a07638e696730be125079edc3c755a/bower.json) file.

**Comment by bastimeyer** [comment]
Should be fixed now.
You maybe also need to clear your bower cache again, but I'm not sure. Please tell me if it's working on your machine, too, so I can close this (without the `resolutions` property in the bower.json file). Thanks!

**Comment by skulblakka** [comment]
Works again. Thanks.
