### ISSUE TITLE
Twitch Livestreamer Seek

### ISSUE THREAD

**Issue by RyuBlade** [bastimeyer/livestreamer-twitch-gui#163]
Hello I only just found out about this program mainly because my computer is 9 years old and so I look for means to externally play flash videos for example twitch vods as I follow a few people and I got it working for the most part except no matter what player I set as default I cannot for the life of me get it to seek ahead to any point I tried vlc / potplayer / mpc-hc and using the passthrough command as well as the T command both don't work

any advice on this would be greatly appreciated.

**Comment by bastimeyer** [comment]
Hello...
Jumping around in the video buffer needs to be supported by your video player and is *totally unrelated to Livestreamer Twitch GUI*, so I can't help you here...

If you want to watch VODs while using Livestreamer via CLI, then please don't forget to set the right parameters (`livestreamer --player "/path/to/player" --player-passthrough hls twitch.tv/CHANNEL/v/VODID best`). If your video player is capable of reading HLS streams, then you're able to jump around in the VOD. If you want to download the VOD, use the `-o "/download/location/filename"` parameter.

**Comment by bastimeyer** [comment]
Hello!
~~Jumping around in the video buffer needs to be supported by your video player and is *totally unrelated to Livestreamer Twitch GUI*, so I can't help you here...~~

~~If you want to watch VODs while using Livestreamer via CLI, then please don't forget to set the right parameters (`livestreamer --player "/path/to/player" --player-passthrough hls twitch.tv/CHANNEL/v/VODID best`). If your video player is capable of reading HLS streams, then you're able to jump around in the VOD. You can also download VODs by using the `-o "/download/location/filename"` parameter.~~

**Edit:**
Just re-read your comment (please use punctuation :crying_cat_face: next time), so I'm answering again... I think you're having buffering issues, right?

To fix this, first, set the `--player-passthrough` parameter to a **different** value than `hls`. See the [Livestreamer configuration Wiki entry](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Livestreamer-configuration) for more informations why this is important.
Then increase the `--hls-live-edge` parameter and maybe also the `--hls-segment-threads` parameter. Documentations are linked inside the GUI for each of those livestreamer parameters.

**Comment by RyuBlade** [comment]
Not buffering issues but issues with the twitch stream where I wanted to jump ahead to a specific time into the stream instead of like I had to wait 4 hours to get to the part I wanted to..lol

No matter what player I used it never shows the total time which is a little over 11 hours so I'd like to configure it so I can at least skip ahead instead of waiting hours hopefully this clears any confusion and sorry for the grammar.

**Comment by RyuBlade** [comment]
The post you crossed out was actually what I really needed and that command helped me and I'm able to now seek ahead to points I wanted to watch and continue on from last time thanks so much for the help xD thread can be closed now cheers again.
