### ISSUE TITLE
The "there is a newer release" popup should automatically download the update.

### ISSUE THREAD

**Issue by Alex139602** [bastimeyer/livestreamer-twitch-gui#166]
Is this a possibility?

Currently I'm keeping the app up to date with git command line but I think the app should download the latest release automatically if you agree yes to the modal pop up when it comes up, instead of opening the github page.

Any thoughts on this? I can look into forking this and trying to provide it, but It wont be straight away.

**Comment by bastimeyer** [comment]
See #145...
