### ISSUE TITLE
Shortcut to refresh listings

### ISSUE THREAD

**Issue by ryanlewis** [bastimeyer/livestreamer-twitch-gui#168]
I usually keep your app open. I'd like to be able to cmd+r to refresh listings, instead of reaching for the refresh button.

**Comment by bastimeyer** [comment]
See #152 
Just press [F5 or CTRL+R](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.0/src/app/components/ApplicationComponent.js#L55) until a new version gets released or build the application from the master branch...

**Comment by ryanlewis** [comment]
Ah cool, will await the latest release then. :smile:
