### ISSUE TITLE
Launch directory

### ISSUE THREAD

**Issue by Poorchop** [bastimeyer/livestreamer-twitch-gui#170]
Just a general question - from which directory is the Livestreamer executable called? I took some screenshots while watching via mpv and I can't find where the screenshots where saved. By default, mpv will save the screenshots to the directory from which the executable was called.

**Comment by bastimeyer** [comment]
It's somewhere in your system's temp folder. This is the default NWjs behavior for applications which have been compiled the way it's done here (with appended application content to the executable).

Which OS do you use?
In *nix systems you can check the current working directory of a process with `pwdx $(pgrep mpv)`. I have no idea how this works on Windows...

You could also start the application with the `--remote-debugging-port=8888` parameter, then open `http://localhost:8888` in your browser and then type `process.cwd()` into the dev console, to see the current working directory of the NWjs process...

**Comment by Poorchop** [comment]
Using Windows 8.1 and Fedora 23. I tried remote debugging but `process.cmd()` wasn't defined. However, I was able to find the screenshot in the temp folder as you mentioned. Within the temp directory, it's inside another folder named nw*_* where the asterisks are a string a numbers. Thanks for your help.

In case anyone stumbles across this in the future, the folder is deleted after closing the application, so either specify the save path in the mpv configuration file or copy the screenshot to another location before closing the program.

**Comment by bastimeyer** [comment]
> I tried remote debugging but process.cmd() wasn't defined.

It's `process.cwd()`

> Windows

You could also have run this command on Windows to find the NWjs temp directory:
`wmic process where "Name='livestreamer-twitch-gui.exe'" get CommandLine`
This lists the command line of the process and its subprocesses. The `--working-directory` of the subprocesses are showing the temp dir location.

> In case anyone stumbles across this in the future, the folder is deleted after closing the application

Well, yeah, as I said, the application code is being compressed and appended to the NWjs executable during the build process. This means that NWjs has to uncompress the content and then temporarily write it to the filesystem somewhere before it can launch the app.
There are other ways of compiling NWjs apps, but that's what the nw-builder is doing.

**Comment by Poorchop** [comment]
Excusing my inability to read, I still get "ReferenceError: process is not defined". The second command works for listing the necessary processes are you wrote. Also I know that it's obvious that the directory is erased when the application is closed but sometimes obvious stuff get can overlooked, like confusing a W for an M.

**Comment by bastimeyer** [comment]
> ReferenceError: process is not defined

Then you are probably using your browser's dev console and not the NWjs one. Click the "Livestreamer Twitch GUI" link on `http://localhost:8888` to access it...
