### ISSUE TITLE
Automatic restart of desktop notifications.

### ISSUE THREAD

**Issue by omperus** [bastimeyer/livestreamer-twitch-gui#176]
Every time i lose internet connection the desktop notifications get disabled and won't restart unless i click the button, it would be nice if it checked automatically for a connection so it restarted itself, sometime i spend hours without the notifications working and lose on some streamers, thanks.

**Comment by Mayurifag** [comment]
Would be a nice feature, same problem here.

**Comment by bastimeyer** [comment]
Yeah, the notification error logic is not ideal like it is right now and will be changed.
I'm going to rewrite it so it won't stop querying the API in case of an error.

**Comment by Mayurifag** [comment]
Nice, thanks a lot in advance!
