### ISSUE TITLE
Permanently show which game is currently being played

### ISSUE THREAD

**Issue by ThisIsIvan** [bastimeyer/livestreamer-twitch-gui#178]
If you're browsing and sorting for games, this might not be a big problem, but when you're watching the Followed streams tab it's not so obvious which game the streamer is currently playing. 

An option to permanently show the text which tells you which game is being played would be neat (which is displayed when hovering over the stream).

**Comment by bastimeyer** [comment]
Yeah, an always visible flags option is already in, so something like that could also be added.

**Comment by ThisIsIvan** [comment]
Thank you, bastimeyer.
