### ISSUE TITLE
Unexpected version

### ISSUE THREAD

**Issue by Confuseh** [bastimeyer/livestreamer-twitch-gui#179]
When I try to launch any of the streams I get an error message saying "Unexpected version check output". I have no clue where output is, since stdout gives me nothing.

Livestreamer-twitch-gui version: 0.11.1
NW.js: 0.12.3
OS: Arch Linux
Livestreamer: 1.12.2

**Comment by bastimeyer** [comment]
The GUI will always validate livestreamer first, before launching any streams. That's where the error is coming from.
What's the output when running `livestreamer --version --no-version-check` on your machine??? Needs to be `livestreamer 1.12.2`, or else this error will be shown. See [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.1/src/app/controllers/LivestreamerController.js#L260-L296)...
How did you install livestreamer? I've never seen a different output before, so this error is indeed a bit *unexpected* :confused:.

**Comment by Confuseh** [comment]
I don't know what's going on anymore. My livestreamer just broke completely and keeps outputting same error about urllib, it worked before I installed livestreamer-twitch-gui. Close it for now, I need to sort out that first, if it appears again after I fix livestreamer, I'll let you know.

**Comment by bastimeyer** [comment]
The AUR package has just listed livestreamer as a dependency, so this error should be unrelated...
Good luck fixing the error :four_leaf_clover:

**Comment by Confuseh** [comment]
Okay it was livestreamer issue, now everything is fixed. Sorry for disturbing you!
