### ISSUE TITLE
Clicking notifications doesn't open streams...

### ISSUE THREAD

**Issue by Robby-** [bastimeyer/livestreamer-twitch-gui#183]
Clicking notifications doesn't open streams even though `Notification click` is set to `Open stream`.

**Comment by bastimeyer** [comment]
Which OS do you use?

**Comment by Robby-** [comment]
Windows 7.

**Comment by bastimeyer** [comment]
[The notification click listener is working correctly](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.1/src/app/services/NotificationService.js#L371-L376), so for me this sounds more like an issue with your Windows configuration. I just tested it with a fresh Win7 VM and there were no issues at all. I don't know though if the clicks can be disabled in Windows somewhere...

- **Linux**  
  Notification click events are not supported (NWjs restriction).
- **OSX**  
  To be able to click notifications, the type of notification has to be changed in the notification settings first. Items in the notification center can always be clicked, though.
- **Windows**  
  While you're only able to receive balloon tooltips on Win7, notification clicks should be working out of the box (for all Windows versions). To be able to receive real notifications on Win8+, a startmenu shortcut is required, but this will be created automatically. See #173

**Comment by Robby-** [comment]
It turns out I can't seem to consistently reproduce it, but it happened a couple of times now. The last time it happened I was playing a full screen game and when I exited the game I saw that a notification was already there, and it was starting to fade out/away. When I clicked it, it disappeared and nothing else happened.

**Comment by bastimeyer** [comment]
That's not an issue of Livestreamer Twitch GUI. It is just making use of NWjs' notification system which is again using the notification system of your OS. You are occasionally running into these notification click issues because of the terrible notifications of Windows 7. There is nothing that can be done on the application level.

**Comment by Robby-** [comment]
Oh, I see. No worries then, thank you.
