### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by Magciool** [bastimeyer/livestreamer-twitch-gui#184]
I did not log out from Livestreamer Twitch GUI but when I just started it up I was logged out.
I tried to login but after typing in my name and password I get this:

 {"error":"Bad Request","status":400,"message":null}

I can log out and log in normally directly on tiwtch.tv
(I haven't save my acess token so I didnt try that)

edit: looks like it was something temporary I'm able to login again

**Comment by bastimeyer** [comment]
When something like that happens, it's usually not the fault of the application, but instead Twitch's infrastructure... Closing this now...
