### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by ptkato** [bastimeyer/livestreamer-twitch-gui#185]
> Unexpected version check output

Well... Before, I was using an older livestreamer version, the GUI asked to update, so I did, now the GUI throws this error.

I'm actually using the livestreamer 1.12.2-1 version under Debian Jessie.

**Comment by bastimeyer** [comment]
> the GUI asked to update

???
[This was the last time the required livestreamer version has been updated.](https://github.com/bastimeyer/livestreamer-twitch-gui/blame/master/package.json#L51)

What's the output of `livestreamer --version`???
Does the package by accident replace the livestreamer version string with it's own package version? If this is the case, then the GUI is parsing it as release and prerelease and not as release and package version...
[Semantic versioning](http://semver.org/): `release-prerelease` < `release`

**Comment by ptkato** [comment]
I think I expressed myself wrong. I meant to say that I was using and older version than 1.11.1, the GUI asked to update, I did update to the newest version, 1.12.2-1, but now there's this new error.

`livestreamer --version` output:

    ptkato@laptop:~$ livestreamer --version
    Traceback (most recent call last):
      File "/usr/bin/livestreamer", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
        working_set = WorkingSet._build_master()
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
        return cls._build_from_requirements(__requires__)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: livestreamer==1.12.2

**Comment by bastimeyer** [comment]
Yeah, looks like livestreamer did break on your system... Could #179 be related, maybe?

**Comment by ptkato** [comment]
I installed the new version over the older, but when this error was thrown I did purge the livestreamer and installed it again, so I don't know.

Do you know what `DistributionNotFound` means?

**Comment by bastimeyer** [comment]
> Do you know what DistributionNotFound means?

I have no clue, sorry... You should open a thread at the livestreamer repo for all livestreamer related issues... [There are already a couple of DistributionNotFound related ones](https://github.com/chrippa/livestreamer/issues?utf8=%E2%9C%93&q=is%3Aissue+DistributionNotFound), so maybe you can find help over there...

**Comment by Akanoa** [comment]
Same here, I was on streamlink-twitch-gui v 1.0.0 all was good. Today I update to v 1.1.0 and each time I try to launch a stream I see this :/ 

![deleteme](https://cloud.githubusercontent.com/assets/4521637/21582382/7b41e874-d055-11e6-9592-4782ef01e3fb.png)
