### ISSUE TITLE
OS X: Unable to compile source tar

### ISSUE THREAD

**Issue by MCPtz** [bastimeyer/livestreamer-twitch-gui#186]
For v0.11.1.

I found an issue with the source tar I downloaded from the webpage.

Download the release source tar.gz files and untar it somewhere.
cd into the source directory.
Following the Readme.md:
npm install -g grunt-cli bower
npm install
And finally an error on "grunt release" command:
Running "metadata:all" (metadata) task
Fatal error: fatal: Not a git repository (or any of the parent directories): .git

Full output:
```
grunt release
Running "release" task

Running "jshint:tasks" (jshint) task
>> 27 files lint free.

Running "jshint:app" (jshint) task
>> 214 files lint free.

Running "jshint:test" (jshint) task
>> 7 files lint free.

Running "connect:test" (connect) task
Started connect web server on http://0.0.0.0:8000

Running "qunit:all" (qunit) task
Testing http://localhost:8000/test/tests.html .................................OK
>> 157 assertions passed (327ms)

Running "clean:tmp" (clean) task
>> 0 paths cleaned.

Running "copy:build" (copy) task
Created 1 directory, copied 44 files

Running "metadata:all" (metadata) task
Fatal error: fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by bastimeyer** [comment]
You can't just download and use the zip/tarball that github is creating for each tag in the repository, you need to clone it. The grunt metadata task [is reading the list of all contributors](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.1/build/tasks/custom/metadata.js#L68), that's why.

```bash
git clone https://github.com/bastimeyer/livestreamer-twitch-gui
cd livestreamer-twitch-gui
npm install -g bower grunt-cli
npm install
grunt release
```
