### ISSUE TITLE
I can't open chat.

### ISSUE THREAD

**Issue by lapulzi** [bastimeyer/livestreamer-twitch-gui#187]
I first used the program and had the chat enabled but now when I tried opening it up today, the chat doesn't pop up and when I click on the "Open Chat" on the interface when you select what channel you are viewing, the button animation just appears to shake left and right like its emoting the "No" animation.

**Comment by bastimeyer** [comment]
> emoting the "No" animation

Did you check your chat configuration in the settings menu? You're seeing this animation because the GUI was either unable to find the executable of your selected chat program or you messed up the parameters, etc.

Which chat application did you choose? What OS do you use?

**Comment by lapulzi** [comment]
I had it on open chat each time a stream starts up and then I looked through my settings again. Apparently it was on Chronium instead of Chrome... That fixed it. Thanks for pointing out my user error xD
