### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by stalq3r** [bastimeyer/livestreamer-twitch-gui#188]
Suggest you to add an option with page autorefresh. Would be great to have a possibility to set a page autorefresh by time. Any page, any interval.
Additionally i suggest you to remade notification, its useless right now. And i would like to see an option to add notification to any stream without FOLLOWING. Its like on chrome addon "Twitch Tracker"
Thanks for your programm

**Comment by bastimeyer** [comment]
> autorefresh

See #177.

> Additionally i suggest you to remade notification, its useless right now.

I'm actually not sure if I want to comment on this undetailed and also slightly impudent "suggestion".

> without FOLLOWING

For that you'd need to make countless single API requests for each channel every minute, so this is a very inefficient way of implementing notifications. Also, why would you ever want to get notifications for channels that you are not following? Just follow the channel...
