### ISSUE TITLE
Suggestion to improve refreshing

### ISSUE THREAD

**Issue by jaggedShrapnel** [bastimeyer/livestreamer-twitch-gui#189]
It seems that fetching the followed streams in the Streams page occasionally returns an error page. I don't mind that. Once given this screen however, the refresh button doesn't work and I need to go to another page (Subscriptions, Channels, etc.) and come back to Streams to get around the error page. Minor I know, but it would be nice to be able to refresh as expected. Love the software, thanks for reading.

**Comment by bastimeyer** [comment]
Thanks
