### ISSUE TITLE
Start minimised (to tray)

### ISSUE THREAD

**Issue by Lombra** [bastimeyer/livestreamer-twitch-gui#198]
Hi,
I only use this for the notifications really, and I have added it to autostart, but I have to minimise it every time, then. Would be great if it could hide in the tray bar immediately at startup.

**Comment by bastimeyer** [comment]
See here...
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Launch-parameters

**Comment by Lombra** [comment]
Hadn't thought of checking here, sorry. Works great, thanks!
