### ISSUE TITLE
Livestreamer GUI crashing on startup

### ISSUE THREAD

**Issue by tomoppentopper** [bastimeyer/livestreamer-twitch-gui#201]
Hi, 

I've been using the Livestreamer GUI fine for months now, but after running a bunch of Windows 7 updates, the application crashes with a 0xc000001d failure to initialize error. It's been working fine up until last night. I've reinstalled the Livestreamer standalone client, along with updating the files for the GUI client as well, and trying it on a different drive. I've looked through the crashdumps with WinDbg, but I didn't have any luck exactly what is causing the crash. Are there any log files stored in appdata folders for the GUI client I could look through to try and figure out what's happening?

I apologize if this is the wrong place for this type of issue, I'm not sure if it's happening to others though.

**Comment by bastimeyer** [comment]
Google lists similar issues with Chromium, the base of NWjs (the platform that's being used), so I'm not sure if I can help you here.

Did you already try to delete the app cache folder? You can find it here:
`%LOCALAPPDATA%\livestreamer-twitch-gui`

**Comment by tomoppentopper** [comment]
I just gave that a shot, but with no luck. I don't know if this matters or not, but in addition to bringing my machine current with Windows Updates last night, I also moved my Downloads folder, Music and Documents to another drive, mapped with a different letter (via the Library move command). Would this possibly cause the issue?

**Comment by bastimeyer** [comment]
> Windows Updates

I don't use Windows, but doesn't it have this reset feature that creates snapshots of the current state before each update? Maybe you should use that.

> mapped with a different letter

No, if the cache folder is missing, a new one will automatically be created. No paths besides `%LOCALAPPDATA%` and `%TMP%` are being accessed...

Apart from that, I don't have any idea how I could help you, sorry :disappointed: 
Just google this error code, there are a bunch of other people who are also having this issue.

**Comment by tomoppentopper** [comment]
I'm combing through the crashdumps to see if I can figure anything out. :) Do you know of another program built for x64 Win 7 that I could run to test if it's the NWjs platform causing this issue?

**Comment by bastimeyer** [comment]
I think that your system upgrade somehow messed up some system libraries that NWjs is using.

> Do you know of another program built for x64 Win 7 that I could run to test if it's the NWjs platform causing this issue?

Just download [NWjs](https://github.com/nwjs/nw.js) itself and start it without any application code.
You should also open an issue thread over at their repo if the issue persists.
