### ISSUE TITLE
Implement Automatic Refresh for the Streams Page

### ISSUE THREAD

**Issue by CryZe** [bastimeyer/livestreamer-twitch-gui#206]
It would be pretty cool if the Streams page would automatically refresh everything now and then. That way you could just leave the LiveStreamer GUI open and look at the current streams whenever you want without having to press the refresh button.

**Comment by bastimeyer** [comment]
Auto refresh has been added in the latest release... You need to active it in the settings first, though...
See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/177#issuecomment-167099431
