### ISSUE TITLE
Linux - Unexpected version check output

### ISSUE THREAD

**Issue by IDeadFishI** [bastimeyer/livestreamer-twitch-gui#211]
Hello,

I'm using Debian Jessie with freshly installed livestreamer 1.12.2.

When lauching a stream, I get this:

![image](https://cloud.githubusercontent.com/assets/17099940/12868025/288f3e76-ccfd-11e5-909b-11b009dd560d.png)

Here is the output of 
`livestreamer --version --no-version-check
Traceback (most recent call last):
  File "/usr/bin/livestreamer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: livestreamer==1.12.2
`

I get the same error when lauching manually a stream via command line.

I hope this can help.

EDIT : sorry, the code is ugly, I don't know how to indent.

**Comment by bastimeyer** [comment]
Something is wrong with your livestreamer installation...
#185 #179

**Comment by bastimeyer** [comment]
I don't know if you've already managed to fix this, but see chrippa/livestreamer#1166. This should be exactly what you are looking for.
Also, please notice the new release `v0.12.0` from a couple of minutes ago...

**Comment by IDeadFishI** [comment]
Geez, I looked for similar issues but found nothing, thank you. You were right, the version in the official repos is broken, I simply updated it with pip (see http://docs.livestreamer.io/install.html). It's fine now.
