### ISSUE TITLE
Open normally in browser instead of livestreamer?

### ISSUE THREAD

**Issue by Lombra** [bastimeyer/livestreamer-twitch-gui#213]
I know this is pretty much the opposite of what this application is intended for, but so far I prefer watching streams in the browser. I like the notifications this brings, though.

Would there be any way to trick this application to launch the browser instead? Maybe replace the livestreamer executable with something else?

**Comment by bastimeyer** [comment]
No, that would be silly. The whole stream launch mechanism is bound to livestreamer. This can't be done by "simply" replacing the exectuable path and parameters...

Why would you also ever want to watch streams in your browser via flash?
The **only reason** I can see is the chat being integrated directly into the window. Everything else is just **terrible** from a performance or ease of use aspect. VODs *could* be another reason, but this will be tackled and hopefully integrated soon.

**Comment by Lombra** [comment]
Just to be clear, I didn't mean for any changes to be done to this application to achieve the described behavior. Rather if you had some idea of whether it could be done "externally".

Chat would be the main reason that I prefer browser, indeed. But also, combined with the fact that the browser view will give me a layout specifically designed for the purpose, wheras opening your media player it could end up anywhere, with any size. I don't really understand what the terrible ease of use is about, though?

I completely respect and understand using good practices and avoiding bad technologies, but for me, user experience will _always_ come before performance concerns. I really don't care if something is Flash if it does the job better than the alternatives.

**Comment by bastimeyer** [comment]
> whether it could be done "externally"

You could write a shell script as a video player replacement that will open the stream in your browser and do nothing else then. It would need to keep running, so livestreamer will keep running as well, so the user is able to see the popup in the GUI. When clicking the close button in the GUI, livestreamer would then terminate it. The shell script can have it's own arguments set by the `--player-args` livestreamer parameter, so you can launch whichever URL you want. Here is a working example:

**launch-twitch-in-browser.sh**
```bash
#!/bin/bash
xdg-open "$1"
tail -f /dev/null
```

Set `--player` to `/path/to/launch-twitch-in-browser.sh`
and `--player-args` to `"http://twitch.tv/{name}"`

This works on Linux, on OSX you need to replace the `xdg-open` command with the `open` command. Please don't ask me for a Windows batch file... :confused: 

> Chat would be the main reason that I prefer browser, indeed.

Maybe you should use a different video player or give it explicit parameters for the window position/size/behavior. You can do this easily with MPV, which is the best player in my opinion.
As long as the GUI doesn't have its own chat implementation, you can open it in the Chromium/Chrome "app mode", which is a minimal window without any buttons. You can either move/drag it to the edge of the screen if you like or let the window manager of your system do the work, which should be the better approach. The video player can then peacefully run in maximized or fullscreen mode, or just in a simple window.
With a decent window manager you can do this for multiple videos and chats on one or multiple workspaces. This all is much better than using the twitch or multitwitch websites.

> I really don't care if something is Flash if it does the job better than the alternatives.

Even when the time comes that Twitch finally removes flash, livestreamer will still be superior. Running a stream in a dedicated application makes much more sense than doing it in the browser. It's not only the performance that matters, but also the usability and ability to customize everything to your needs. For instance, livestreamer lets you configure the stream buffering. You can't do this while using the website.

**Comment by natostanco** [comment]
you could probably script a wrapper that binds your preferred video player and irc client and have the smoothest and seamless experience possible but it is indeed extrawork

**Comment by bastimeyer** [comment]
> you could probably script a wrapper that binds your preferred video player and irc client

?

By saying "bind", do you mean that both windows of the video player and chat somehow should get *glued* together? Something like that would be highly specific to the system and software being used. Just think about different configurations for a sec. This is absolutely not the task of a "wrapper script" and should be done by the user himself by making use of the features of the system's window manager.
Even if you want to write a script, you simply don't know the process ID and window ID of the video player livestreamer is launching.

I'm closing this thread now, since I've already posted how the web browser can be launched instead of the video player. Please have in mind that while doing this, livestreamer will still download the stream from twitch in the background, which means that you're downloading it twice.

**Comment by natostanco** [comment]
you could launch both the player and the chat into a virtual desktop and configure preferred tiling, that seems like enough glue for me. Also I am obviously not that familiar but why would you need the process and window ID in the first place? Wouldn't the window title be enough for a more direct approach?

**Comment by bastimeyer** [comment]
> Wouldn't the window title be enough for a more direct approach?

Using the window title doesn't work while watching multiple streams at the same time or when having another instance of the same player opened...

Support for custom player-launch scripts can be added once stream recording has been implemented. This feature will require the GUI to open the player (instead of livestreamer), so it's process id can then be used as a parameter for those scripts as well.

**Comment by Lombra** [comment]
Thanks.

I managed to come up with a decent solution since I already have Livestreamer installed anyway.
I put 'cmd /c' as the Livestreamer player just to satisfy the need for a valid executable. Then I select Automatically open chat, pick Custom application, and use this:
`"C:\Program Files\Mozilla Firefox\firefox.exe" http://www.twitch.tv/{channel}`
