### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by sesambrot1** [bastimeyer/livestreamer-twitch-gui#222]
Hey guys,
I'm quite new to all this but I followed a yt tutorial where everything worked out fine but I can't start my stream in any way and I don't understand the problem. I even changed the stream name in the livestreamer config but nothing is working in any way and I'm quite mad right now. Is there anyone who can help me? If you need a specific file please tell me where I can find it, livestreamer is installed in the standard path, I didn't change anything.
Here is a link to the error:
https://picload.org/image/wcdwrdp/unbenannt21.jpg

**Comment by bastimeyer** [comment]
> I even changed the stream name in the livestreamer config

???

It looks like you've added the contents of a logfile to your livestreamer config. Why else would livestreamer complain about those invalid arguments which look like log output? This is definitely not an issue related to Livestreamer Twitch GUI.

You actually don't have to modify your livestreamer config file. Just install livestreamer, download and launch the GUI and it should work automatically. I don't know which youtube tutorial video you've followed, but in the project's wiki, you can find all necessary informations:
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki
