### ISSUE TITLE
Application closes on its own

### ISSUE THREAD

**Issue by Gabriev** [bastimeyer/livestreamer-twitch-gui#223]
As soon as someone on my follow list goes live or ends the stream, application closes without any errors. It happens only with desktop notifications enabled on Windows 7. It started acting that way only recently without changing any settings or installing anything new, so the configuration hasn't change.

**Comment by bastimeyer** [comment]
Are you using the latest version (v0.12.0)?

> As soon as someone on my follow list goes live or ends the stream, application closes without any errors.

Application crashes are usually not silent. I'd like to see the output of this.
All exceptions thrown should be caught by a global listener function which logs the message and the app should keep running. A crash is a bit unexpected and may be related to NWjs itself, but I don't know yet.

Could you please run the application from the master branch and see if this error persists? All infos can be found [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.12.0/CONTRIBUTING.md#developing-and-building).

If you want know how to do this or if you don't want to, you could also try starting the application from the Windows command prompt (cmd.exe) by running this command:
`\path\to\livestreamer-twitch-gui.exe 1> output.txt 2>&1`
This will write every output from `stdout` and `stderr` to a file. Thanks!

**Comment by Gabriev** [comment]
Yes, I was using the latest version.

I followed your instructions, and this behavior still persists after running the application via the "Run the "precompiled" application" method and "Run the application from source" method. First method doesn't produce any errors, the second gives this in the CLI:
```
D:\Utilities\livestreamer-twitch-gui-master\src>grunt run:src
Running "run:src" (run) task
Using v0.12.3
Create cache folder in D:\Utilities\livestreamer-twitch-gui-master\build\cache\0.12.3
Using cache for: win64
Launching App
App exited with code 3221225477

Done, without errors.
```

**Comment by bastimeyer** [comment]
> App exited with code 3221225477

This code is `0xC0000005` in hexadecimal notation and in Windows it means that the application tried to access memory it was not allowed to.
This can have many reasons, but I highly doubt this is the fault of the JavaScript code here, since we don't have any influence on the memory allocation. This may be an issue of NW.js itself, one of its components like chromium or v8, or a dependency of NW.js installed on your Windows machine.

I can't help you any further here. Just try to google this error code...

**Comment by bastimeyer** [comment]
Maybe you should try to delete your temp and config folders:
`%TEMP%\livestreamer-twitch-gui`
`%LOCALAPPDATA%\livestreamer-twitch-gui`

**Comment by Gabriev** [comment]
Thanks for the help, despite I wasn't able to resolve the issue. Although I have a strong suspicion it had to do with Windows sneaking in some updates, even though I have them set not to install automatically.

**Comment by bastimeyer** [comment]
:disappointed: 
See #201, maybe it's related...
