### ISSUE TITLE
Change livestreamer to mpv+youtube-dl

### ISSUE THREAD

**Issue by edo44** [bastimeyer/livestreamer-twitch-gui#225]
I have issues with livestreamer in my windows 7 since ages. Like this:

`$livestreamer.exe http://www.twitch.tv/basetradetv 
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/basetradetv
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "__main__.py", line 128, in <module>
  File "__main__livestreamer__.py", line 9, in <module>
  File "livestreamer_cli\main.py", line 886, in main
  File "livestreamer_cli\main.py", line 475, in handle_url
  File "livestreamer_cli\console.py", line 62, in exit
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 311: ordinal not in range(128)`

It's a issue with livestreamer, but even using the nightly I cannot fix the problem, and the developers of livestreamer are veeeery slow to fix problems, so I was wondering if I could use mpv+youtube-dl instead of livestreamer in some way.

I mean, if I want to use youtube-dl with mpv usually I just put in the terminal `mpv <link>` and it works fine, so it shouldn't be a big deal I guess.

thanks

**Comment by bastimeyer** [comment]
> It's a issue with livestreamer

This looks more like an issue with Python on your system. I'd recommend reinstalling livestreamer by using the Windows installer.

> I was wondering if I could use mpv+youtube-dl instead of livestreamer in some way

No, the whole application is built on top of livestreamer. This is not going to work.

**Comment by edo44** [comment]
> This looks more like an issue with Python on your system. I'd recommend reinstalling livestreamer by using the Windows installer.

I uninstalled everything, updated python and installed livestreamer with the installer, all stable. Same damn error.

> No, the whole application is built on top of livestreamer. This is not going to work.

k

**Comment by bastimeyer** [comment]
> updated python

Doesn't come Livestreamer on Windows with its own portable Python version (2.7)??? Maybe that's your issue here. If you don't use Python for anything else, then uninstall it from your system.

Besides that, I don't have any clue what could cause that issue.
