### ISSUE TITLE
Chatty crashes after prolonged use

### ISSUE THREAD

**Issue by Jademalo** [bastimeyer/livestreamer-twitch-gui#231]
This has been happening for a while now, so there's no start date I can really think of.
I have Chatty set to launch through LTGUI, and essentially, after a few hours of use, Chatty will hang. I've sent the Chatty logs to it's developer, but he can't see anything specifically causing the problem. After looking at it further, I've noticed that chatty will come back to life if I close LTGUI, so I believe the issue is related to this.

It's a full on traditional hang. It doesn't crash, but it becomes entirely unresponsive in every way. It happens no matter the chat, no matter the message frequency, and at a random time.

If there's any logs that are needed, I'll get them and add them.

Thanks

**Comment by bastimeyer** [comment]
Could you please try opening chatty via the shell and see if it freezes as well?
[These are the used parameters...](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.12.0/package.json#L180) Don't forget to replace the `{variables}`.

Linux, OSX:
`java -jar "/path/to/chatty.jar" -connect -single -user "{user}" -token "{token}" -channel "{channel}"`

Windows:
`javaw -jar "C:\path\to\chatty.jar" -connect -single -user "{user}" -token "{token}" -channel "{channel}"`

**Comment by Jademalo** [comment]
Ok, that's running now. I'll reply again if it freezes, although I don't expect it to. Mainly because of the whole closing LTGUI fixing it thing.

**Comment by Jademalo** [comment]
Been running it for 5 1/2 hours through the command, it's still fine.

**Comment by bastimeyer** [comment]
I've changed some child process spawn params in the ChatService.
Would you please be so kind and test the latest commit from the master branch?
5fd41f5d972bfb849da71d30bf63a893ccb901ce

Build instructions can be found [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.12.0/CONTRIBUTING.md#developing-and-building).

There's nothing I can do at this point. If the issue persists, you should check your system's memory consumption, etc...

**Comment by Jademalo** [comment]
Alright, I'll build it and try.
I don't know what to say about it being my system since I recently did a fresh win10 install with fresh config and the issue persisted.

I'll reply in a few hours, or if it crashes.

**Comment by Jademalo** [comment]
Having build issues, got node.js and git installed fine, installed grunt fine, did npm install fine, then did grunt release and it completed fine. However, I can't actually find the build. There are temp files getting modified, but the binary isn't anywhere.

**Comment by bastimeyer** [comment]
Check the `build/releases/livestreamer-twitch-gui/` directory...

As an alternative to building the application, you can also simply run `grunt metadata less:source run:src`

**Comment by Jademalo** [comment]
It's not making a /releases/ directory. build only has resources, tasks and tmp. Weird.

That second method gives me a `warning: No platform to build!` error

**Comment by Jademalo** [comment]
Good news!
After leaving a stream open for 7 hours, it's still absolutely fine. That seems to have fixed it!

I'll let you know if it happens again, but I'm reasonably confident this has sorted it.
Thanks!

**Comment by bastimeyer** [comment]
Thanks for taking the time!
