### ISSUE TITLE
Host feature

### ISSUE THREAD

**Issue by ChrillePan** [bastimeyer/livestreamer-twitch-gui#233]
Hey bastimeyer,
I would love to see a host feature on the window, where you can open the chat and view details about the stream. 

So far I need to go to my own stream and have to type in the host command by myself.

Thanks for this great work so far,

Greetings,
ChrillePan

**Comment by bastimeyer** [comment]
> on the window, where you can open the chat and view details about the stream

Do you mean on the stream launch dialog?

> So far I need to go to my own stream and have to type in the host command by myself.

The prupose of this application is for viewing only. Everything broadcasting related is not intended to be implemented.

**Comment by ChrillePan** [comment]
Hey,
Yes! I mean the dialogue which pops up after you hit the play button.

I dont see the host button as a "broadcasting" only thing. If we had tournaments or stuff on the speedruncommunity we host our runnerchannels or just hosting channels of friends. 

Would be really nice to have.

ChrillePan

**Comment by bastimeyer** [comment]
I just can't build everything into the app and I have to draw a line at a certain point. For me this kind of feature is out of scope of this application. People who are hosting other channels are usually broadcasters themself and are using the features on Twitch's website. If you are not a broadcaster, then you will most certainly not have many followers, so hosting a channel as a regular viewer is absolutely pointless.

I really don't see the need of implementing something that only a tiny fraction of the users will ever use, sorry.
