### ISSUE TITLE
Application badge settings not having an effect since 0.13.0

### ISSUE THREAD

**Issue by zawnk** [bastimeyer/livestreamer-twitch-gui#238]
### Description

I just updated manually to 0.13.0 and now I don't see the number of favorite streamers that are online anymore (neither on the task bar nor on the tray icon). Haven't changed any setting. I tried enabling/disabling and restarting the app, but to no avail. It shows no number, even though at least one favorite streamer is online. [1]

### Expected / Actual behavior

Actually show the numbers of favorites online/streaming.

### Reproduction steps

Start the program, have favorites and check settings "Application badge" and enabled "Desktop notifications".

### Environment details (operating system, etc.)

Win7 x64, haven't change in between updates. Switched from 0.12.x (can't remember exactly which one, might've been the last before 0.13.0) to 0.13.0 (livestreamer-twitch-gui-v0.13.0-win64.zip). Using with livestreamer 1.12.2 even though this should make no difference.

### Comments, logs, screenshots, etc.

[1]
http://i.imgur.com/ypBYEDE.png
http://i.imgur.com/Cf16WET.png
http://i.imgur.com/2FNyQE6.png

**Comment by bastimeyer** [comment]
I can't reproduce this. Are you sure that desktop notifications are enabled and also not paused?

The responsible code for the application badge has not been changed in the last couple of releases.
https://github.com/bastimeyer/livestreamer-twitch-gui/blame/v0.13.0/src/app/services/NotificationService.js#L154-L169

Please try to delete the application folder and re-extract the archive. If this doesn't work, delete your config folder in `%LOCALAPPDATA%\livestreamer-twitch-gui`.

**Comment by zawnk** [comment]
>Are you sure that desktop notifications are enabled and also not paused?

What do you mean, not paused? I skimmed the settings and didn't see anything with pausing them? So I didn't change anything consciously there :D But yes, desktop notifications are on.

http://i.imgur.com/Feo2hgb.png

>Please try to delete the application folder and re-extract the archive. If this doesn't work, delete your config folder in %LOCALAPPDATA%\livestreamer-twitch-gui.

Did both things. First just extracting again and starting, still not working. Then I deleted the settings, configured it roughly to how I had it, and still doesn't work. Two of my followed streamers are now online.

**Comment by bastimeyer** [comment]
> didn't see anything with pausing

There's a pause option in the tray icon's context menu. But this option is not persistent, so I guess it doesn't matter.

> http://i.imgur.com/ypBYEDE.png

From what it looks like, you are having small icons on your Windows taskbar. I don't use Windows, but afaik, Windows doesn't show badges on small icons.

> neither on the task bar nor on the tray icon

The tray icon never had an online counter.

**Comment by zawnk** [comment]
>From what it looks like, you are having small icons on your Windows taskbar. I don't use Windows, but afaik, Windows doesn't show badges on small icons.
>The tray icon never had an online counter.

Whoops, those two seem to be right. The big task bar icon does indeed have a counter. Is there a way that the tray icon gets a small number? Turning this into a feature request, haha. 

I'm certain that I saw somewhere how many of my favs are online. Was there a number/icon somewhere in the client itself? 

http://i.imgur.com/vwRxl8h.png

Maybe on/next to the user icon? Or am I so confused that I make memories up now? I'm very confused right now :D

**Comment by bastimeyer** [comment]
> Is there a way that the tray icon gets a small number?

No. NW.js doesn't provide an API for that. Icons have to be images on the filesystem. I'm not going to implement something that renders images, writes them to the filesystem, so NW.js can read them again. That would be stupid.
https://github.com/nwjs/nw.js/wiki/Tray#trayicon

> I'm certain that I saw somewhere how many of my favs are online

There's an indicator in the headline of certain menus.
