### ISSUE TITLE
Mouse forward/back button recognition in browser

### ISSUE THREAD

**Issue by leafonthewind7** [bastimeyer/livestreamer-twitch-gui#242]
Hello, I was wondering if it would be possible to add input recognition for forward and back mouse buttons in the browser.

**Comment by bastimeyer** [comment]
See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/85#issuecomment-98985832 or https://github.com/bastimeyer/livestreamer-twitch-gui/issues/180#issuecomment-167425713
