### ISSUE TITLE
Show number of viewers and broadcasters in My Games

### ISSUE THREAD

**Issue by AnKlaGo** [bastimeyer/livestreamer-twitch-gui#243]
First of all, thanks for this great application! I rarely visit the actual twitch website thanks to this and livestreamer.

That being said, the only reason I actually visit their website is when none of my followed streamers is only and I want to browse my followed games. Since I have some niche games in my list where sometimes nobody is streaming either and in MyGames the # of broadcasters and viewers is not shown on hover( but it is in "Top Games). 

Any chance of adding this in "My Games" as well as sorting by viewer count?

Thanks!

**Comment by bastimeyer** [comment]
The currently used Twitch API endpoint doesn't return channel and viewer numbers for followed games. That's the reason why they are missing, see #148. The Top Games API response does include these numbers.

I'll have a look at the Twitch website tomorrow and will see which one they are using there. This is all part of the undocumented API, so I'm not sure.
