### ISSUE TITLE
OSX Settings Keyboard Shortcut

### ISSUE THREAD

**Issue by memco** [bastimeyer/livestreamer-twitch-gui#245]
### Description

On OSX, it is common for <kbd>CMD+,</kbd> to open the preferences. It would be nice to have this shortcut activate the settings pane.

### Expected / Actual behavior

Currently this shortcut does nothing.

### Environment details (operating system, etc.)

Livestreamer GUI 0.13.0 on OSX  10.11.4

**Comment by bastimeyer** [comment]
Thanks for the suggestion
