### ISSUE TITLE
Google Chrome as method not working

### ISSUE THREAD

**Issue by skulblakka** [bastimeyer/livestreamer-twitch-gui#248]
I just switched to the newest commit in the master branch (86feeac) and I noticed that using Google Chrome as the chat method in the settings does not work correctly. 
Instead of opening the Chat inside an app/minimal Chrome window, a normal Chrome Window with an empty tab is being opened. 
Using the command line to open an app window with ```chrome.exe "--app=http://twitch.tv/CHANNELNAME/chat"``` works as intended.

I'm on Windows 10 and using Version 50.0.2661.102 m (64-bit) of Google Chrome.

**Comment by skulblakka** [comment]
Also when looking at the command line arguments passed to Chrome, the argument is listed as ```--app=\h\t\t\p\s\:\/\/\w\w\w\.\t\w\i\t\c\h\.\t\v\/\ [...]```

**Comment by bastimeyer** [comment]
Thanks!
