### ISSUE TITLE
Pause streaming

### ISSUE THREAD

**Issue by EderO** [bastimeyer/livestreamer-twitch-gui#252]
I use VLC as a player for livestreamer GUI, i want to know, if its posible to hit pause icon on VLC player while seeing a streaming, and the streams just stays in "buffer" or something, so 30 minutes or 1 hour later i can hit unpause i continue watching the streaming from that "pause" point.

This is something i miss, cause just plays for 5 secs, and then reloads the streaming in "live". This functionality i used in "tardsplayer".

Thanks in advance.

**Comment by Poorchop** [comment]
I think that this is an issue with your video player. I use mpv and after pausing, it picks off where it left off and continues to do so until I explicitly fast forward. In any case, I don't think this has anything to do with Livestreamer and even much less to do with this application, which is just a GUI frontend for Livestreamer.

**Comment by EderO** [comment]
Ok, gonna check, its strange cause with tardsplayer, and using VLC its working ok.

Thanks

**Comment by bastimeyer** [comment]
If you're using VLC and having issues with the stream buffering, you should increase its buffer size. You can do this in the VLC settings or by setting a VLC launch parameter in the GUI. See the [Wiki](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration) for more informations.

To see all available parameters for VLC, run `vlc -H` or click [here](https://wiki.videolan.org/VLC_command-line_help).
The parameter you're looking for could either be `--file-caching` or `--network-caching`. I don't use VLC, so I'm not sure.

> In any case, I don't think this has anything to do with Livestreamer and even much less to do with this application, which is just a GUI frontend for Livestreamer.

This, thanks.

**Comment by EderO** [comment]
thanks for the tips.
