### ISSUE TITLE
Built-in HTML 5 player

### ISSUE THREAD

**Issue by Coriou** [bastimeyer/livestreamer-twitch-gui#255]
This a feature request, and probably a big one. But it's, in my opinion, what would turn this application from good to great. I did check closed issues but I was very surprised to not find this request (unless I missed it).

While I was looking around for a Twitch client, I stumbled upon a Mac app called [LiveNow](https://itunes.apple.com/en/app/livenow/id948520249?mt=12) which is essentially the same thing, except they aim at providing the full Twitch experience within their client (both videos and chat).

I think the user experience & user interface of LiveStream Twitch GUI are better than LiveNow's, but functionality wise - for now - the later is way ahead.

I understand it's a technical challenge, but hey, reaching the current state of the application was already challenging I'm sure !

**Comment by Poorchop** [comment]
I think this project is just supposed to be a simple frontend for Livestreamer. The playing and viewing of videos is meant to be outsourced to an external player. Incorporating a built-in viewer would essentially just be recreating the entire Twitch site but with the limitations imposed by the API.

**Comment by bastimeyer** [comment]
This has already been requested in #29 (and partially in #213, see https://github.com/bastimeyer/livestreamer-twitch-gui/issues/213#issuecomment-181981547)...

> LiveStream Twitch GUI

The application is called "Livestream**ER** Twitch GUI", because it's a [GUI for Twitch.tv for **Livestreamer**](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/master/README.md).

> I understand it's a technical challenge, but hey, reaching the current state of the application was already challenging I'm sure !

These kind of "feature requests" are delusional.
Why should I, a CS-student who's not being paid for all this, be able to solve this problem of delivering a functional HTML5 video player, while Twitch, a billion dollar company, is struggling with that for months and years? If you're looking for a better twitch experience, wait until the Twitch devs upgrade their website, which btw is a disaster from a technical point of view, not only the player.

The GUI will never embed a video player, it's just a tool for building the livestreamer parameter list and executing it. It has nothing to do with fetching the stream data from Twitch, that's what Livestreamer is doing.

> LiveNow

I don't know this app, but this just looks like some parts of the Twitch website being used in something like NWjs, Electron, etc... The sourcecode is not available and I'm not sure if what they are doing is legal, since they are clearly using assets of the Twitch website. They are also charging $3 for this. Oh boy...

**Comment by Coriou** [comment]
> This has already been requested in #29 (and partially in #213, see #213 (comment))...

My bad, completely missed those.

> The application is called "LivestreamER Twitch GUI", because it's a GUI for Twitch.tv for Livestreamer.

I get that now. Also, I apologize I opened this request before correctly understanding the software I was discussing about.

> These kind of "feature requests" are delusional.
Why should I, a CS-student who's not being paid for all this, be able to solve this problem of delivering a functional HTML5 video player, while Twitch, a billion dollar company, is struggling with that for months and years? 

I believe a fully functional HTML5 player is already functional and public. It has it's issues still though. One I ran into is that it's "impossible" to embed on a website behind HTTPS because the video streams do not support SSL which raises a mixed content exception. That's a problem an application like this one will not suffer from. Of course, that would totally defeat the purpose of this application, which is a GUI for LiveStreamer (I get that now)

> If you're looking for a better twitch experience, wait until the Twitch devs upgrade their website, which btw is a disaster from a technical point of view, not only the player.

I'm indeed looking for a better Twitch experience, and I couldn't agree more with your last statement. We could write a lot about companies like Twitch (there's a lot more, such as Steam for instance) which are very successful yet built on poor technical grounds.
I don't plan on waiting on Twitch's site update though, because I have no faith in them succeeding at providing a decent experience. I will carry on exploring other options.

You work is much appreciated however, please don't think I meant otherwise !

**Comment by bastimeyer** [comment]
It's alright...
It just can get somewhat annoying after a while reading countless of requests from people who think I could magically fix all the issues Twitch currently has. I get these all the time, not only here, but also on reddit or via email.

> I believe a fully functional HTML5 player is already functional and public.

AFAIK it's only working in Safari on OSX right now. I don't know what they are doing, but every major browser should be able to read HLS streams.

- https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Live_streaming_web_audio_and_video
- http://caniuse.com/#search=MSE
- https://github.com/dailymotion/hls.js

> We could write a lot about companies like Twitch (there's a lot more, such as Steam for instance) which are very successful yet built on poor technical grounds.

That's true.

> You work is much appreciated however, please don't think I meant otherwise !

Thanks

**Comment by Coriou** [comment]
> It's alright...
It just can get somewhat annoying after a while reading countless of requests from people who think I could magically fix all the issues Twitch currently has. I get these all the time, not only here, but also on reddit or via email.

I understand.

> AFAIK it's only working in Safari on OSX right now. I don't know what they are doing, but every major browser should be able to read HLS streams.

I agree that every browser should support HLS. Right now, I also think only Safari on Mac does. I'm looking at a player that recently became free to use called [Viblast](http://viblast.com) and that Dailymotion hls.js you linked seems very interesting, I'll take a look.

However, Twitch's HTML5 player works on every browser I have tried (Firefox & Chrome on Mac). You can try it here if you haven't already : http://player.twitch.tv/?channel=sovara_play&html5 (you can replace the channel arg by whichever Twitch channel you want).
Technically though, I don't know if they actually serve HLS and somehow decode it in the browser through their player of if it's actually being transcoded. I will also look into that :)
