### ISSUE TITLE
Refresh button unresponsive after disconnect

### ISSUE THREAD

**Issue by peoleo** [bastimeyer/livestreamer-twitch-gui#258]
### Description

After experiencing a network disconnect and reaching the "Failed to load resource page", after reconnecting, the refresh button does not attempt to reload the page.  

### Expected / Actual behavior

The page you intended to view is reloaded.

### Reproduction steps

1. Go into Top Games and select a game
2. Disconnect from the network
3. Try to visit Top Games from the Browse sidebar link
4. Reconnect to the network
5. Hit Refresh 

### Environment details (operating system, 

Ubuntu 14.04 LTS
LTG 0.13.0

**Comment by bastimeyer** [comment]
Thanks for reporting!
