### ISSUE TITLE
Invisible tray icon on Windows

### ISSUE THREAD

**Issue by skulblakka** [bastimeyer/livestreamer-twitch-gui#259]
I noticed that instead of the icon I only have a empty square where the icon should be (I can still right click on it and it shows the context menu as expected). I also tried changing it to task bar only and back to both in the GUI settings tab but the icon just reappeared invisible.

I'm running 64 bit Windows 10 and compiled the newest commit (7858778) without errors.

**Comment by bastimeyer** [comment]
Thanks!
This is caused by an unexpected side effect of #237... Let me see...

**Comment by solomongrundy6** [comment]
I am having this same problem, except on Linux.  Using version 2.2.0
