### ISSUE TITLE
Uninstalling Livestreamer 1.12.2

### ISSUE THREAD

**Issue by fuckdisshit** [bastimeyer/livestreamer-twitch-gui#261]
Im trying to uninstall the software from my system (win 7 64bit) but it doesnt let me do it.
I keep getting the message that i dont have enough rights on this account and that i should contact the systemadministrator. Problem is that i am the systemadministrator and have all the necessary rights to install and uninstall programs. I also tried to uninstall it manually by using the application "uninstall-livestreamer" found in the "Livestreamer folder and by that i get a different error but the actual text in it is very similar to that i get when trying to uninstalling it via windows.

Am I the only one having problems with that?
Is there any way to uninstall this thing properly?
Sry for my english

If anyone should care about my specs:

win 7 64 bit
120 gb ssd software is installed on the ssd
1tb hdd
The other components shouldnt really matter...

**Comment by bastimeyer** [comment]
[Wrong repo...](https://github.com/chrippa/livestreamer)
