### ISSUE TITLE
Which file do I choose as the executable on Mac?

### ISSUE THREAD

**Issue by long-horse** [bastimeyer/livestreamer-twitch-gui#266]
There are so many files in ~/Documents/livestreamer and ~/anaconda/lib/python3.5/site-packages/livestreamer (also /livestreamer_cli in site-packages) and since I don't know my way around python this is getting more complicated than I initially thought it would be to watch subscriptions in vlc on Mac.

**Comment by bastimeyer** [comment]
This is an issue tracker for reporting **bugs** of the *"Livestreamer __Twitch GUI__"*...

You should read the [Livestreamer documentation](http://docs.livestreamer.io/install.html) if you're having troubles installing Livestreamer.
