### ISSUE TITLE
Can't use my profile.

### ISSUE THREAD

**Issue by VinylNix** [bastimeyer/livestreamer-twitch-gui#27]
I have a problem where I can't click on or use anything profile related such as: Recent Activity, Favorites, Subscriptions etc. Although I've authenticated with livestreamer via editing the configuration file (adding twitch-oauth-token=). Is there a correct solution to this or is it just not implemented yet?

And by the way, thank you for creating such a great utility.

**Comment by bastimeyer** [comment]
I'm closing this thread for now: desktop notifications and all the internal logic was updated in the [v0.7.0 release](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.7.0)... All the other missing features will be implemented in the future.
