### ISSUE TITLE
Clicking images in channel details that have no link behind them opens the Computer explorer window

### ISSUE THREAD

**Issue by Robby-** [bastimeyer/livestreamer-twitch-gui#274]
### Description
When viewing a channel's details and it has an image without a link behind it, clicking this image will open the `Computer` explorer window (where it shows your hard drives, optical drives, that stuff).

### Expected / Actual behavior
Expected: Nothing should happen.
Actual: The `Computer` explorer window opens.

### Reproduction steps
1. Click an image that has no link behind it.
2. The `Computer` explorer window opens.

### Environment details (operating system, etc.)
Windows 7, 64-bit.

**Comment by bastimeyer** [comment]
Thanks for reporting!
