### ISSUE TITLE
livestreamer-twitch-gui is not hidpi-aware on linux

### ISSUE THREAD

**Issue by Jujstme** [bastimeyer/livestreamer-twitch-gui#277]
### Description

The program does not determine if the desktop enviroment is HiDPI and, therefore, does not scale UI elements on HiDPI, thus rendering the GUI in a very small size (screenshot attached).
### Expected / Actual behavior

The program is supposed to read the scaling settings for GTK+ applications, or at least provide a command-line option for manually setting up scaling. 
### Reproduction steps
1. start a desktop enviroment (eg. Gnome3) in a HiDPI display
2. set up scaling for your desktop enviroment (in Gnome3 this is done automatically, alternatively it's possible to set up scaling via gnome-tweak-tool)
3. start livestreamer-twitch-gui
### Environment details (operating system, etc.)

Arch Linux x86_64
Linux kernel  4.6.4-1
Desktop enviroment Gnome3  3.20.2
### Comments, logs, screenshots, etc.

![schermata del 2016-07-24 15-52-22](https://cloud.githubusercontent.com/assets/20629184/17086148/e7688768-51b8-11e6-807d-d6be4040135c.png)

**Comment by bastimeyer** [comment]
This is a known NW.js issue on Linux for the version that's being used here right now (0.12.3).
An upgrade to one of the new and rewritten NW.js versions (>=0.13.0) is still being blocked by some other issues. The upgrade will fix the scaling issue...
See the progress here: #275 (not final)

HiDPI scaling does work on OSX and Windows, though.
