### ISSUE TITLE
Video Quality does not work correctly in 1080p60 streams

### ISSUE THREAD

**Issue by vegbrasil** [bastimeyer/livestreamer-twitch-gui#279]
### Description

Twitch [announced 1080p60 streams](https://blog.twitch.tv/the-international-on-twitch-705404e95cc2) for The International and quality settings changed from `low`, `medium`, `high` and `source` to `144p30`, `240p30`, `360p30`, `480p30`, `540p30`, `720p30`, `720p60` and `source` (1080p60).

### Expected / Actual behavior

Expected to be able to choose between available streams but only "source" is chosen.

### Reproduction steps

1. Find the channel `dota2ti`
2. Play channel and set to `low`, `medium` or `high`
3. The stream will open in `source` anyway

### Environment details (operating system, etc.)

Livestreamer Twitch Gui 0.14.0 and Livestremer 1.12.2 - Windows 10

### Comments, logs, screenshots, etc.

I'm sorry if this should not be posted here or has already been posted.

**Comment by bastimeyer** [comment]
Already fixed on the master branch, see 322cc8c...

I'm preparing a new release because of another issue, so until then you need to use the CLI for all the dota2ti channels if you're watching in a lower quality.

**Comment by vegbrasil** [comment]
Ok, I was not sure if you guys already known about that.

Thanks a lot!

**Comment by bastimeyer** [comment]
https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.14.1
