### ISSUE TITLE
dota2ti streams not working on source quality

### ISSUE THREAD

**Issue by bastimeyer** [bastimeyer/livestreamer-twitch-gui#283]
This is again an unexpected issue.
Twitch has removed the `source` quality out of nowhere from the dota2ti streams.

```
livestreamer twitch.tv/dota2ti source,best
[cli][info] Found matching plugin twitch for URL twitch.tv/dota2ti
error: The specified stream(s) 'source, best' could not be found.
       Available streams: 1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio

```

When selecting `source` in the GUI, it will use the `source,best` quality selection for livestreamer, see  https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.1/src/app/models/localstorage/Settings.js#L117

**Comment by bastimeyer** [comment]
I'm preparing another fix for that, although I really hate adding a fallback for `source`...
In the meantime, please use the CLI...
```
livestreamer twitch.tv/dota2ti 1080p60
```

**Comment by Marsinator** [comment]
livestreamer twitch.tv/dota2ti 1080p60
[cli][info] Found matching plugin twitch for URL twitch.tv/dota2ti
[cli][info] Available streams: 1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
error: Failed to start player: 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe' ([Error 740] Der angeforderte Vorgang erfordert erh÷hte Rechte)

**Comment by Marsinator** [comment]
nvm running as cmd.exe as admin fixed it

**Comment by bastimeyer** [comment]
https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.14.2

**Comment by GolemGetYeGone** [comment]
So we just dowload the installer and run it?

**Comment by romansp** [comment]
Thank you! Literally saving digital sports. :smile:

**Comment by mjbcopland** [comment]
Would it make more sense to update Livestreamer instead of the GUI? For example, this fallback won't work for any streams which only go to 720p, etc. The problem is that twitch updated the stream names to include framerate (e.g. 1080p→1080p60) and Livestreamer does not parse these properly. See [here](https://github.com/chrippa/livestreamer/pull/1429) for a quick and simple fix.

Perhaps add Livestreamer as a submodule of the GUI rather than rely on it being installed globally? Then we could make the changes ourselves rather than wait for Livestreamer to be updated.

**Comment by bastimeyer** [comment]
Well, I'm not a Livestreamer dev, so I can't do anything there... Also, I really hope that Chrippa doesn't have abandoned the project, although it pretty much looks like it. 😞 

Right now I don't want to bundle Livestreamer together with the GUI, because it really is not necessary. I'm also not sure how this would work on all three supported OSes. If the day comes that livestreamer stops working and there's no update or a fork with future support, I may consider adding an internal implementation. I'm not too sure if I want to maintain this alone, though, as it would be pretty complex.

[The added fallback btw does work](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.2/src/app/models/localstorage/Settings.js#L103-L126), because the new qualities have only been added for the TI streams, which have this strict list, up to 1080p60. All other streams still have and will very likely keep the old format, with `source`, `high`, `medium` and `low`. If they don't, then another change is indeed needed and a quality parser from the livestreamer output would make much more sense than using a list of expected qualities. The issues with this approach though is the default quality selection, which might not always match the given qualities. That's why I added the new qualities as fallback, so that the current qualities in the GUI work as well.

**Comment by mjbcopland** [comment]
I didn't realise the new formats were only for The International and thought they were for all streams. Perhaps the added fallbacks are the best option for now so feel free to ignore my earlier comments, but I wouldn't be surprised if these sort of changes are needed in the future.

**Comment by monkeyphysics** [comment]
For reference, this is the blogpost where Twitch announces an experimental quality range for this TI: https://blog.twitch.tv/the-international-on-twitch-705404e95cc2

**Comment by silentzor** [comment]
Livestreamer already checks for the values: `Available streams: 1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio`. I'm fairly certain the GUI has these options hardcoded, so it could instead update the list of available stream qualities upon error code 1, or string `error: The specified stream(s) 'source' could not be found.`

This way whenever you specify a stream quality that doesn't exist the gui will just update the available options.

**Comment by bastimeyer** [comment]
@monkeyphysics 
The blog was posted on the 2nd of august. This was reason why [`v0.14.1`](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.14.1) was published. See the changelog (and the linked commit)...
The reason for [`v0.14.2`](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.14.2) was, that Twitch suddenly switched from `source` to `1080p60` after the TI group stages and livestreamer was/is unable to parse quality names with a refresh rate and therefore doesn't know that `1080p60` is the `best` quality (fallback quality). `v0.14.2` was necessary, because the livestreamer dev seems to have abandoned his project and doesn't fix any issues anymore (#289).

@silentzor 
The GUI doesn't parse the available qualities, because this would increase the stream launch time and the livestreamer child process would have to be spawned twice. I'm not a fan of things that might confuse the user, so parsing the qualities only in case of an error and changing the quality then doesn't sound like a great idea. It would be future proof, though.
Having dynamic quality lists would also break the default quality selection. That's why it is hardcoded with fallback quality names. See the changelog or [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.2/src/app/models/localstorage/Settings.js#L103-L126).

**Comment by silentzor** [comment]
@bastimeyer  
I already checked the changelog :) The problem with hardcoded values is that if they change again they need to be manually changed and recompiled. Maybe have them as configurable options, with the defaults set to the current ones? We could then maintain a list of "working" ones on the front page in case someone wants to manually include them, and you can obviously update the configs whenever new ones are added.

**Comment by bastimeyer** [comment]
This could work.
It would require some changes to the settings menu, though. The settings currently don't have a reset button (in case someone does something stupid) and an interface for a dynamic list of qualities would need to be written.

**Comment by silentzor** [comment]
@bastimeyer 
Now that I had an even closer look, a lot of Settings.js variables could be moved to a configuration file to be honest, no reason to recompile every time those defaults are adjusted.
