### ISSUE TITLE
Stream Popup immediately disappears on certain failure

### ISSUE THREAD

**Issue by neffers** [bastimeyer/livestreamer-twitch-gui#284]
### Issue: Stream Popup closes instantly on failure

when attempting to watch a stream with an unsupported quality (dota2ti), the stream popup disappears instantly on failure, taking the CLI output with it

### Expected: Stream popup should remain to allow for troubleshooting of the issue

I believe if a stream is not found or another issue is encountered, the stream popup remains

### Reproduction steps

1. Attempt to watch dota2ti on the current release build
2. Stream popup opens, and then closes immediately

### Environment details

Ubuntu 16.04 LTS

**Comment by bastimeyer** [comment]
Already fixed with a new release... #283
