### ISSUE TITLE
Livestreamer fork ideas

### ISSUE THREAD

**Issue by bastimeyer** [bastimeyer/livestreamer-twitch-gui#289]
chrippa/livestreamer#1427

Since Livestreamer isn't being actively maintained anymore and it seems that it has been abandoned by the creator, a couple of people are now trying to organize a fork. Forking livestreamer would mean that we can be sure that issues in the future will get fixed in time and other improvements are being made, benefitting the Twitch GUI. There are some issues though. I've mentioned these in the linked thread above (or here: https://github.com/chrippa/livestreamer/issues/1427#issuecomment-239005734).

**Right now, there is a call for additional people with python knowledge** who are willing to help with the fork and some additional unresolved issues. Let them know, if you think you can help. Thanks!

Other related issues here:
#250 
#256 
#283

**Comment by InfernoZeus** [comment]
@bastimeyer Thanks for flagging this, hadn't realised that Livestreamer is so uncared for. I've got some amount of experience with Python, and I might be able to help them with some of the more practical matters (setting up automated build/testing, website, etc.).

**Comment by lawli3t** [comment]
I have some knowledge of python, less so of the technologies involved but i might be willing to help fix some bugs here and there. Does the fork already have its own repository?

**Comment by bastimeyer** [comment]
I'm not sure. There are a couple of people who have already pushed fixes and stuff to their own forks, but AFAIK there is no official one yet. Just click on the linked thread. You should ask them, I'm just helping finding more people here.

**Comment by cdrage** [comment]
@bastimeyer @lawli3t @InfernoZeus i'm interesting in devoting some time to this. i have some knowledge of python, and maintenance, however, I'd only be able to devote a few hours a week to this, *just* enough to maintain it.

anyone want to come up with a decent name / alternative to "livestreamer"?

**Comment by lawli3t** [comment]
yes,  a central authority would definitely be nice - i dont think
self-organizing with complete strangers is sensible (albeit possible).

off the top of my head i only get some cheesy names
* pystreamer
* streamage

**Comment by cdrage** [comment]
imo, the project is big enough that we should create an organization repo for it, there's a large need for something like this.

streamage sounds like garbage :(

i like pystreamer, but pystream and pystreamer looks to be already used on pip

streamlink maybe? doesn't seem to be taken either

**Comment by cdrage** [comment]
Hey guys! @InfernoZeus @lawli3t 

I've created https://github.com/streamlink/streamlink and I've added a bunch of collaborators. 

Feel free to ping me if you'd like to be added to the collaborators list, otherwise, ping anyone from the "members" group as well.

**Comment by lawli3t** [comment]
sure add me, i might even find some time this week @cdrage

**Comment by bastimeyer** [comment]
@cdrage @lawli3t 

> streamlink maybe? doesn't seem to be taken either

I forgot to mention this here and in the other thread yesterday and I regret not doing this immediately, but I'm not sure if it's a good idea keeping that name. There's already a company called **StreamLink Software**.
I was too lazy checking this name for myself, because the repo was already created when I came back to my computer yesterday and I thought everything was fine. I didn't even see your post here asking for a decent name.
The name itself is ok and fitting, but there could definitely be some (legal) issues with it in the future. Can github orgas be renamed or is this restricted to repos?
Don't ask me to come up with an alternative, I'm the worst person on this planet you could ask for naming stuff, so please don't. 😞

**Comment by KaiSforza** [comment]
Why not just wrap it around youtube-dl instead? That seems to be actively developed.

**Comment by bastimeyer** [comment]
@KaiSforza 
yt-dl works a bit differently... See streamlink/streamlink#7 for a discussion about that.

Streamlink seems to be on a good way and will be added here in addition to livestreamer once the remaining issues have been resolved. I will make sure that both livestreamer and streamlink can be used, as long as both keep working (the same way). Once livestreamer breaks, it will be removed.

I'm not sure about a re-brand of the application yet. I guess I will wait a bit first and then see what the best solution will be. Since there are multiple people working on streamlink, the possibility of it becoming another unmaintained software is relatively low. Maybe a transition of this repo here to the streamlink orga could also make sense, but as I've said, I going to wait a bit first before doing such a transition.

**Comment by cdrage** [comment]
@bastimeyer if you want to transition this to the streamlink org i'd be +1 +1 for it.

**Comment by TheSneakySniper** [comment]
There shouldn't be any legal problems, because nobody is making any money off of this. http://www.streamlinksoftware.com/
but if you want to be safe, you should probably change the name now, to something along the lines of...
vidalive?
I am horrible with names. sorry.

**Comment by bastimeyer** [comment]
This can be closed now.
I have opened a new issue for the repo transition: #331
