### ISSUE TITLE
Adding cask to Homebrew 

### ISSUE THREAD

**Issue by NGMarmaduke** [bastimeyer/livestreamer-twitch-gui#291]
### Description
Hey there, thanks for the App - really stops by Mac's fans from taking off.

Noticed you have packages under Chocolatey and AUR but nothing with Homebrew. I've made a PR to add the latest version to `brew cask` here: https://github.com/caskroom/homebrew-cask/pull/23722

I can update the package grunt task to also generate new a formula.rb if you'd like, anyway great job 💯.

**Comment by bastimeyer** [comment]
Awesome, thanks!
I have been asked a couple of times in the past months to add a brew package/cask, but I didn't have the time to do this.

> I can update the package grunt task to also generate new a formula.rb if you'd like

Sure, go ahead.
Could you please split the `package` task into a [multi task](http://gruntjs.com/creating-tasks#multi-tasks) with a simple switch statement for the task target? The choco package maintainer has created a single task for this already:
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.14.2/build/tasks/custom/package.js#L6-L17

If you want you can also add the homebrew cask to the readme and wiki.

Thanks!!! :+1:

**Comment by NGMarmaduke** [comment]
For now I'll update the formula manually, as it requires a sha to be generate for both the download and the atom feed: https://github.com/bastimeyer/livestreamer-twitch-gui/releases.atom. 

This is difficult to do pre publishing to Github, as Homebrew is looking for the package from Github.

I've subscribed to the release feed so I know when to push new versions to Homebrew. I'm gonna close this issue.

**Comment by bastimeyer** [comment]
See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/294#issuecomment-239640899

**Comment by NGMarmaduke** [comment]
Excellent, let me know when you've add the hashing function

**Comment by bastimeyer** [comment]
@NGMarmaduke 
https://github.com/bastimeyer/livestreamer-twitch-gui/issues/294#issuecomment-240102509

Does the content of https://github.com/bastimeyer/livestreamer-twitch-gui/releases.atom also need to get hashed? I haven't implemented this yet. Please tell me if it does.

**Comment by NGMarmaduke** [comment]
@bastimeyer: It does indeed, currently not used but it will be when Homebrew cask supports updating

**Comment by bastimeyer** [comment]
0a942a0

Setting the `checksumAtom` option to true will save the hash of the current atom feed content to the `package.checksumAtom` grunt config property. Uses sha256 as well.

All requirements for your package config are now there. If you want, you can add your task config similar to the chocolatey one and send a PR. Thanks!

**Comment by bastimeyer** [comment]
I'm not sure if you're still interested, but the changes for creating an automated brew-cask script have been added a while ago. Here's the config of the choco package:
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.15.2/build/tasks/configs/package.js
The `checksumAtom` property can be set to true and its processed value can then accessed in the templates, similar to how the choco package is doing it with the `changelog` string and `checksums` object. If you don't have time for doing this, just tell me what exactly is needed and I'll build the script for you. Just let me know!

**Comment by bastimeyer** [comment]
> cask-repair

Ah okay, I didn't know that...

> I'm subscribed to updates version updates and then running cask repair:

Wouldn't it make sense adding this to the `after_deploy` hook of travis-ci, so the PR on the homebrew-cask repo can be opened automatically when a new release gets published?
In addition to the [tiny-scripts brew tap](https://github.com/vitorgalvao/homebrew-tiny-scripts), `cask-repair` is also available as a bash script:
https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair
