### ISSUE TITLE
1080p60 not recognised as the best (or source) qeality 

### ISSUE THREAD

**Issue by Deluxo** [bastimeyer/livestreamer-twitch-gui#293]
### Description

Livestreamer doesn't recognise 1080p60 as the best (or source) quality, when quality array is: [1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio].

The issue can be observed by watching dota2ti stream: [link](https://twitch.tv/dota2ti).

### Expected / Actual behavior

```
livestreamer https://twitch.tv/dota2ti best
[cli][info] Found matching plugin twitch for URL https://twitch.tv/dota2ti
error: The specified stream(s) 'best' could not be found.
Available streams: 1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio
```
```
livestreamer https://twitch.tv/dota2ti 1080p60 --player mpv
[cli][info] Found matching plugin twitch for URL https://twitch.tv/dota2ti
[cli][info] Available streams: 1080p60, 144p30, 240p30, 360p30, 480p30, 540p30, 720p30, 720p60, audio
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: mpv
```

### Environment details (operating system, etc.)

Linux 4.7.0-1-ARCH Mon Aug 8 22:05:58 2016 x86_64 GNU/Linux-

**Comment by bastimeyer** [comment]
Wrong repo and also a duplicate chrippa/livestreamer#1433
The issue got fixed here a couple of days ago #283
