### ISSUE TITLE
Error during the compilation

### ISSUE THREAD

**Issue by VirtualPorygon** [bastimeyer/livestreamer-twitch-gui#299]
Hi,

I recently tried to compile the project but I got an error. I'm on Ubuntu 16.04 64bits. The error happens when I run the last command `grunt release`. The two npm commands don't give me any error (just a few warning about old versions of some programs IIRC). So here is the error:

```
ERROR in ./src/web_modules/metadata.js
Module build failed: TypeError: Promise.defer is not a function
  at denodified (~/livestreamer-twitch-gui/src/app/utils/node/denodify.js:18:23)
  at Object.module.exports (~/livestreamer-twitch-gui/src/web_loaders/metadata-loader.js:23:25)
 @ ./src/app/controllers/AboutController.js 1:0-30:2
Warning: Task "webpack:prod" failed. Use --force to continue.

Aborted due to warnings.
```

I tried to use `grunt release --force` as suggested but at the end I can't run the program.

**Comment by bastimeyer** [comment]
Which node.js version are you running?
The LTS version (v4.x.x) should already support the es6 Promise spec...

**Comment by VirtualPorygon** [comment]
Wow that was a fast answer.

```
nodejs --version
v4.2.6
```

**Comment by bastimeyer** [comment]
> v4.2.6

`4.5.0` is the minimum requirement (https://nodejs.org/en/blog/release/v4.0.0)

You should install Node.js on Ubuntu via their own repo:
https://nodejs.org/en/download/package-manager/

I could add fallback libs for the missing stuff on older node versions. I'm not sure though...

**Comment by VirtualPorygon** [comment]
Ok so that's the problem. Thanks for the answer. I will see what I can do to upgrade it.

**Comment by bastimeyer** [comment]
b5941c5418894b302f734274c7f3d5e92460a15b
