### ISSUE TITLE
Could not connect to streams! PLease Help!

### ISSUE THREAD

**Issue by Meaddu** [bastimeyer/livestreamer-twitch-gui#300]
Whenever i try to connect to any twitch streams it says connection timed out! I am a noob please help!

**Comment by bastimeyer** [comment]
I can't help you without any useful informations. Even if you consider yourself a *noob*, you should provide at least some kind of info.

What kind of timeout are you talking about? Do you get a timeout error during the livestreamer validation when trying to launch a stream or are you talking about a timeout while viewing the stream in your video player?

Does it work when using the Livestreamer CLI? Anything "Livestreamer Twitch GUI" unrelated doesn't belong here. Also, this is an issue tracker, personal issues don't belong here either.

**Comment by skodem123** [comment]
I am having the same problem. Funny thing is that it was working well a couple of hours ago so i dont know what happened. As soon as i click on a stream, the window pops up but after a couple of seconds i get the timed out message. I can provide a screenshot if thats gonna be any help.

**Comment by bastimeyer** [comment]
Closing this. See #301
