### ISSUE TITLE
Show both nickname & username

### ISSUE THREAD

**Issue by i-cant-git** [bastimeyer/livestreamer-twitch-gui#303]
His username is 1983kej but his nickname is Korean so we only see his nickname below

![2016-09-07_05-31-41](https://cloud.githubusercontent.com/assets/16619091/18297825/6c4aac2e-74bc-11e6-8477-9306e36cda6b.png)

Twitch now allows nicknames in Korean / Japanese / Chinese so we can't see their real usernames.

Please add an option to see their usernames too like this:

![likethis](https://cloud.githubusercontent.com/assets/16619091/18297904/1e6efab8-74bd-11e6-9eed-2b34d7c43aba.png)

**Comment by bastimeyer** [comment]
The default channel name can now be seen if a custom display_name was set by the channel, similar to your example. On the channel page, it's being listed under the stats on the right, though.
If I have missed something or if this causes issues with text lengths, etc, please let me know.
Thanks for reporting... 👍

**Comment by i-cant-git** [comment]
So how can I see both username and nickname at the same time?

**Comment by bastimeyer** [comment]
> I need to update

I'm not going to release a new version soon, though. If this issue is super annoying for you, you can compile the application by yourself. Instructions can be found here:
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building
