### ISSUE TITLE
Cannot start livestreamer-twitch-gui - Web sqlite error 5, errno 0: database is locked

### ISSUE THREAD

**Issue by xaxxon** [bastimeyer/livestreamer-twitch-gui#304]
Latest OS X - one patch back

latest livestreamer gui.

It worked when I downloaded it a few hours ago, came back to run it again but when I click on it in the dock, nothing happens.   No bounce, no nothing.

So I ran it from the terminal and get:

zacs-MacBook-Pro:v8toolkit xaxxon$ /Applications/Livestreamer\ Twitch\ GUI.app/Contents/MacOS/nwjs 
[57755:0910/023504:ERROR:connection.cc(1060)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA journal_mode = PERSIST
[57755:0910/023505:ERROR:connection.cc(1060)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA cache_size=32
[57755:0910/023505:ERROR:connection.cc(1060)] Web sqlite error 5, errno 0: database is locked, sql: CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR)
[57755:0910/023505:ERROR:web_data_service_backend.cc(54)] Cannot initialize the web database: 1

**Comment by bastimeyer** [comment]
I'm not exactly sure what you've done, but it seems that either the old process is still running and preventing access to the sqlite database of Chromium for the new one (although NWjs doesn't allow running multiple processes of the same application at once) or the data has somehow been corrupted. If this is the case, you should try deleting the config folder located in `$HOME/Library/Application Support/livestreamer-twitch-gui/`.

**Comment by xaxxon** [comment]
You were right -- there was a copy running, but it didn't show up on
cmd-tab or force kill.

But I did a `ps` and found it, did a killall nwjs and tried again and it
worked.

Thank you.

--Zac

**Comment by bastimeyer** [comment]
Ok... closing this.
If it happens again, reopen the issue. I'd like to know how to reproduce this and why the first process didn't terminate correctly.

**Comment by xaxxon** [comment]
I think the problem was that I don't understand what the "OS integration" options mean.   

Apparently you can make it so it doesn't show up in the dock or even in the cmd-tab list -- but I just noticed there's a little icon in the top near the time that I probably just didn't see before.

But I've never used an app on OS X that while there's a window open it doesn't show up in cmd-tab (and probably in the dock as well).   This is probably a mis-feature to allow.

**Comment by xaxxon** [comment]
Of course the fact that they are named "taskbar" and "tray" isn't a great description on os x.

Setting it to "taskbar" gives normal functionality.
