### ISSUE TITLE
Browse Featured returns 503 Service Unavailable

### ISSUE THREAD

**Issue by DOFandersolsen** [bastimeyer/livestreamer-twitch-gui#306]
### Description
Hi there, for a couple of days now, the Featured-page has been unavailable, maybe it's because of an API change?

### Expected / Actual behavior

**Expected**: To see a list of the featured streams with their titles and thumbnails.

**Actual:**
![twitch](https://cloud.githubusercontent.com/assets/16536056/18447003/0148733a-7925-11e6-9ddc-42e9c2e6404d.PNG)

### Reproduction steps

1. Open Livestreamer Twitch GUI
2. Click on Featured under Browse

### Environment details (operating system, etc.)
![twitch](https://cloud.githubusercontent.com/assets/16536056/18447108/7ebfc142-7925-11e6-931e-67e14f143bc6.PNG)

![twitch](https://cloud.githubusercontent.com/assets/16536056/18447070/50dc2a2c-7925-11e6-9057-0501d1d7a53e.PNG)

![twitch](https://cloud.githubusercontent.com/assets/16536056/18447087/5f2f8600-7925-11e6-9489-c031654cc4cb.PNG)

**Comment by bastimeyer** [comment]
> maybe it's because of an API change?

I doubt it as this is part of the public API. The "Service unavailable" error (no. 5xx) indicates that something else went wrong on their end.
I'm having issues as well these days, but not all of the time. Every so often the followed streams list is empty, so I think they're simply having some server/database issues. There's nothing I can do about.

**Comment by MrLint** [comment]
I don't know if its coincidence, but this and other issues with LS seemed to coincide with the big twitch DDOS that went on a few days back
