### ISSUE TITLE
Option to NOT authenticate when launching a stream.

### ISSUE THREAD

**Issue by gyvess** [bastimeyer/livestreamer-twitch-gui#308]
While logged in, every launched stream will print:

```
Attempting to authenticate using OAuth token
Successfully logged in as %username%
```

As far as I can tell, being logged in is only useful for subscriber checks which allow additional video qualities if restricted by the caster.  However, the authentication happens regardless of what stream you choose to watch.  More importantly, authenticating delays stream launch compared to not being logged in.

I tried blocking the token by putting a blank value for the `--twitch-oauth-token` option in the config file, but it's baked into livestreamer-twitch-gui.

I'm requesting a way to avoid the delay brought on my authentication.  Some suggestions option to disable authentication when launching streams or only authenticate when launching from the subscription tab.

**Comment by bastimeyer** [comment]
The `--twitch-oauth-token` parameter can now be disabled in the settings->livestreamer menu.

**Comment by gyvess** [comment]
Awesome.  Thanks for the great program and speedy turnaround on this issue!  Keep up the good work.

**Comment by bastimeyer** [comment]
> speedy turnaround on this issue

Maybe a little bit too fast. Or worst point in time asking for this feature: #310 
I will need to revert this change.

**Comment by bastimeyer** [comment]
Re-reverted... :sweat_smile:
See df63541fc508f1aeee27987ecaf326a474a59a22
