### ISSUE TITLE
Followed Games

### ISSUE THREAD

**Issue by PeterJonson** [bastimeyer/livestreamer-twitch-gui#31]
For the next update, is it possible to add the Followed Game feature on the menu so we can check streams for specific games directly from the menu instead of searching for it?

**Comment by fletom** [comment]
+1 for this

**Comment by Robby-** [comment]
:+1: from me too. Right now I have to either use the Twitch app on my phone, or login to the Twitch website to follow a game.

**Comment by fletom** [comment]
Yeah, I think this issue should be closed now.

**Comment by Robby-** [comment]
I would agree if the `followed games` feature would be *fully* implemented, which right now isn't the case.

**Comment by bastimeyer** [comment]
> I would agree if the followed games feature would be fully implemented, which right now isn't the case.

Yes, that's why I left this thread open.

> We still need a follow/unfollow button.

This hasn't been implemented yet, because the way Twitch has built this feature into their API is **terribly inconsistent** (/rant). I need to write a special data adapter first - just for the game following mechanic.
