### ISSUE TITLE
Lists in "Top Games" and "Top Channels" out of order/disappeared

### ISSUE THREAD

**Issue by imurpops984** [bastimeyer/livestreamer-twitch-gui#311]
### Description
With the new update v0.15.0 everything is fine upon initially opening the GUI but if I click on _Top Games_ and _Top Channels_ more than once, some of the streams outright disappear or reorder strangely.  A similar thing happens when clicking on all of the choices under the _My_ section but they seem to fix themselves if you pick the same choice again.  Closing and reopening the GUI seems to reset the issue but doesn't fix it. 

### Reproduction steps

1. Open GUI
2. Click on _Top Games/Top Channels_
3. Click same option from step 2 again
4. Close GUI
5. Reopen to find back to normal
6. Repeat

### Environment details (operating system, etc.)

Windows 10 Pro x64

### Comments, logs, screenshots, etc.

http://imgur.com/a/pj6Kt
Album with screenshots (probably not necessary but why not)

I checked around to see if this was reported but it's possible that I missed it so sorry if this is a repost.  Thanks

**Comment by bastimeyer** [comment]
Twitch is having issues the last couple of days. This has nothing to do with the GUI or any of the recent releases. It's just different data that's being returned by the API. The Twitch website should have the same issues. #306 #307

**Comment by imurpops984** [comment]
Gotcha, I did see 307 but wasn't sure if they were related.  I'll be sure to check Twitch first next time and thanks for getting back so fast.
