### ISSUE TITLE
Tray icon is invisible after upgrading to 0.15.0

### ISSUE THREAD

**Issue by k3lt** [bastimeyer/livestreamer-twitch-gui#312]
After upgrading to the latest version, which is 0.15.0 Livestreamer GUI tray icon is invisible.
I can still click it and it's interractable.
Windows 10 x64. (Anniversary update)

![bez tytulu](https://cloud.githubusercontent.com/assets/22222328/18559500/c6d20bda-7b77-11e6-8fb9-eefe6355f103.png)

**Comment by i-cant-git** [comment]
I can confirm

**Comment by bastimeyer** [comment]
Fixed in [v0.15.1](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.15.1).
Thanks for reporting...
