### ISSUE TITLE
GUI streams completely random? Doesn't show all my followed livestreams and top games are not top games

### ISSUE THREAD

**Issue by zawnk** [bastimeyer/livestreamer-twitch-gui#316]
Since I've updated to 0.15.x I've noticed that the GUI shows random stuff as top games, even though the website shows the 'normal' top games as top games. Random games with low viewer numbers are shown as the #1 game currently (see screen). Also, currently 4 of my followed streamers are online, but the 'My Live Streams' only shows one, for whatever reason. If I click another menu, and 'My Live Streams' again, I see 3. And it keeps alternating. I don't know if livestreamer twitch gui receives wrong data from the API or if it's the program itself.

...

### Expected / Actual behavior
Actually represent the data like it's on the Twitch website.
...

### Environment details (operating system, etc.)
Win 10 x64
0.15.1 livestreamer twitch gui
...

Screen as an example: http://i.imgur.com/IcyNONs.jpg

**Comment by bastimeyer** [comment]
https://github.com/bastimeyer/livestreamer-twitch-gui/releases/latest

**Comment by zawnk** [comment]
Well, that was fast. Sorry for not seeing the update. Didn't have a notification about it yet in the client. Thanks :)
