### ISSUE TITLE
Slow stream load using MPC-HC

### ISSUE THREAD

**Issue by sollunaastro** [bastimeyer/livestreamer-twitch-gui#317]
I'm getting a very slow startup when using MPC-HC as the default media player. After clicking the stream the MPC window opens but doesn't load the video until 30-40s later, and it's delayed (compared to a stream opened in a browser/command-line-livestreamer) by that much time.

I'm not getting that problem if I use VLC as the default player

I'm using Windows 10 and MPC-HC x86

In advance, thanks

**Comment by bastimeyer** [comment]
> compared to a stream opened in command-line-livestreamer

Which parameters were you using? Have you set any custom parameters in your [`livestreamerc`](http://docs.livestreamer.io/cli.html#configuration-file) config file?

> I'm not getting that problem if I use VLC as the default player

How can this be an issue with Livestreamer Twitch GUI then? It just assembles a list of livestreamer parameters executes it. It doesn't know about strengths or weaknesses of the selected player (well, not yet: #257).

Please check your caching/buffer configuration in MPC-HC. You could also try choosing a different stream type ([`--player-passthrough`](https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Livestreamer-configuration#stream-type)) in the GUI's livestreamer-settings (requires advanced settings to be enabled). Other than that, I don't know what could possibly be the reason for this.

**Comment by sollunaastro** [comment]
In command line, I only use the authentication parameter and the stream ID, so it usually looks like `livestreamer --twitch-oauth-token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx twitch.tv/<streamID> best`
The only modification in my [livestreamerrc](http://docs.livestreamer.io/cli.html#configuration-file) config file is regarding the default player
MPC-HC buffer is at 256MB, which seems plenty

I deduced it was a GUI issue because the problem is not at command line, am I wrong in thinking that?

**Comment by bastimeyer** [comment]
> You could also try choosing a different stream type (--player-passthrough) in the GUI's livestreamer-settings

Have you done that?
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Livestreamer-configuration#stream-type

That's basically the only difference between using the CLI and the GUI. The GUI enforces the `--player-passthrough` parameter, because there are a couple of players (on Windows) that don't support reading from `stdin`.

**Comment by hvoIIITA** [comment]
Switch to HLS stream type. I've noticed it starts faster
