### ISSUE TITLE
[Feature Request/Question] Non-Twitch Chat (Destiny.gg)

### ISSUE THREAD

**Issue by WaerjakSC** [bastimeyer/livestreamer-twitch-gui#318]
Hey, I absolutely love your program. 
I have a really niche request/question. I watch a streamer called Destiny quite frequently, and I was wondering if it was possible to configure Livestreamer GUI to open the Destiny.gg chat that he uses instead of the default twitch chat? Probably wouldn't be anywhere near the top of your priorities, I just thought I'd ask. 

Thanks!

**Comment by bastimeyer** [comment]
> the Destiny.gg chat that he uses instead of the default twitch chat

Is it this chat URL here?
https://www.destiny.gg/embed/chat

Livestreamer Twitch GUI does support custom chat applications. You need to build a script that opens the special URL in your browser if you're opening the chat of this streamer and the default twitch chat URL for everyone else. Then simply use that script as chat application with the channel name as parameter.

I don't know which OS you're using, but this is how it looks like in bash on Linux/OSX. Please don't ask me about Windows shell scripting.

**Custom chat application:**
`/path/to/destiny_chat.sh "{channel}"`

**destiny_chat.sh:**
```bash
#!/bin/bash

chrome="$(which google-chrome)"

if [[ "${1}" = "destiny" ]]; then
  url="https://www.destiny.gg/embed/chat"
else
  url="https://www.twitch.tv/${1}/chat"
fi

# open chromium/chrome with the special --app=URL parameter
exec "${chrome}" "--app=${url}" &
```

**Comment by WaerjakSC** [comment]
Thanks for the swift response. Yes, that's the chat URL. I'm on Windows 10, and unfortunately I'm a complete noob about scripts. Is there any way to run that script as-is on Windows somehow, or am I being stupid?

**Comment by bastimeyer** [comment]
**Custom chat application:**
`cscript "DRIVE_LETTER:\path\to\destiny_chat.vbs" "{channel}"`

**destiny_chat.vbs:**
```vbs
chrome = "DRIVE_LETTER:\path\to\chrome.exe"
channel = WScript.Arguments.Item(0)

If channel="destiny" Then
	url = "https://www.destiny.gg/embed/chat"
Else
	url = "https://www.twitch.tv/" & channel & "/chat"
End If

' open chromium/chrome with the special --app=URL parameter
Set objShell = CreateObject("WScript.Shell")
objShell.exec(Chr(34) & chrome & Chr(34) & " " & Chr(34) & "--app=" & url & Chr(34))
Set objShell = Nothing
```

**Comment by WaerjakSC** [comment]
Thanks you so much!
