### ISSUE TITLE
Error in building from the source code

### ISSUE THREAD

**Issue by rycastaneda** [bastimeyer/livestreamer-twitch-gui#321]
----

### Description
ERROR in ./src/web_modules/metadata.js
Module build failed: Error: null
  at ChildProcess.onExit (/home/ryan/Downloads/livestreamer-twitch-gui-0.15.2/src/web_loaders/metadata-loader.js:52:14)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

 @ ./src/app/controllers/AboutController.js 11:16-35

...

### Expected / Actual behavior
Should build
...

### Reproduction steps

1. Download the source and build
2. Follow the build steps in the readme

### Environment details (operating system, etc.)
KUbuntu 16
...

### Comments, logs, screenshots, etc.
![image](https://cloud.githubusercontent.com/assets/4694510/18939654/5c0097d2-8634-11e6-8c9a-0b49bc5defdf.png)

...

**Comment by bastimeyer** [comment]
> Download the source

You need to clone the git repo and not just download the archive of the head of the master branch that github provides. The metadata webpack-loader builds an array of all git contributors. See here
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.15.2/src/web_loaders/metadata-loader.js#L42
