### ISSUE TITLE
Static image distortion within the app on Mac

### ISSUE THREAD

**Issue by Vitosi4ek** [bastimeyer/livestreamer-twitch-gui#326]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Description

The app emits static image distortion in the top half of the window when moving the mouse. Notably can't be captured by any screengrabbing software (the recording just captures the app window without any irregularities). Also happens within the native Twitch.com's video player, so I'm not sure it's on the app and not on the OS, but reporting nontheless.

### Reproduction steps

1. Launch the app

2. Move the mouse around a little bit within the app window.

### Environment details (operating system, etc.)

OS: macOS 10.12 Sierra (the latest release). App: the latest version.

### Comments, logs, screenshots, etc.

Would love to grab a screenshot or a recording, but, as mentioned, the distortion could not be captured in any way.

**Comment by bastimeyer** [comment]
This doesn't sound like a Livestreamer Twitch GUI related issue and even if it was, it would rather be related to NWjs/Chromium (the platform that's being used), and you should report this over there. For me, this sounds like a problem with your system and its graphics drivers.

> Also happens within the native Twitch.com's video player

What *native* video player of Twitch.tv are you talking about? The html5/flash web player on their website? So you're having the same graphical glitches in your web browser (which is probably based on Chromium)? If so, maybe `chrome://gpu` is able to tell you more, but despite that, I can't do anything for you here.
