### ISSUE TITLE
Linux/Ubuntu - installation as application?

### ISSUE THREAD

**Issue by xingped** [bastimeyer/livestreamer-twitch-gui#327]
Is it or would it be possible to install this gui as an installable application in the system? I.e. show up in the Applications list in the Start Menu?

I'm on Linux Mint.

**Comment by bastimeyer** [comment]
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Installation#custom-installation

You need to run `add-menuitems.sh` from the archive once. This will create a launcher in the menu.

Packages for Debian/Ubuntu/Mint etc. are not available yet, but are being worked on.
Progress can be seen here: #319

**Comment by xingped** [comment]
Awesome, thank you so much! Sorry I missed that in the wiki!
