### ISSUE TITLE
Streams which default to "720p60 - Source" do not work

### ISSUE THREAD

**Issue by neffers** [bastimeyer/livestreamer-twitch-gui#329]
### Description

GUI fails when attempting to open a live stream for which the highest available quality is 720p60 - Source

### Expected / Actual behavior

Should initialize stream

### Reproduction steps

1. attempt to watch twitch.tv/dreamleague
2. gui fails

### Environment details

linux x64

### Comments

leaving the 'stream info box' open on all failures would help to diagnose further for the end-user

**Comment by stevek123** [comment]
see #323

**Comment by neffers** [comment]
ah, okay, I'll close this then
