### ISSUE TITLE
Set chat window size and position

### ISSUE THREAD

**Issue by NatPagles** [bastimeyer/livestreamer-twitch-gui#330]
Im currently using google chrome and was wondering if there is a way to set window size and position for the chat that pops up?

**Comment by bastimeyer** [comment]
You need to use the custom chat method in the settings menu and then write a wrapper script for achieving something like this. This is all very specific to your OS and env, though. Something similar to https://github.com/bastimeyer/livestreamer-twitch-gui/issues/318#issuecomment-249401942
