### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by efe116** [bastimeyer/livestreamer-twitch-gui#333]
### Description

Hello!
I recently installed Windows 10 and re-installed Livestreamer gui, but now whenever I try to watch something through it I get this error. Nothing more specific, just this. Tried changing the vlc path but it didn't help.

### Environment details (operating system, etc.)

Windows 10 Pro
VLC 2.2.4
Livestreamer GUI 0.16.0

### Comments, logs, screenshots, etc.

![2ox7tyb 1](https://cloud.githubusercontent.com/assets/11664459/19449766/39d09578-94a7-11e6-8bc4-53c8e9e45397.png)

Hope you can help me, love this software and would love to be able to use it again.
Thank you and regards,

**Comment by bastimeyer** [comment]
Check your livestreamer installation. A timeout usually means that something went wrong during the validation. If it doesn't work from the CLI, it also won't work in the GUI, so make sure that livestreamer itself is working correctly.

**Comment by efe116** [comment]
Hello again,
Totally forgot that you actually need Livestreamer as well. Downloaded it and changed the pathing and it worked like a charm.
Thank you!
