### ISSUE TITLE
Watching Past Broadcasts

### ISSUE THREAD

**Issue by BogheanGratian** [bastimeyer/livestreamer-twitch-gui#334]
A few months ago I could watch any past broadcast from twitch using this code:
livestreamer --player-passthrough=hls *insert twitch url* source
But now whenever I do this I get this error message:
error: Unable to open URL: https://api.twitch.tv/api/vods/89374805/access_token.json (400 Client Error: Bad Request)
Any one has this problem? I would like some help because I cannot go to twitch.tv, for some reason my pc just freezes and I have to manually turn it off if I stay on twitch for a long period of time.

**Comment by bastimeyer** [comment]
Wrong repo, this is **not** Livestreamer, this is **Livestreamer Twitch GUI**... You should use the search function before opening new threads: chrippa/livestreamer#1456

Btw, Livestreamer is dead. See Streamlink: https://github.com/streamlink/streamlink

**Comment by BogheanGratian** [comment]
Oh, I'm sorry. Thanks for the info.
