### ISSUE TITLE
Audio Hiccup with VLC

### ISSUE THREAD

**Issue by qoralswp** [bastimeyer/livestreamer-twitch-gui#337]
There is an audio hiccup occurring randomly. The audio stops and skips for around half a second to a second and resumes. Other media players seem to be fine. It happens fairly frequently and it's getting ridiculously annoying.

I have tried downloading and reinstalling VLC, livestreamer and it doesn't seem to be helping.

**Comment by bastimeyer** [comment]
Does this happen while using livestreamer/streamlink via the shell (without the Twitch GUI)?
I don't know why the GUI would be responsible for messed up video/audio rendering, unless it is setting some weird livestreamer/streamlink parameters which could cause this behavior.

The only thing I can tell you is to try livestreamer/streamlink on their own and then fix your issues from there. This doesn't sound like a GUI related issue.

**Comment by qoralswp** [comment]
Thank you for the fast reply! I'll try!
