### ISSUE TITLE
Custom Chat Application Channel Name Escaping

### ISSUE THREAD

**Issue by memco** [bastimeyer/livestreamer-twitch-gui#338]
### Description

When using the "Custom application" and "open irc://irc.twitch.tv/#{channel}" to open chat links, the client is receiving every letter of the channel name escaped with "/" which results in broken links for my particular irc client (Textual on mac).

It would be nice to have some way to indicate whether the various variables should be escaped or not as it seems the escaping is actually not needed in some cases.

**Comment by memco** [comment]
Seems this is implemented and undocumented. Missed it because the previous issues for this had been closed. I created a wiki page for the chat options to hopefully prevent further issues: https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Chat-configuration

**Comment by bastimeyer** [comment]
Thanks... The wiki is a bit out of date. I'll see if I can add some more missing stuff once I've completed the transition over to streamlink.

Variables will always be escaped. There is no reason to confuse the user with unexpected mechanisms like a dynamic detection of potentially breaking substitutions. There's a `?` "button" above the list of vars (also in the player settings menu) which has a tooltip that explains how variable substituion works.

**Comment by memco** [comment]
Hmm. I have looked at the tool tips and not seen that before. Will look again.
