### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by mikeparadinas** [bastimeyer/livestreamer-twitch-gui#339]
when I start the application, nothing happens and it doesnt appear in task manager
v16, used to work fine
-admin mode
-restarted pc
-reinstalled everything livestreamer related
-installed streamlink
-downgraded t 15.x

**Comment by bastimeyer** [comment]
I'm guessing you're using Windows (you ignored the issue template and did not provide any useful environment informations)...

Can you please launch the application from the windows cmd shell and then see for any log output? There's either something wrong with your application config/cache or something else on your system is preventing you to launch it.

You could try deleting your config folder in `%LOCALAPPDATA%\livestreamer-twitch-gui`, but I'd like to see an error log first, in case there's a bug that needs to be fixed.

**Comment by bastimeyer** [comment]
Any response?
