### ISSUE TITLE
Infobar always visible setting not applying when sorting by games

### ISSUE THREAD

**Issue by Dkzn** [bastimeyer/livestreamer-twitch-gui#342]
Settings > Lists > Info bar is always visible 

It works everywhere else like search results, top channels, etc.

Running Windows 10 64 bit.

Setting is enabled in both pics here:
![infobar1](https://cloud.githubusercontent.com/assets/7800161/20323454/cd44d206-ab4a-11e6-832d-42a0e79fcfea.png)

![infobar2](https://cloud.githubusercontent.com/assets/7800161/20323472/dee35b18-ab4a-11e6-89fd-2c6a9bdbd66b.png)

**Comment by bastimeyer** [comment]
Thanks for reporting!
