### ISSUE TITLE
Error: Couldn't launch the stream

### ISSUE THREAD

**Issue by Lachstah** [bastimeyer/livestreamer-twitch-gui#39]
Whenever I attempt to open a stream it comes up with "Error: Couldn't launch the stream" followed by this:

"usage: livestreamer.exe [OPTIONS] [URL] [STREAM] livestreamer.exe: error: unrecognized arguments: ----default-stream=source"

Before I couldn't even launch a stream and once I reinstalled both livestreamer and twitch gui this error message starts coming up, is there anything I could fix in a config file?

**Comment by bastimeyer** [comment]
Hi!
The `--default-stream` livestreamer parameter [is not used by the application](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.0/src/app/controllers/LivestreamerController.js#L66), so the issue must be in your livestreamer config or maybe you're using an alias for the livestreamer executable. See here: http://livestreamer.tanuki.se/en/latest/cli.html#cmdoption--default-stream

**Comment by Lachstah** [comment]
Sorry, I don't really know what half of this means. Does that mean I should delete something from the config file and how do I tell if I'm using an alias? Thanks.

**Comment by bastimeyer** [comment]
:+1:
