### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by isamu99** [bastimeyer/livestreamer-twitch-gui#41]
Not sure if there is a normal comments section or messageboard for this app but I just wanted to give a very sincere thank you to Sebastian for giving us a new updated version of Livestreamer-twitch-GUI. This version is so much better it's ridiculous. Can't tell you how happy I am with this version. Thanks so much Sebastian, you rock dude! :)

**Comment by bastimeyer** [comment]
![BibleThump](https://cloud.githubusercontent.com/assets/467294/5990381/6fd4a1ae-a9ae-11e4-8531-e6610bc14ca5.png)
Thank you very much for the kind words!
