### ISSUE TITLE
No 'build/releases' folder

### ISSUE THREAD

**Issue by RAWRWAFL** [bastimeyer/livestreamer-twitch-gui#42]
I feel like I've done everything right, but I'm bad so I'm not sure. I'm running ubuntu and all the commands  to build seem to run smoothly, but at the end there is no 'build/releases' folder and I don't see any way to launch. Maybe I'm missing something obvious, idk.

**Comment by bastimeyer** [comment]
> all the commands to build seem to run smoothly

Did the `nodewebkit` grunt task succeed? This is the last part of the build process and it compiles the node-webkit application. If it did not, there must be something wrong with either your system/configuration or the `node-webkit-builder` package. This is how the output of the `grunt release` command should look like:

```
Running "release" task

Running "jshint:app" (jshint) task
>> 125 files lint free.

Running "jshint:test" (jshint) task
>> 4 files lint free.

Running "connect:test" (connect) task
Started connect web server on http://0.0.0.0:8000

Running "qunit:all" (qunit) task
Testing http://localhost:8000/test/tests.html .......OK
>> 27 assertions passed (31ms)

Running "clean:tmp" (clean) task
>> 54 paths cleaned.

Running "copy:build" (copy) task
Created 1 directories copied 41 files

Running "metadata:all" (metadata) task

Running "less:release" (less) task
File build/tmp/styles/app.css created

Running "requirejs:release" (requirejs) task

Running "uglify:release" (uglify) task
>> 1 file created.

Running "uglify:requirejs" (uglify) task
>> 1 file created.

Running "compile:linux64" (compile) task

Running "clean:release_linux64" (clean) task
>> 16 paths cleaned.

Running "nodewebkit:linux64" (nodewebkit) task
Using v0.11.6
Create cache folder in /home/basti/repos/livestreamer-twitch-gui/build/cache/0.11.6
Downloading: http://dl.nwjs.io/v0.11.6/node-webkit-v0.11.6-linux-x64.tar.gz


Create release folder in /home/basti/repos/livestreamer-twitch-gui/build/releases/livestreamer-twitch-gui/linux64
Zipping app/main.js
Zipping img/Twitch_Logo_Purple.png
Zipping img/icon-16.png
Zipping img/icon-256.png
Zipping img/icon-32.png
Zipping img/icon-48.png
Zipping index.html
Zipping oauth.html
Zipping oauth.json
Zipping package.json
Zipping styles/app.css
Zipping vendor/flag-icon-css/flags/4x3/br.svg
Zipping vendor/flag-icon-css/flags/4x3/cn.svg
Zipping vendor/flag-icon-css/flags/4x3/cz.svg
Zipping vendor/flag-icon-css/flags/4x3/de.svg
Zipping vendor/flag-icon-css/flags/4x3/dk.svg
Zipping vendor/flag-icon-css/flags/4x3/es.svg
Zipping vendor/flag-icon-css/flags/4x3/fi.svg
Zipping vendor/flag-icon-css/flags/4x3/fr.svg
Zipping vendor/flag-icon-css/flags/4x3/gb.svg
Zipping vendor/flag-icon-css/flags/4x3/gr.svg
Zipping vendor/flag-icon-css/flags/4x3/hu.svg
Zipping vendor/flag-icon-css/flags/4x3/it.svg
Zipping vendor/flag-icon-css/flags/4x3/jp.svg
Zipping vendor/flag-icon-css/flags/4x3/kr.svg
Zipping vendor/flag-icon-css/flags/4x3/mx.svg
Zipping vendor/flag-icon-css/flags/4x3/nl.svg
Zipping vendor/flag-icon-css/flags/4x3/no.svg
Zipping vendor/flag-icon-css/flags/4x3/pl.svg
Zipping vendor/flag-icon-css/flags/4x3/pt.svg
Zipping vendor/flag-icon-css/flags/4x3/ru.svg
Zipping vendor/flag-icon-css/flags/4x3/se.svg
Zipping vendor/flag-icon-css/flags/4x3/sk.svg
Zipping vendor/flag-icon-css/flags/4x3/tr.svg
Zipping vendor/flag-icon-css/flags/4x3/tw.svg
Zipping vendor/flag-icon-css/flags/4x3/us.svg
Zipping vendor/font-awesome/fonts/fontawesome-webfont.woff
Zipping vendor/requirejs/require.js
Zipping vendor/roboto-fontface/fonts/Roboto-Bold.woff2
Zipping vendor/roboto-fontface/fonts/Roboto-Light.woff2
Zipping vendor/roboto-fontface/fonts/Roboto-Medium.woff2
Zipping vendor/roboto-fontface/fonts/Roboto-Regular.woff2
Zipping vendor/roboto-fontface/fonts/Roboto-RegularItalic.woff2
>> nodewebkit app created.

Running "copy:linux64scripts" (copy) task
Copied 3 files

Running "copy:linux64icons" (copy) task
Copied 6 files

Done without errors.
```

**Comment by RAWRWAFL** [comment]
Mine stops short. Not sure why it would do this. 

Running "release" task

Running "jshint:app" (jshint) task
>> 125 files lint free.

Running "jshint:test" (jshint) task
>> 4 files lint free.

Running "connect:test" (connect) task
Started connect web server on http://0.0.0.0:8000

Running "qunit:all" (qunit) task
Testing http://localhost:8000/test/tests.html .......OK
>> 27 assertions passed (61ms)

Running "clean:tmp" (clean) task
>> 0 paths cleaned.

Running "copy:build" (copy) task
Created 1 directories, copied 41 files

Running "metadata:all" (metadata) task

Running "less:release" (less) task
File build/tmp/styles/app.css created

Running "requirejs:release" (requirejs) task

Running "uglify:release" (uglify) task
>> 1 file created.

Running "uglify:requirejs" (uglify) task
>> 1 file created.

Done, without errors.

**Comment by bastimeyer** [comment]
Hm, what you've posted is the result of the [buildrelease task](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/5a1179b4aa552f66a5b3c84e4afb824c7d2926bc/build/tasks/configs/aliases.yml#L17-L25), which is called by the [compile task](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/5a1179b4aa552f66a5b3c84e4afb824c7d2926bc/build/tasks/custom/release.js#L10-L15) here... Are you sure you're running the right command (`grunt compile`)? You can also manually compile the built project by running `grunt compile` after `grunt buildrelease`. See `grunt --help` for a full list of available tasks...
