### ISSUE TITLE
Can you add a option to watch other streams?

### ISSUE THREAD

**Issue by dragons4life** [bastimeyer/livestreamer-twitch-gui#43]
For example say i want to watch "MLG.tv" the link to the video or stream link input for livestreamer is
"hds://mlghds-lh.akamaihd.net/z/mlg459_1@129210/manifest.f4m", simply make a box like the parameters but for other streams or adding your own stream?

**Comment by bastimeyer** [comment]
I don't think this would be a good idea. This application is for browsing twitch.tv only. Adding another streaming platform or support for custom streams would make no sense...
What you're asking for can be done very easily by the livestreamer CLI alone, so a GUI is absolutely not needed...

**Comment by dragons4life** [comment]
ok, thank you.
