### ISSUE TITLE
Start Menu Shortcut

### ISSUE THREAD

**Issue by dojima** [bastimeyer/livestreamer-twitch-gui#44]
Firstly, just wanted to say that I love this application.  Don't think I could go back to using Twitch without it.  Had a few issues that were mostly resolved by deleting my old preferences folder, but one still remains.

It seems that livestreamer-twitch-gui checks to see whether or not I have a shortcut to it in the start menu on launch, and if it detects that I don't, it places one there.  Is there any way to stop this behavior?  I do already have a shortcut in my start menu for it, but I've renamed it slightly.

Thanks!

**Comment by bastimeyer** [comment]
Thanks!
The reason for creating a start menu shortcut at the startup of the application are the desktop notifications. There are two different kind of notifications on windows and one of them (the better one) requires a shortcut to the program which is invoking those desktop notifications ([see here](https://github.com/nwjs/nw.js/wiki/Notification#toast-notification-requires-node-webkit--v011)). When I implemented this, I already knew that there might be some people who won't like this strict behavior, especially on win7 where these better notificaions are not available. I'm sorry...
So yeah, this definitely needs to be changed and also tied to the desktop notification settings only for users of win(>=8).
If this annoys you so much and you don't want to wait for a new release, you could remove [these lines of code](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.0/src/app/initializers/node-webkit.js#L49-L58) and compile the application for yourself. This is fairly easy, the instructions for this can be found [at the bottom of the readme file](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.0/README.md#build).

**Comment by dojima** [comment]
Ah, I see.  No worries.  As a workaround, I guess I'll just leave the shortcut created by the program and set it to hidden.

Thanks for the quick reply!
