### ISSUE TITLE
Couple quirks to address

### ISSUE THREAD

**Issue by Anonanon** [bastimeyer/livestreamer-twitch-gui#46]
1) Stream quality selection
I watch streams in different quality depending on the streamer or channel. I don't understand why quality selection is hidden and buried requiring 3 additional clicks. It's also not a matter of how many clicks I have to make, but when you pick a quality setting this causes a second instance of MPC to open which causes issues with the first instance.

Solution: when you click on a stream, give us the quality selection immediately.
Bonus: parse/analyze the average bitrate corresponding to the quality, for example:
Source (3000kbps)
High (1580kbps)
Medium (820kbps)
etc.
There's already a Twitch tool out there that informs average bitrate for a quality, so I don't think it's unreasonable to do.

2) Chat popout
The current implementation is a bit jarring to me. Clicking chat popout will just insert itself into the most recent active browser window. So if I'm doing some browsing on my Chrome with 20 tabs opened, chat will insert itself fullscreened into my browser, which will require me to drag it out of Chrome and resize it. It's almost the opposite of convenience.

Solution: make it popout in a small, NEW window exactly like how Twitch behaves. If it isn't broke, don't fix it.

**Comment by bastimeyer** [comment]
> Stream quality selection

This was already requested by #23 a couple of weeks ago and will be resolved by the implementation of the channel pages. You'll then be able to set a default quality for each channel independently and also some other configs like notifications, etc...

> parse/analyze the average bitrate

All stream qualities are encoded with a constant bitrate value by the twitch servers (exclusing the source quality, which is the raw input by the streamer). These bitrates are the same for every stream/channel, so it's up to you to tinker around with your connection to the twitch.tv servers for finding a fitting quality level. Once you've found the right quality for your connection speed, it should be just fine to set it as your default stream quality.
Parsing the stream quality would be the overkill of all overkills for this application. If there's already a tool for that, then please use it instead, that's not what this application was built for.

> Chat popout

I can't do anything about that. There is no way for opening links in a new browser window on nw.js... See [here](https://github.com/nwjs/nw.js/wiki/Shell#openexternaluri).
Using the browser is also just a temporary solution and will hopefully be replaced soon...

**Comment by Anonanon** [comment]
Well at least I'm glad to hear the most important one is getting a solution. Looking forward to that.
