### ISSUE TITLE
Login on two devices

### ISSUE THREAD

**Issue by fortunerayzor** [bastimeyer/livestreamer-twitch-gui#47]
Hey, I'm using your application on two different machines (usually NOT at the same time) and it keeps me logging off the previous device I was using.
Here's the less vague definition:
I log to my account on machine A.
After some time I log to the same account on machine B.
At this point if I start Twitch GUI on machine A, it won't log me in automatically. Machine B will work as expected.

Is this problem related to some twitch limitations?

**Comment by bastimeyer** [comment]
> Is this problem related to some twitch limitations?

Yep, a new login automatically nullifies the old access token on the twitch servers.
See my comment in #36...
