### ISSUE TITLE
Performance/Config Issue

### ISSUE THREAD

**Issue by aventu90** [bastimeyer/livestreamer-twitch-gui#49]
Hi,
I just noticed a big difference in cpu core usage comparing GUI and pure livestreamer, does the GUI ignore my livestreamerrc config? (hls-segment-threads=4) Or is there an other way to add livestreamer parameters?

![withgui](https://cloud.githubusercontent.com/assets/1304763/6287062/8c0ca488-b90e-11e4-8970-79c21a6af99a.PNG)
![withoutgui](https://cloud.githubusercontent.com/assets/1304763/6287067/95504f68-b90e-11e4-9c95-764a75a5966b.PNG)

**Comment by bastimeyer** [comment]
Hi!
There actually shouldn't be any interferences with the default livestreamer config variables when using the GUI. [These](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.1/src/app/controllers/LivestreamerController.js#L68-L78) are the only parameters which are being used when starting the livestreamer process, all other variables defined in your config are not touched/changed.
So are you sure that's really an issue related to the GUI? I mean it doesn't do anything fancy but invoking the livestreamer executable... Your screenshots also don't show which processes are causing the high CPU load and I'd be surprised if it was the GUI.
Could it be the `--player-passthrough` parameter which is responsible for that? Have you tried setting another value?

**Comment by aventu90** [comment]
Shame on me, it was totally my fault. I thought that I was still using --player-passthrough hls with livestreamer, so I chose it for the GUI settings. Turns out that hls (Apples's streaming protocol, should have googled it earlier) has worse performance with my Windows setup.
Everything works fine now, I'm sorry for this hurried ticket. I love your GUI, keep up the great work!

**Comment by bastimeyer** [comment]
Np, thanks :)
