### ISSUE TITLE
Change Twitch OAuth client_id at runtime

### ISSUE THREAD

**Issue by InfernoZeus** [bastimeyer/livestreamer-twitch-gui#53]
This is related to issues #47 and #36.

I haven't looked to closely into this, but would it technically be possible to adjust the `client_id` used? As long as the user registers their own application with the same `redirect_uri`, it should work right?

I realise this would very much be a "power user" feature, but I would personally love to be signed in on more than one machine :smiley:

**Comment by bastimeyer** [comment]
Yes, that would be possible, but I think it's easier to give the user the ability to read/set the access token (of the default client_id) without having to deal with a custom twitch.tv application ID/redirect uri...
There is also always the option to compile the application with a custom client_id for each device, which should be absolutely fine.

> "power user" feature

Maybe I should add a checkbox to the settings for "advanced users". And then adding an input field to the user menu for manipulating the access_token seems to be a good idea. The user can then copy the token to other devices.

**Comment by InfernoZeus** [comment]
Wow, nice job! I'll check it out in a couple of hours. Very grateful for
all the work you put into this :)
