### ISSUE TITLE
Add application to Chocolatey

### ISSUE THREAD

**Issue by scowalt** [bastimeyer/livestreamer-twitch-gui#54]
Hey Sebastian, love the app!

It would be great to add livestreamer-twitch-gui as a [package](https://chocolatey.org/packages) to [Chocolatey](https://chocolatey.org/). Some documentation on how to create a package [here](https://github.com/chocolatey/choco/wiki/CreatePackagesQuickStart). [livestreamer](https://chocolatey.org/packages/livestreamer) is already a Chocolatey package.

I would be happy to setup and maintain this package myself, but it felt appropriate to get in touch with you before doing so.

Thanks!

**Comment by bastimeyer** [comment]
Hi!
Sounds good. You are very welcome to do this. Also thanks for asking :smiley: 
Could you please post the Nuspec and chocolateyInstall.ps1 file contents here first before publishing the package?
Thank you!

**Comment by scowalt** [comment]
Hey Sebastian,

Here's a link to the nuspec, install, and uninstall files. Everything is working on my machine. https://gist.github.com/scowalt/83607606a61387a1662b

The install script simply extracts the zip file into the chocolatey lib directory and adds a shortcut to the desktop. The uninstall script wipes the chocolatey lib directory and removes the shortcut.

Once you approve I'll upload the package to the chocolatey package directory :smile:. Obviously, feel free to make changes as you see fit.

**Comment by bastimeyer** [comment]
Looks all very good. Thank you, Scott...
Can't test it myself since I'm on Linux right now, so I'm just going to trust you here :wink:.

A *quick* question regarding the uninstall script:
Do you think we should also delete the cache and settings folders? I mean, I personally hate it when an uninstaller is leaving stuff behind which is then polluting my system. These are the folders which should be deleted:
```
%LOCALAPPDATA%/livestreamer-twitch-gui
%TEMP%/livestreamer-twitch-gui
```

This is the default `--user-data-dir` of chromium:
http://www.chromium.org/user-experience/user-data-directory
Do you think that this is correct for all windows versions (excluding XP, because who cares anymore)??? `C:\Users\%USERNAME%\AppData\Local` -> `%LOCALAPPDATA%`

This is the definition of `require("os").tmpdir` in node/io.js, which should be fine:
https://github.com/iojs/io.js/blob/v1.5.0/lib/os.js#L25-L36

Thanks again :+1:

**Comment by scowalt** [comment]
Good catch on the cache and settings folders! This was something I hadn't considered.

Removing these folders would not be ideal *if* the uninstall script were to run on package `upgrade`. However, as far as I can tell, only the install script is run on `upgrade`. Therefore, I think removing the cache and settings folders on uninstall is the correct decision.

I'll look into how to compute the proper paths for these folders for all modern versions of windows. However, I suspect using the environment variables you mentioned will work.

I'll comment again on this issue once I've update the package to reflect these changes.

**Comment by scowalt** [comment]
I updated the scripts on the gist I posted before. I'm using the `$env:LOCALAPPDATA` and `$env:TEMP` variables to build the proper paths. I also made all of the removals conditional so the script won't error out if the directories don't exist.

**Comment by bastimeyer** [comment]
Thanks...
In the Arch package thread someone had a good point against deleting the cache and configs when uninstalling the package https://github.com/bastimeyer/livestreamer-twitch-gui/issues/58#issuecomment-77779950. I think removing these folders should either be conditional with a certain command line parameter (such as `--purge` or something like that) or not be done at all.
Besides that, everything looks fine and should be good to go.

Also:
https://github.com/bastimeyer/livestreamer-twitch-gui/issues/58#issuecomment-77747771

**Comment by scowalt** [comment]
Passing a parameter in to clear the cache and settings (and not having it be a default behavior) makes sense. I'll work on that next.

Regarding automation, there are a number of options I could think of:
- Chocolatey has a tool called [AutomaticPackages](https://github.com/chocolatey/choco/wiki/AutomaticPackages) that allows for some level of automation. However, this tool isn't open source, so I might prefer a more DIY solution. 
- We could also use an external tool like [Travis-CI](https://travis-ci.org/) to automatically do this packaging based off of a grunt task. However, this may be overkill considering that this tool isn't currently integrated into the project.
- Creating a grunt task seems like the most reasonable option. I assume that we would distribute the deployment key offline? Or maybe have the task simply create the package, and manually upload it? There is also the issue of including the patch notes for each version. Maybe this grunt task would just crawl the *releases* page to grab the file and the release notes?

Curious to hear how you envision this grunt task working. I'll continue to comment when I have relevant updates.

**Comment by scowalt** [comment]
Updated the Chocolatey package ([gist here](https://gist.github.com/scowalt/83607606a61387a1662b)). Added a `/Purge` uninstall flag that will remove the cache and appdata folders. Also updated the description and release notes in the .nuspec file (these fields support markdown, so I added some basic syntax)

**Comment by bastimeyer** [comment]
> TravisCI

Yes, that would be overkill.. Also, this isn't implemented *yet* for a reason: can't write tests with node/io.js and DOM context and NW.js also can't be run headless... But this story doesn't belong into this thread.

> Grunt task

Just a very simple task that reads from the project.json file, replaces vars in a template and then writes the package metadata file for a manual upload. So nothing dramatically huge here. If there are checksums to be calculated, then those need of course be generated from the uploaded archives.

> Added a /Purge uninstall flag

Cool... If you think that it's ready, then please go for it and publish the package.
Thank you very much!

**Comment by scowalt** [comment]
I've submitted the package, which is [listed here](https://chocolatey.org/packages/livestreamer-twitch-gui/0.7.1). Once it gets through the moderation queue it will publicly available.

I can work on integrating a basic grunt task. Templating the version number based on `package.json` seems simple enough. I still think we would need a web crawler in order to keep the "Release Notes" up-to-date automatically.

I'll make a pull request to this repository once I have significant work done on this grunt task and we can continue our discussion there.

Pleasure to contribute to a project I use every day!

**Comment by bastimeyer** [comment]
> I've submitted the package

Awesome! :+1: 

> I can work on integrating a basic grunt task

You're very welcome to do so, but please follow the structure of custom tasks that is currently used.
The file name of the task should be `build/tasks/custom/package.js` and its configs should go into `build/tasks/configs/package.js`. Also please make it so, that it uses different targets (`grunt package:chocolatey`). The directory for the templates should be `build/resources/package/TARGET/` (TARGET = "chocolatey") and the generated package files should then be saved into `build/package/TARGET/`. If there are any npm dependencies needed, feel free to add and use them. Thanks!

> I still think we would need a web crawler

I'm going to add a `CHANGELOG.md` file for the next release (including all the prev logs). This can be parsed locally then.

**Comment by scowalt** [comment]
Update on this: [the package (version 0.7.1)](https://chocolatey.org/packages/livestreamer-twitch-gui) was approved and is now available in the Chocolatey Gallery.

I have [a branch](https://github.com/scowalt/livestreamer-twitch-gui/tree/chocolatey-package) open to work on automating this packaging process. Hopefully I will be able to make some progress on this soon.

**Comment by scowalt** [comment]
I've made some significant progress on getting `grunt package:chocolatey` up and running. Just one question I have:

While I'm able to load `CHANGELOG.md` into the release notes of the chocolatey package, it seems sub-optimal to load the entire change history into the package. Is there a way to parse the markdown to only include the relevant changes in grunt? If this seems like overkill, I could just exclude the release notes from the chocolatey package altogether.

Once I finish the release notes thing, I should be able to finalize everything and create a pull request.

**Comment by bastimeyer** [comment]
> Is there a way to parse the markdown to only include the relevant changes in grunt?

I think it should be kept as simple as possible. Here's a code snippet that should do the job.

```js
var reSplit  = /\n## /g;
var reFormat = /^\[v?(\d+\.\d+\.\d+(?:-[\S+])?)]\((\S+)\)\s\((\d{4}-\d{2}-\d{2})\)\n\n([\s\S]+)$/;

var list = require( "fs" )
	.readFileSync( "CHANGELOG.md" )
	.toString()
	.split( reSplit )
	.slice( 1 )
	.map(function( release ) {
		return reFormat.exec( release );
	})
	.filter(function( release ) {
		return release !== null;
	});

/*
[
	[ _, version, url, date, notes ],
	...
]
*/
```

Thanks for taking the time and doing this! :+1:
