### ISSUE TITLE
It does not detect livestreamer in mac

### ISSUE THREAD

**Issue by craked5** [bastimeyer/livestreamer-twitch-gui#55]
Hey! First let me say thanks for doing this awesome program!
I installed it on my mac and when i try to watch a stream it tells me that it cannot detect a Livestreamer installation. Livestreamer is certainly installed and on the $path variable also.

Thanks for the help in advance, awesome job!

**Comment by craked5** [comment]
I got it! Thanks anyway mate!

**Comment by bastimeyer** [comment]
Hi, thanks!
Did you set the livestreamer location manually in the settings or how did you solve the issue?
This actually was an old issue which was fixed by #24... On OSX, certain apps don't have access to some env variables (including $PATH). The fix was to set $PATH inside the `Info.plist` file with default paths.
https://github.com/bastimeyer/livestreamer-twitch-gui/blob/cdb856eab4c913238f0a50a793200ecb742cb55f/build/tasks/configs/nodewebkit.js#L11-L13
So I'd like to know if there actually is another issue...

**Comment by craked5** [comment]
Hey! I did set the livestreamer location manually or else it wouldnt find livestreamer!
Thanks!

**Comment by bastimeyer** [comment]
Could you please start the application with the `--remote-debugging-port=8888` parameter and open `http://localhost:8888` in your browser? What I'm looking for is the value of `process.env.PATH` from the dev console.
Also, you're using the latest version, right?

**Comment by craked5** [comment]
Yep, using the latest version!
The process.env.PATH returns this: "/usr/bin:/bin:/usr/sbin:/sbin"

**Comment by bastimeyer** [comment]
Please check if you find the following inside the `livestreamer-twitch-gui.app/Contents/Info.plist` file:
```xml
    <key>LSEnvironment</key>
    <dict>
      <key>PATH</key>
      <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
```

**Comment by craked5** [comment]
Yep its exactly like that! I checked that earlear when i read the issue #24 
Should i do something anywhere else?

**Comment by bastimeyer** [comment]
tbh, I don't know what to do from this point on... I personally don't use OSX, so I have no idea why this is failing. The `Info.plist` file *should* also be fine. Last time I've checked this in my VM, it was all working correctly... Which OSX version are you using? How do you start the application?

**Comment by craked5** [comment]
Well its fine by me mate, i can just do it manually!
I have the latest version, 10.10.2.
I started in the terminal with: open /Applications/Livestreamer\ Twitch\ GUI.app --args --remote-debugging-port=8888
Normally i just click the app.

Thanks for the help dude :)

**Comment by bastimeyer** [comment]
The thing is that I don't know if it's still an issue with the osx builds or if this just happens on your machine. But ok, can't do anything right now... :weary:

**Comment by craked5** [comment]
Ye that sucks, an idea would be to put the manual path as default. I dont know if it would work.

**Comment by Wraul** [comment]
It appears that in OS X 10.10 the PATH environment variable isn't possible to set with LSEnvironment in Info.plist.
Other environment variables works just fine though.

If this is intentional or a bug I don't know.

**Comment by bastimeyer** [comment]
> Ye that sucks, an idea would be to put the manual path as default. I dont know if it would work.

Yep, that's the only solution that I can come up with, too. Although I must say, that I hate it to build in those kind of exceptions into the application code itself.

> It appears that in OS X 10.10 the PATH environment variable isn't possible to set with LSEnvironment in Info.plist.
> Other environment variables works just fine though.
> 
> If this is intentional or a bug I don't know.

Oh apple, you **** :rage:

**Comment by bastimeyer** [comment]
@craked5 
Would you please be so kind and test my fix 1870260? Thanks!!!
```
git clone -b osx-livestreamer-fallback-fix https://github.com/bastimeyer/livestreamer-twitch-gui.git
cd livestreamer-twitch-gui
sudo npm install grunt-cli bower
npm install
grunt release && open build/releases/livestreamer-twitch-gui/osx64/livestreamer-twitch-gui.app
```

**Comment by SkylerLipthay** [comment]
@bastimeyer I'm running on Mac OS X 10.10.2 and I can confirm 1870260bc94f0d8985ff34a478c994e48440a031 fixes this problem!

**Comment by bastimeyer** [comment]
ty, @SkylerLipthay

**Comment by craked5** [comment]
Hey dude sorry for not saying anything soon, but my 2010 mac just died for good i think!
Well i am relieved to see that its fixed! Thanks for the help dude, take care :)

**Comment by bastimeyer** [comment]
np, I'm glad this nasty bug is finally fixed

**Comment by bastimeyer** [comment]
[v0.7.2](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.7.2) released...
