### ISSUE TITLE
Feature Request: Option to list Followed Games

### ISSUE THREAD

**Issue by isamu99** [bastimeyer/livestreamer-twitch-gui#56]
Hello Bastimeyer....fantastic work on the app so far mate! Just wanted to request a feature....in addition to the followed channels list, how about a way to list the games we're following? That would be awesome, since I often have to refer to the Twitch website in order to see which of my followed games are being played. Furthermore, Twitch is now acting up, and not show all my followed games, only ones that have a minimum of around 20 viewers. Not sure why it;s doing this, but its very annoying. If we could have this option built into Livestreamer-GUI that would be wonderful!

Anyway thanks and keep up the good work :)

**Comment by bastimeyer** [comment]
Hi, thanks!
This was already requested in #31... See my answer to this https://github.com/bastimeyer/livestreamer-twitch-gui/issues/31#issuecomment-66801786
I'll have a look into this when I'm done with channel pages, vods and stream/vod download.

**Comment by isamu99** [comment]
Thanks for the reply Sebastian. OK sounds good my friend :)

Just out of curiosity, what are "vods" and "stream/vod download"?

**Comment by bastimeyer** [comment]
>vod 

Video on demand (past broadcasts and highlights of a channel)...

>stream/vod download

Saving streams or VODs to the filesystem instead of passing it to the videoplayer (or do both at the same time).
