### ISSUE TITLE
Arch package

### ISSUE THREAD

**Issue by InfernoZeus** [bastimeyer/livestreamer-twitch-gui#58]
I've finally finished off the Arch package which I started on a couple of months ago, which you can find here: https://aur.archlinux.org/packages/livestreamer-twitch-gui/ Turns out it was much easier than I was making it seem ;)

Should I maintain a git repo for the PKGBUILD/patches/install files, or would you rather just add them to this repo? I don't mind either way.

**Comment by bastimeyer** [comment]
Cool...
How does the packaging system on arch work? Do you need to push the built files yourself or is it possible to link to the files stored on the github servers?

Could you create a github gist with these files for me, so I can see? I also don't have anything against it, if you create your own repo for this, of course...

Thanks

**Comment by InfernoZeus** [comment]
I've added the files to a gist here: https://gist.github.com/InfernoZeus/00e289c4ec6859ddb6a4
There's technically another file but that's just a patch of the pull request I just made.

I should start by saying I'm no Arch expert. There's basically two types of Arch packages:

1) Those that package a specific version of the software, usually pulling a versioned archive (either source or already compiled binary) or a specific tag from git

2) Those that pull the latest version of the code directly from a git repo, and build it as the user installs the package.

At the moment, I've only written the first type, and I think that needs to be manually updated when you bump the version. It should be a very simple change though, just bumping the version string in PKGBUILD, as long as nothing big changes in the application/release structure.

**Comment by bastimeyer** [comment]
Looks good. Thanks!
Do you also think that there should be an uninstall script which removes the settings and cache folders? See my comment here https://github.com/bastimeyer/livestreamer-twitch-gui/issues/54#issuecomment-77727176

I guess the first option you've listed is ok. It's simple and doesn't require all the build dependencies you'd need to install when using the second option...

**Comment by bastimeyer** [comment]
Do you think a grunt task for automating those replacements could be a good idea? Of course you can still maintain the package yourself, but by adding something like this, all the required metadata can be stored at one place for all package managers.

**Comment by InfernoZeus** [comment]
I was wondering if something like that might work. I haven't used Grunt before, so I'll check it out and see what I can do with it.

I believe Arch's pacman handles removing any files added during the install process, but I think we have to handle removing settings/cache folders ourselves. Where does livestreamer-twitch-gui place those?

I intend at some point to create a PKGBUILD for the second type as well, so that I can easily stay in sync with master, but I'm leaving that until I've got this one finished. Then it should be pretty easy to extend it for git.

**Comment by InfernoZeus** [comment]
Just found it in `~/.config/livestreamer-twitch-gui/`. Is that the only place?

**Comment by bastimeyer** [comment]
`/tmp/livestreamer-twitch-gui/`, too...
This is how io.js determines the tmpdir path:
https://github.com/iojs/io.js/blob/v1.5.0/lib/os.js#L31-L34

**Comment by InfernoZeus** [comment]
Do we need to remove stuff from the `tmp` dir? Shouldn't the OS just take care of that (hence the name:wink:)

**Comment by bastimeyer** [comment]
Yeah right, it's optional...

**Comment by InfernoZeus** [comment]
Arch has an option to save user configuration files when removing the package (in case they wish to reinstall in the future). Can you point me to which of the `~/.config/livestreamer-twitch-gui/` files need to be saved in that case?

**Comment by bastimeyer** [comment]
I think `Local Storage/app_livestreamer-twitch-gui_*` should be enough, but I don't know if chromium accepts those single files after a cache wipe.

**Comment by Steef435** [comment]
Sorry for randomly jumping in, I read [the thread on the arch forums](https://bbs.archlinux.org/viewtopic.php?id=194124)

I would advise against removing files not owned by the package, especially when it's about files that belong to users. Not only would it require advanced acrobatics to remove these files for every user, a user shouldn't expect a package to remove files from their home directory. I don't know any package that does this.

Cheers

**Comment by InfernoZeus** [comment]
Thanks for the input, I wasn't sure what the expected behaviour was for
files that aren't technically owned by the package. I'll take a look and
see if I can find some "official" guidelines in it tomorrow.

**Comment by bastimeyer** [comment]
@Steef435 yes, you are right. I also didn't think about a multi-user scenario. So I guess we should just ignore this.

**Comment by bastimeyer** [comment]
This can be closed, I guess...
Also, thanks again for maintaining the package :+1:

**Comment by InfernoZeus** [comment]
Just to add, Arch has switched to using Git for AUR packages. You can find the repo here: https://aur4.archlinux.org/cgit/aur.git/?h=livestreamer-twitch-gui
I'm more than happy to carry on maintaining the package though :smile:

**Comment by bastimeyer** [comment]
Okay, thanks :)

**Comment by bastimeyer** [comment]
@InfernoZeus 
I've just added the `--no-version-check` start parameter. Could you add this to the package please?
I think you need add a replacement for [this line in start.sh](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/66c0321509e6696ad56f44344cf794f29f132577/build/resources/linux/start.sh#L52)...
Thanks!

**Comment by bastimeyer** [comment]
@InfernoZeus 
I made it a bit simpler [by adding a variable to the top of the start script](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/5a5ef56a65af55d9d49e4031ecf9089c868e6e99/build/resources/linux/start.sh#L10).
I'm sorry if I caused any troubles with my decision and my previous post a couple of hours ago :innocent:

**Comment by InfernoZeus** [comment]
No worries, I hadn't started on an update yet. I'll try and get something done tonight.

**Comment by bastimeyer** [comment]
It's ok, you don't need to rush it, it doesn't need to be updated yet. Not until the next release. :grin:

**Comment by InfernoZeus** [comment]
Oh, right! I think it should be a pretty simple sed now that you've added
that variable :)

**Comment by bastimeyer** [comment]
@InfernoZeus 
Hey, I've just seen that the AUR package is still outdated. 3c5accdab7e00ec86aaa7beca4c0ef13d8f21140
Is everything alright? Do you still want to maintain the package?

Could you also please add `xdg-utils` as a dependency? This is required, so the desktop menu entries and icons can be installed.

Thanks!

**Comment by InfernoZeus** [comment]
@bastimeyer Whoops, missed the last update. I'll try and fix that tonight. I'll look at adding `xdg-utils` as well.

**Comment by bastimeyer** [comment]
Hey, I'm intending on adding a `livestreamer-twitch-gui-git` package to the AUR, so people can build it on their own from the master branch. Is it okay, if I'm using some lines from your package, or do you want me to add your name to the header of the PKGBUILD file?

I've also added some missing dependencies that `namcap` was complaining about, added some lines for copying the LICENSE file to the correct location and added the normal package to the conflicts list. You could do this as well for your package.

Before I'm going to publish this, I'd first like to see someone reviewing it, if possible:
https://gist.github.com/bastimeyer/9b733e35ad4baa3b6917f0f423edf467

```bash
git clone https://gist.github.com/9b733e35ad4baa3b6917f0f423edf467.git livestreamer-twitch-gui-git && \
cd ./livestreamer-twitch-gui-git && \
makepkg && \
namcap ./livestreamer-twitch-gui-git-*.pkg.tar && \
sudo pacman -U ./livestreamer-twitch-gui-git-*.pkg.tar
```

Btw, the normal package is outdated and needs to be updated, thanks!

**Comment by InfernoZeus** [comment]
Nice one. I did look at adding a `-git` package a while ago, but had issues with `npm` packages and stuff like that! No problem with you using stuff from my PKGBUILD :)

Can you let me know what `namcap` was complaining about? When I run it on my PKGBUILD, there aren't any issues. (Or were they only with the `-git` package?)

If you don't mind I'll copy the LICENSE file installation from your PKGBUILD.

**Comment by InfernoZeus** [comment]
Just updating the main package now - I've been away from my Arch machine the last couple of days :sunglasses:

**Comment by bastimeyer** [comment]
```bash
$ namcap ./livestreamer-twitch-gui-v0.13.0-1-x86_64.pkg.tar                            2016-07-17 18:25:35
livestreamer-twitch-gui E: Missing custom license directory (usr/share/licenses/livestreamer-twitch-gui)
livestreamer-twitch-gui E: ELF file ('opt/livestreamer-twitch-gui/livestreamer-twitch-gui') outside of a valid path.
livestreamer-twitch-gui E: ELF file ('opt/livestreamer-twitch-gui/libffmpegsumo.so') outside of a valid path.
livestreamer-twitch-gui E: Symlink (opt/livestreamer-twitch-gui/libudev.so.0) points to non-existing /usr/lib/libudev.so
livestreamer-twitch-gui E: Dependency libxtst detected and not included (libraries ['usr/lib/libXtst.so.6'] needed in files ['opt/livestreamer-twitch-gui/livestreamer-twitch-gui'])
livestreamer-twitch-gui E: Dependency nss detected and not included (libraries ['usr/lib/libnss3.so', 'usr/lib/libsmime3.so', 'usr/lib/libnssutil3.so'] needed in files ['opt/livestreamer-twitch-gui/livestreamer-twitch-gui'])
livestreamer-twitch-gui E: Dependency alsa-lib detected and not included (libraries ['usr/lib/libasound.so.2'] needed in files ['opt/livestreamer-twitch-gui/livestreamer-twitch-gui'])
livestreamer-twitch-gui W: Dependency included and not needed ('livestreamer')
livestreamer-twitch-gui W: Dependency included and not needed ('xorg-xwininfo')
livestreamer-twitch-gui W: Dependency included and not needed ('xdg-utils')
```

The "ELF file" and "Symlink" errors can't be fixed (the ELF file ones are caused by using the /opt directory, but they are no real errors and the namcap creator wants to change those to warnings in the future)

```bash
$ namcap ./livestreamer-twitch-gui-git-1171.ebc4688-1-x86_64.pkg.tar                   2016-07-17 18:30:16
livestreamer-twitch-gui-git E: Symlink (opt/livestreamer-twitch-gui/libudev.so.0) points to non-existing /usr/lib/libudev.so
livestreamer-twitch-gui-git E: ELF file ('opt/livestreamer-twitch-gui/livestreamer-twitch-gui') outside of a valid path.
livestreamer-twitch-gui-git E: ELF file ('opt/livestreamer-twitch-gui/libffmpegsumo.so') outside of a valid path.
livestreamer-twitch-gui-git W: Dependency included and not needed ('livestreamer')
livestreamer-twitch-gui-git W: Dependency included and not needed ('xdg-utils')
livestreamer-twitch-gui-git W: Dependency included and not needed ('xorg-xwininfo')
```

**Comment by InfernoZeus** [comment]
Whoops, didn't realise I should run it on the output as well! I'll add those extra libraries as well, thanks!

**Comment by InfernoZeus** [comment]
Just tried out your `-git` package, seems to be working fine. Nice work on the new settings menu, very tidy!
