### ISSUE TITLE
Keyboard shortcuts and right click don't work on Mac.

### ISSUE THREAD

**Issue by fletom** [bastimeyer/livestreamer-twitch-gui#59]
For example, in text fields you can't Cmd-C to copy, Cmd-V to paste, etc. You also can't right click for a context menu and use the copy/paste menu items there. You can't use Cmd-Q to quit the app like every other application.

This applies to all text fields in the app, like search, all settings, and even the username/password fields when authenticating with Twitch.

**Comment by bastimeyer** [comment]
> You also can't right click for a context menu

That's "intended". NW.js comes without context menus, so you need to implement those by yourself and until now I didn't feel the need of doing this.

> you can't Cmd-C to copy, Cmd-V to paste

This used to work in the past... Must have something to do with the latest upgrades to NW.js `v0.12.0`. I'll look into this when I get the time. Thanks for reporting!

**Comment by fletom** [comment]
Great, thanks so much!

Will this be released soon? Does the app automatically update itself or should I keep checking back at the releases page?

**Comment by bastimeyer** [comment]
It'll notify you when there's a new release, but you're always welcome to watch/star the repo. :grin: 
I'm not sure about the release date of the next release though. There is still quite some work to be done... :tired_face:

If you feel that the copy/paste bugs are too annoying, you could try building the application off the master branch. See either [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/c0a6a74983a7829f775c3c92f7e1c8a35ce70bb2/README.md#build) or [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/c0a6a74983a7829f775c3c92f7e1c8a35ce70bb2/CONTRIBUTING.md#developing-and-building).

**Comment by bastimeyer** [comment]
[v0.7.2](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.7.2) released...

**Comment by fletom** [comment]
It works great, thank you so much!
