### ISSUE TITLE
Error: Livestreamer was not found

### ISSUE THREAD

**Issue by suvaacc** [bastimeyer/livestreamer-twitch-gui#61]
I have mac os x 10.10 and i get this error. I have done clean reinstall of livestreamer, but it still doesn't work. When i change the path value of livestreamer myself to point to livestreamer folder i get spawn EACCESS error.

**Comment by bastimeyer** [comment]
Hi,
this was fixed in #55...
A new version will be released this week.

> When i change the path value of livestreamer myself to point to livestreamer folder

You need to set it to the livestreamer executable... Try `/usr/local/bin/livestreamer`

**Comment by bastimeyer** [comment]
[v0.7.2](https://github.com/bastimeyer/livestreamer-twitch-gui/releases/tag/v0.7.2) released...
