### ISSUE TITLE
[OSX] Icon Issue

### ISSUE THREAD

**Issue by soofuzz** [bastimeyer/livestreamer-twitch-gui#64]
Icon too big on task bar with the x64 OS X version. Le minor bug :+1: 
Retina (2880x1800 res) screen macbook pro ›
![screen shot 2015-03-31 at 4 54 33 pm](https://cloud.githubusercontent.com/assets/11738103/6920389/a791f754-d7c6-11e4-930f-1180668020b1.png)

this second isn't so bad thou. its a bit big but meh. task bar on the other hand is too blurry :blush: 
![screen shot 2015-03-31 at 4 54 42 pm](https://cloud.githubusercontent.com/assets/11738103/6920394/aa9eb5a4-d7c6-11e4-8c1f-7f478c5a5146.png)

**Comment by bastimeyer** [comment]
> 2880x1800

Could you please tell me the value of `window.devicePixelRatio`? (paste this into the dev console of NW.js or your browser)
It actually should use a higher icon resolution if your OS is scaling up the UI ([see here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/src/app/nwjs/tray.js#L31-L44)).
The sad thing is, that there's no official guide for creating menubar icons on OSX, so it could be possible that the icons are simply wrong. Back then, when I added the tray icons (colored menubar icons on OSX), a question on stackoverflow.org suggested using 16x16, 32x32 and 48x48 sizes, but I guess this doesn't work well on OSX while using UI scaling (on other platforms it does).

> Icon too big on task bar

I know, the taskbar icon on windows is also a little bit too big, but it's fine for most icon sets on linux. Let me see what I can do.
