### ISSUE TITLE
Show number of online favorites in tray

### ISSUE THREAD

**Issue by zawnk** [bastimeyer/livestreamer-twitch-gui#67]
Hi there,

just found this little neat program and I already really like it! Thanks for it!

A little thing that came to my mind that might be nice to have: Show in the tray icon how many favorite streams are online currently (similar to the unread Skype bubble on the tray icon). 

Thanks again and I hope you consider this feature :)

**Comment by bastimeyer** [comment]
On a tray icon, this wouldn't make much sense. You probably mean a badge label on the task bar (windows) / dock (osx) - something like this (found that image):
![image](https://cloud.githubusercontent.com/assets/467294/6989871/74d29362-da61-11e4-9d29-e3ca24c92930.png)
Yeah, I like that. Will be added, [NW.js supports that](https://github.com/nwjs/nw.js/wiki/Window#setbadgelabellabel).

Thanks for the suggestion!

**Comment by zawnk** [comment]
Hey,

thanks for the quick feedback, glad that it's being implemented! But Skype also has the numbers on the tray icon (and not the Taskbar icon, there it just has numbers, at least for me). 

Taskbar: http://i.imgur.com/PNDpCmi.png
Tray: http://i.imgur.com/432LqxM.png

If it's not a lot of work to implement both, you can give the user the choice, otherwise either is fine, too :)

**Comment by bastimeyer** [comment]
I don't think it's possible to have dynamic tray icons using NW.js... [You're only able to use image files as icons](https://github.com/nwjs/nw.js/wiki/Tray#trayicon) and generating temporary icons which are then being read back in is too much of an overkill for that little feature.
