### ISSUE TITLE
SSL problem with Python <2.7.6

### ISSUE THREAD

**Issue by domagojb** [bastimeyer/livestreamer-twitch-gui#69]
Hey,

Having a python version under 2.7.6 generates an InsecurePlatformWarning. I understand where this problem is coming from, I'd rather like to ask if it is possible to link the program to use another installed version of python on your system instead of the default system one. I do not want to change the system version.

**Comment by bastimeyer** [comment]
Hi!
Which OS (+version) do you use?

> if it is possible to link the program to use another installed version of python on your system

This is a `livestreamer` related problem. This application doesn't have anything to do with the internals of livestreamer or even python.

The `InsecurePlatformWarning` is caused by a python dependency of livestreamer which requires the latest python version. Sadly though, the latest (compiled) version of python is not available on all platforms. You should not manually update python since it could potentially harm your system by breaking current dependencies.

Either wait for an official python upgrade for your system or
**downgrade livestreamer** to `1.12.0` (`sudo pip install livestreamer==1.12.0`).

I could also add a filter that's ignoring this specific error message, but I don't think this is a wise decision.

**Comment by domagojb** [comment]
Hey,

I'm using Elementary Os Luna. The python version in question is 2.7.3.

I will try downgrading livestreamer. If that doesn't work out, I would not mind using a forked version that ignores that error since I would consciously know of it.

**Comment by skulblakka** [comment]
>I would not mind using a forked version that ignores that error since I would consciously know of it.

I think using [this](http://docs.livestreamer.io/cli.html#cmdoption--http-no-ssl-verify) parameter will help

**Comment by bastimeyer** [comment]
> I think using this parameter will help

Using this parameter doesn't work. It will still print out the warning/error message.
Also, disabling certificate verification usually is not a great idea.

Just do what the [link in the error message](https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl) says:
`sudo pip install pyopenssl ndg-httpsclient pyasn1`

**Comment by Kirayao** [comment]
I got the same problem even with livestreamer version 1.12.0.
Also I discovered that this warning could be neglect, whereas in the app it will force the stream to close.
Would you please just neglect the warning? Since that this actually won't affect the stream playing.

**Comment by bastimeyer** [comment]
> I got the same problem even with livestreamer version 1.12.0.

It's your system's python version that causes the error, not livestreamer. Just do what the error message says and install the alternative packages.
I'm not going to suppress any security warnings in the GUI, sorry...

**Comment by Kirayao** [comment]
I tried what the advice told me to do, but the warning remains the same. Also, maybe no need to suppress, but just make it a warning, not a error. Currently it will force close the stream, whereas in the command line this warning won't close the stream.

**Comment by bastimeyer** [comment]
> I tried what the advice told me to do, but the warning remains the same.

Well, if the warning remains the same, then you probably didn't fix the issue.

> Also, maybe no need to suppress, but just make it a warning, not a error. Currently it will force close the stream, whereas in the command line this warning won't close the stream.

The reason why the stream dialog doesn't "succeed" is, that livestreamer is returning this warning on `stdErr` and there's no filter for this specific message. Actually, it's not livestreamer's fault, but one of its dependencies. The stream should also start while using the GUI, but as soon as you close the dialog, it will terminate the livestreamer process.

As I said already before, I don't want to encurage the user to ignore any errors or warnings, so I'm not going to implement filters for all of the errors or warnings that may occur (either from livestreamer or its dependencies).
