### ISSUE TITLE
Appcrash 80000003

### ISSUE THREAD

**Issue by dogbertai** [bastimeyer/livestreamer-twitch-gui#71]
Crash occurs after a while watching streams.

With:
livestreamer-twitch-gui-v0.7.3-win64
livestreamer-v1.12.1-win32.zip

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	livestreamer-twitch-gui.exe
  Application Version:	0.0.0.0
  Application Timestamp:	54f7d3de
  Fault Module Name:	livestreamer-twitch-gui.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	54f7d3de
  Exception Code:	80000003
  Exception Offset:	0000000000046b98
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	90db
  Additional Information 2:	90db9e9aee0da17f32d0e69c1f4ce807
  Additional Information 3:	a176
  Additional Information 4:	a176faba30cf118865f686541b624e3f

**Comment by bastimeyer** [comment]
This is a [NW.js](https://github.com/nwjs/nw.js) related problem, can't do anything about it.
Does this happen on a regular basis? If it does, you should open another thread over there at the [issue tracker](https://github.com/nwjs/nw.js/issues) of their repository.
Thanks!
