### ISSUE TITLE
Font looks blurry

### ISSUE THREAD

**Issue by Riceheadv8** [bastimeyer/livestreamer-twitch-gui#72]
Hi, You changed something from 0.7.1 to 0.7.2 that made the font look out of focus and disgusting. For reference I have a 3k (2880x1620) 15.6in display. Not sure why this has happened looking at your change logs.

![](http://i.gyazo.com/62bc37bd3295f0f82957757acf6b7433.png)

![](http://i.gyazo.com/d98aa625320da1c3b63f7b45512a08b5.png)

**Comment by bastimeyer** [comment]
Hi, thanks for reporting...
It's not only the text that's blurry, but also everything else, too...
This seems to be a NW.js issue. I think it doesn't recognize the HiDPI settings of your display and scales up the whole window content after rendering it on a lower resolution.
[The version of NW.js was upgraded from v0.11.6 to v0.12.0](https://github.com/bastimeyer/livestreamer-twitch-gui/compare/v0.7.1...v0.7.3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L36).

It's already been fixed, [see here](https://github.com/nwjs/nw.js/commit/8e1bade2c5a6eb39952072f4cdea64b411dbbb80). I will upgrade to the new NW.js version as soon as it gets released.

**Comment by soofuzz** [comment]
ahhh yes im running windows 10 technical preview and i got weird blurry all over the app. 
it worked fine on windows 8.1 
btw great app :D forgot to say that last time :)

![livestreamer_twitch_gui_2015-04-11_17-59-36](https://cloud.githubusercontent.com/assets/11738103/7101862/0d912bd6-e075-11e4-8181-1644013a1a3c.png)
![livestreamer_twitch_gui_2015-04-04_20-33-40](https://cloud.githubusercontent.com/assets/11738103/7101863/11669d86-e075-11e4-9f24-955c8f045e26.jpg)

**Comment by bastimeyer** [comment]
Thanks! Give the repo a star if you like it :wink:
As I said, the issue was fixed a couple of days ago, but there is no new NW.js release just yet.
I'm not sure when I'm able to release a new version though, since I'm still working on some stuff which I want to be included in the next release.
