### ISSUE TITLE
Authentication Failed when trying to authorize

### ISSUE THREAD

**Issue by Riceheadv8** [bastimeyer/livestreamer-twitch-gui#73]
Hi, When I try to authorize your app I always get Authentication Failed. I have been able to log in before Twitch forced me to reset. not sure how I get my access token so that I can try that. Some thing interesting to note is that it is registering on my twitch account that I have authorized your app (See below). I even made a new account and I get the same behaviour

![](http://i.gyazo.com/88d108f2eb5865a7332f6d3c7d7e3716.png)

Also when trying to authorize if I disconnect the app from the Twitch Settings-> Connections (Tab) and then log in the first time it will take me to the second screen of the authorize process however every time after that I get the authentication failed message straight after pressing the log in button (See below)

![](http://i.gyazo.com/26efaab27133d20e345c879f2f3c1b98.png)

Not sure if the app keeps logs anywhere I couldn't find them immediately. If you tell me how to find them I will post them.

**Comment by bastimeyer** [comment]
Hi,
I've just debugged it with an old account and it all worked flawlessly. It still returns a valid access token plus scope list and it all validates correctly, so I don't know why this is failing for you.
The only advice I could give you, is deleting your config folder `%LOCALAPPDATA%\livestreamer-twitch-gui`, but I don't know if this helps.

> Not sure if the app keeps logs anywhere I couldn't find them immediately. If you tell me how to find them I will post them.

No, there are no logs, but if you're able to, you could debug the login procedure as well to see where it hangs. [Here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/CONTRIBUTING.md#developing-and-building) you can find the instructions of how to run the application in debug mode. [Set a breakpoint in this line](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/src/app/controllers/UserAuthController.js#L238) and follow the execution (there's a lot being executed asynchronously, so you need to set new breakpoints for those functions).

**Comment by Riceheadv8** [comment]
Deleting the config folder fixed this problem, Thanks !!

**Comment by bastimeyer** [comment]
:+1: np
