### ISSUE TITLE
Window too big and unresizable after rotating screen/using multiple screens

### ISSUE THREAD

**Issue by jeifour** [bastimeyer/livestreamer-twitch-gui#75]
Sometimes I watch twitch while laying in bed so I rotate the screen by 90 degrees or 270 degrees via the display options of OS X so I can watch video without much neck pain. I also sometimes use multiple screens or both features in conjunction. After this I wanted to open the Livestreamer Twitch GUI again in normal screen but it remembered its size and everything from before, so it was so big I couldn't resize it to be actually usable (it also got more and more unresponsive the bigger I managed to drag the window).
![0027-04-18 0 32 57](https://cloud.githubusercontent.com/assets/3247063/7212177/80f5ed6c-e563-11e4-96fa-84e3f7c97c99.png)

I couldn't find any function or key combination built into OS X to resize the window to make it usable again yet (but I'm also not very experienced with it). What worked was deleting every file inside the folder ~/Library/Application Support/livestreamer-twitch-gui/Local Storage/ but maybe this is something you want to look into. (Also I'm just posting this issue if anyone has a similar problem so they can find the solution quickly.)

**Comment by bastimeyer** [comment]
Thanks for reporting the issue.
Seems like the window state persistence needs some more work (missing device orientation events).

> What worked was deleting every file inside the folder

Just launch the application with the `--reset-window` parameter. This will reset the window size and position.

**Comment by jeifour** [comment]
Thanks, I tested the parameter and it works as expected here. If anyone on OS X how to start the .app bundle with a parameter, you can just do this in any folder:
`open -a "Livestreamer Twitch GUI" --args --reset-window`
(provided you didn't change the name of the .app bundle, else you'd have to modify accordingly)

**Comment by bastimeyer** [comment]
Would you please be so kind and test my fixes?
See the [check-screensize](https://github.com/bastimeyer/livestreamer-twitch-gui/tree/check-screensize) branch (c252dd2).

You can find the build instructions [here](https://github.com/bastimeyer/livestreamer-twitch-gui/tree/v0.7.3#build) or [here](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/CONTRIBUTING.md#developing-and-building).

```bash
git clone -b check-screensize https://github.com/bastimeyer/livestreamer-twitch-gui.git
cd livestreamer-twitch-gui
sudo npm install -g grunt-cli bower
npm install
grunt release
```

There's still a bug that needs to be fixed before I can merge this, though. Maximizing the window on OSX still remembers the window size which it shouldn't do.

**Comment by bastimeyer** [comment]
@jeifour Still there? :disappointed:

**Comment by jeifour** [comment]
@bastimeyer Unfortunately I can't test these changes as I don't have access to any OS X machines right now because of a personal issue. I should be able to report back next weekend.

**Comment by bastimeyer** [comment]
Okay, thanks.
All I want to know is if the [displayBoundsChanged](https://github.com/bastimeyer/livestreamer-twitch-gui/commit/c252dd28383e7af0a1e03f3c31c6ffca0fcfa600#diff-db5ca2af19c07ce1f433c63c823928c9R172) event gets triggered when the screen rotates. Can't test this in my VM :grin:
I think I'm going to merge this anyway, since it adds the missing screen size logic of the current version. I also want to release v0.8.0 this week.
