### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by VirtualPorygon** [bastimeyer/livestreamer-twitch-gui#76]
Hi, at first I would like to say that I really love this application it's much more enjoyable to watch stream with your favourite player rather than with the Twitch player. Thanks to the developers!

So I have a little problem when I tried to build the application. I run these commands:

npm install -g grunt-cli bower #No problem, just a warning but I don't have time to see it.
npm install #No problem
grunt release #Error

Here is the message:

>>Running "release" task
Running "jshint:tasks" (jshint) task
>> 23 files lint free.
Running "jshint:app" (jshint) task
>> 147 files lint free.
Running "jshint:test" (jshint) task
>> 4 files lint free.
Running "connect:test" (connect) task
Started connect web server on http://0.0.0.0:8000
Running "qunit:all" (qunit) task
Testing http://localhost:8000/test/tests.html 
>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Use --force to continue.

So I tried to use the force option as suggested and I got another error:

>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Used --force, continuing.
Running "clean:tmp" (clean) task
>> 0 paths cleaned.
Running "copy:build" (copy) task
Created 1 directory, copied 12 files
Running "metadata:all" (metadata) task
Fatal error: fatal: Not a git repository (or any of the parent directories): .git

My OS is Ubuntu 14.10 64bits I have npm and Nodejs installed as well as Livestreamer of course. 

I tried to build the application because I wanted to change the tray icon because on Ubuntu it looks like this:
![img](http://tof.canardpc.com/view/7ac6973d-963c-4bb1-9bc1-74b774f82dba.jpg)
And I don't really like it so I wanted to test some new icons with the same white tone in term of colour. For the moment I deactivated the tray icon.

And I have another question, I would like to know if it is possible to get the title of the stream in term of variable of something like that. For example this channel:

![img2](http://tof.canardpc.com/view/6cd23469-288b-4395-b669-80152283c133.jpg)

I want to get the title in order to change the name of the VLC window with the option. For the moment I use something like that: 

![img3](http://tof.canardpc.com/view/4be92af8-b232-44f3-8022-443df52470bd.jpg)

The --meta-title allows me to change the title of the window, for the moment I use "Twitch". But is it possible to use something like %TitleStreamVariable?

Also I never figured out how to use the player option (especially the syntax) that's why I put all the options in the player path.

Thanks in advance for the help.

**Comment by bastimeyer** [comment]
Hi, thanks!

> So I have a little problem when I tried to build the application.

`PhantomJS timed out, possibly due to a missing QUnit start() call.`

This means that the task for running the tests did not finish (or start at all). As you can see in the logs above, it's starting a local webserver running on port `8000` to do this. Maybe this port is blocked on your machine and causes the task to fail.

> So I tried to use the force option as suggested and I got another error:

`Running "metadata:all" (metadata) task
Fatal error: fatal: Not a git repository (or any of the parent directories): .git`

Did you clone the repository or did you download the source tarball/zip? It's complaining about a missing repository, so make sure that this is intact.

> I wanted to change the tray icon because on Ubuntu it looks like this

That looks indeed a bit out of line. Unity tries to follow the same tray icon styles like OSX does with the monochrome icons, but other DEs don't do this. Can't find official guidelines for this, though. Maybe it's time thinking about adding a switch to settings menu for changing the icon style, but I don't know if Unity requires a different format than the OSX icons.

> I would like to know if it is possible to get the title of the stream in term of variable of something like that.

Yes, of course. I will add this in the next couple of days.

**Comment by VirtualPorygon** [comment]
Thanks for your answer.

For the PhantomJS issue you're probably right I have to check how to open port on Ubuntu, for now I use the force option.

>Did you clone the repository or did you download the source tarball/zip? It's complaining about a missing repository, so make sure that this is intact.

I downloaded the tarball and that's why it didn't work. I cloned the repository and now the metadata error is gone but I have another one instead:

>>Running "less:release" (less) task
>> FileError: '../vendor/bootstrap/dist/css/bootstrap.min.css' wasn't found. Tried - src/vendor/bootstrap/dist/css/bootstrap.min.css,src/vendor/bootstrap/dist/css/bootstrap.min.css,../vendor/bootstrap/dist/css/bootstrap.min.css in src/styles/app.less on line 3, column 1:
>> 2 // Include prebuilt bootstrap (css)
>> 3 @import (inline) "../vendor/bootstrap/dist/css/bootstrap.min.css";
>> 4 // Include Font-Awesome less files
Warning: Error compiling src/styles/app.less Used --force, continuing.

Even with the force option it doesn't work.

**Comment by bastimeyer** [comment]
You are missing some bower dependencies. Did the bower install complete?
`npm install` also [triggers](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.7.3/package.json#L95) a `bower install` call afterwards. Maybe you should run this again.

**Comment by VirtualPorygon** [comment]
Well to be honest I don't really know what I did but now it's working.

At first I ran npm install bower -g and sudo npm install grunt-cli -g, then mount the folder of the application and ran npm install and this time I got something totally different which was the bower install, I saw a lot of lines that I never had before:

>>bower ember#1.11.0          not-cached git://github.com/components/ember.git#1.11.0
bower ember#1.11.0             resolve git://github.com/components/ember.git#1.11.0
bower ember-localstorage-adapter#0.5.2       not-cached git://github.com/rpflorence/ember-localstorage-adapter.git#0.5.2
bower ember-localstorage-adapter#0.5.2          resolve git://github.com/rpflorence/ember-localstorage-adapter.git#0.5.2
etc.

Then I ran the grunt release command and it worked like a charm! No more problem with the port 8000 too (probably because I deactivated the Ubuntu firewall).

So I tried to change the tray icon and it worked, well it's quite ugly but it was just a test:

![img](http://tof.canardpc.com/view/fb5cd377-daa7-4ca3-91d1-0ac84dce85bc.jpg)

I tried the icon for Mac OS X and here is the result:

![img2](http://tof.canardpc.com/view/12a88555-8907-4a48-9675-5b8df2cc325c.jpg)

So I'm going to spend a little bit of time to get something nice but it's not a big deal.

Thank you bastimeyer for your help. You're doing a great job with your application continue like that!

**Comment by VirtualPorygon** [comment]
So it took me some time but after a lot of tests to find the ideal size of the icon I'm pretty much happy with the final result. I made a coloured version too.
![img](http://tof.canardpc.com/view/8ee8c312-7bf9-44b7-8d27-52699da41a34.jpg)

**Comment by bastimeyer** [comment]
You can use [these variables](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/d684418f37f362b0f20b94f92b6e12998ebdfe34/src/app/models/Livestreamer.js#L141-L151) in the player command line and player arguments settings.
**Please make sure that you wrap the vars in quotation marks!** The value of each var will be escaped, so *evil* code can't be executed here.

Example:
`/usr/bin/mpv --title "{name} - {game} - {status}"`

**Comment by VirtualPorygon** [comment]
Alright, I'm probably going to wait until the next release because I have some troubles the build this new version. Maybe because I tried to update livestreamer, I don't know but I still manage to build the old one although. 
I'll see that tomorrow, anyway thanks for the feature!
