### ISSUE TITLE
Unrecognized argument --no-version-check

### ISSUE THREAD

**Issue by Nevon** [bastimeyer/livestreamer-twitch-gui#78]
I'm using the latest release of livestreamer-twitch-gui alongside of livestreamer version 1.11.1. Whenever I try to launch a stream, I get the stream failure popup saying:

```
Error: Couldn't launch the stream
usage: livestreamer [OPTIONS] [URL] [STREAM]
```

I put a breakpoint in where it spawns the livestreamer process, and from what I could see, it's passing the  argument `--no-version-check`, which my version of Livestreamer doesn't seem to support. If I remove that from the array, the stream launches just fine.

**Comment by bastimeyer** [comment]
Does this also happen when you try to start a stream while not using the GUI?
`--no-version-check` was implemented in livestreamer `v1.8.0` ([see here](https://github.com/chrippa/livestreamer/commit/8717efe27e5ebb7ca6d1dc08064c7eeabb6b4453))
Could you please post the whole parameter array?

**Comment by Nevon** [comment]
If I run livestreamer with the same options, then it fails, yes. If I remove the `--no-version-check`, it works.

```javascript
k.join(" ")
"--no-version-check --player /usr/bin/vlc --player-passthrough http --player-continuous-http --twitch-oauth-token MY_TOKEN twitch.tv/cryaotic source,best"
```

```
➜  ~  livestreamer --version
livestreamer 1.11.1
➜  ~  livestreamer --help |grep "no-version-check"  
➜  ~ 
➜  ~  livestreamer --no-version-check --player /usr/bin/vlc --player-passthrough http --player-continuous-http --twitch-oauth-token MY_TOKEN twitch.tv/cryaotic source,best
usage: livestreamer [OPTIONS] [URL] [STREAM]
livestreamer: error: unrecognized arguments: --no-version-check
➜  ~ 
➜  ~  livestreamer --player /usr/bin/vlc --player-passthrough http --player-continuous-http --twitch-oauth-token MY_TOKEN twitch.tv/cryaotic source,best 
[cli][info] Found matching plugin twitch for URL twitch.tv/cryaotic
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as MY_USERNAME
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source (best)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Got HTTP request from VLC/2.2.0 LibVLC/2.2.0
[cli][info] Opening stream: source (hls)
```

**Comment by bastimeyer** [comment]
Well, I don't know how I can help you here. This is clearly an issue of livestreamer itself and maybe you should report this over there, too.
I guess you already tried reinstalling livestreamer, but how did you install it?

**Comment by Nevon** [comment]
Yeah, I guess I will have to file a report there instead. I could also try installing the latest version via `pip`. I was just hoping to avoid that headache. I installed livestreamer directly from the Ubuntu 15.04 repos.

**Comment by Nevon** [comment]
Upgraded to 1.12.1 with pip, and now everything works. Odd, and unfortunate that the version in the latest Ubuntu repos is broken, but at least there's a workaround.

**Comment by bastimeyer** [comment]
Okay, cool... Please don't forget to report the issue over there, too :wink:

**Comment by breunigs** [comment]
The reason Debian's (and thus Ubuntu's) livestreamer doesn't recognize the `--no-version-check` is because I removed it during packaging. Given the OSes keep themselves up to date, it didn't really make sense to keep these options. Starting from 1.12.2, `--version-check` works just as with vanilla livestreamer and `--no-version-check` is just a no-op in Debian-based systems. The new version should be available in Debian in the next few days; no idea when Ubuntu will update.

**Comment by bastimeyer** [comment]
Thanks!
