### ISSUE TITLE
Suggestion for chat client

### ISSUE THREAD

**Issue by Icarus77** [bastimeyer/livestreamer-twitch-gui#79]
I like this GUI, but it's kind of annoying having the client open my browser to have a big chat the size of my browser window.  Is there a way that you could make the chat that is opened appear in a small pop out window, or maybe have the chat open in the GUI itself without relying on the browser?

**Comment by bastimeyer** [comment]
Thanks for the suggestion, but I already pointed it out here https://github.com/bastimeyer/livestreamer-twitch-gui/issues/9#issuecomment-53143747... Opening the chat in the user's default browser is just a compromise.
The long term goal definitely is implementing the chat into the application itself, but this will not be done by embedding the chat from the twitch website. The program would then become a browser within a browser and it's also not possible to use the GUI's OAuth login token in an embedded chat.
What I want to do is implementing a native IRC client (there are several nodejs/io.js IRC modules) for the twitch chat. But as you can already imagine, this will be a lot of work, so I want to finish all the other missing features first.

**Comment by Poorchop** [comment]
Is there going to be an option to disable the IRC portion of the program once you write up the feature? I think a lot of people, myself included, already use standalone IRC clients. I really like the application the way it is now - just a very lightweight Livestreamer frontend for browsing Twitch. I think it is perfect with all of the current features in 0.8.0.

**Comment by bastimeyer** [comment]
@Poorchop Don't worry, it's not going to be bloated and I'm planning to let the user decide on how to open the chat. When I had a look into Chatty a while ago, I ran into some issues, though. I don't know if I will be able to fully support 3rd party programs, but we'll see...
The internal IRC chat is supposed to be working like the original twitch chat, but inside another window, so it can be moved/snapped to the side of the screen next to the video player.
