### ISSUE TITLE
Extreme Lag and Stuttering on Source/High quality

### ISSUE THREAD

**Issue by omperus** [bastimeyer/livestreamer-twitch-gui#82]
About a week ago all streams on source and high quality began to lag and its really unwatchable right now, i have 20/2 internet and never had any problems before so im not sure what is happening.

I downloaded a speed monitor and it shows that it barely gets to 3mbps and then drops to 0 constantly.
Here is my speed test http://www.speedtest.net/result/4334454293.png

After googling around i found a program called "tardsplaya" that it claims to buffer from multiple chunks at the same time, and to my surprise it really fixed the problem.

I now can watch popular streams like lirik at source quality with absolutely no stutter or buffer, my download speed now tops at 10mbps and never goes below 2mbps.

So my question is, can something like this be implemented to livestreamer twitch gui? tardsplaya is a very bare bones program and i really love all the livestreamer twitch gui features and how its constantly updated, thanks for the amazing work and i hope this can be done.

**Comment by bastimeyer** [comment]
Hi...
So you're asking for download parallelization, right? Take a look at the [`hls-live-edge`](http://docs.livestreamer.io/cli.html#cmdoption--hls-live-edge) and [`hls-segment-threads`](http://docs.livestreamer.io/cli.html#cmdoption--hls-segment-threads) livestreamer parameters.
I'll add these parameters to the GUI as soon as I get the time, but for now you have to add them to your [livestreamer config file](http://docs.livestreamer.io/cli.html#configuration-file).

**Comment by omperus** [comment]
I tinkered around with those 2 commands (that weren't present before in the file) and i noticed a difference but didn't eliminate my problem, maybe im doing something wrong with this? im not sure.

It has always been in http mode, by default i think.
After you mentioned that i tried hls and rtmp but there is no difference.

Ive payed attention to the stream launch process and i noticed it says "Opening stream: Source (hls)" http://i.imgur.com/TpGmazI.jpg even tough i have it in http and applied the changes several times just in case.
Maybe there is a problem there? thanks for the response.

**Comment by bastimeyer** [comment]
> I tinkered around with those 2 commands (that weren't present before in the file) and i noticed a difference but didn't eliminate my problem, maybe im doing something wrong with this? im not sure.

If you're having buffering problems, you should increase the values of both parameters a bit.

> Ive payed attention to the stream launch process and i noticed it says "Opening stream: Source (hls)"

Twitch is using [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) for all streams. Livestreamer just reads these HLS playlists and transforms the stream chunks into a http or rtmp stream, so that your video player can play the stream. You can also let livestreamer pass through the HLS playlist to your player if it is capable of playing those stream types by itself, but it also has to do the buffering, etc.
