### ISSUE TITLE
Twitch button in upper right leading to home page

### ISSUE THREAD

**Issue by FISHunderscore** [bastimeyer/livestreamer-twitch-gui#84]
Hello,
I love the GUI, but at first I was confused about what setting the home button did. I eventually found out that it takes you to that page when you launch the program. I think that, if implemented, clicking on the Twitch button in the upper right taking the user to their set home page would be quite handy.

Thanks!

PS: New to GitHub, not sure if I can label this as feature request or if the repository owner has that privilege.

**Comment by bastimeyer** [comment]
Thanks for the suggestion!
This makes sense... Will be added.
