### ISSUE TITLE
Back button shortcut functionality

### ISSUE THREAD

**Issue by FISHunderscore** [bastimeyer/livestreamer-twitch-gui#85]
Hello,
I normally use the forward and back buttons on my mouse to traverse in Chrome and other web browsers. However, I noticed that this does not work in the GUI. I was hoping that you might be able to implement it for a (very slightly) smoother browsing experience.

Thanks!

PS: Hopefully, you understood what I meant by the dedicated forward and back buttons on my mouse. This mouse feature (also sometimes seen on keyboards) is not specific to this specific brand. It is supported by most browsers (it might be something that is a part of Windows?), and even some programs that aren't browsers but it is still useful with.

**Comment by FISHunderscore** [comment]
Also related to making the GUI more web browser-like, a refresh button or the ability to use F5 would be nice if you have had the program running in the background for a while, and want to refresh the streams currently up without having to navigate back to wherever you were at from one of the default pages on the left.

**Comment by bastimeyer** [comment]
Hello...
Forward and backward mouse button event listeners are not supported by Chromium or NW.js, and therefore can't be used. These buttons are also not defined by the DOM3 Events specification, see here: https://w3c.github.io/uievents/#widl-MouseEvent-button

> a refresh button

It's already there at the top bar and it reloads the model of the current route. `F5` or `Ctrl+R` could be added, though...
