### ISSUE TITLE
How can I change to zh-TW language?

### ISSUE THREAD

**Issue by asadman1523** [bastimeyer/livestreamer-twitch-gui#87]
I replace nw.pak to zh-TW.pak but it doesn't work.

I wanna know how I can use another language?

If there isn't zh-TW language file. Maybe I can try to create it.

**Comment by bastimeyer** [comment]
Hello,
I'm sorry, but this application doesn't support multiple languages yet. The files inside the `locales` folder are used by [NW.js](https://github.com/nwjs/nw.js) (dev-tools, etc), but not by the GUI itself.

Right now, I don't want to include multiple languages. I might consider adding language support when all other features are implemented. If I'm at this point, I will be happy to see any good pull requests, thank you.

**Comment by asadman1523** [comment]
OK, I got it~.
