### ISSUE TITLE
How do i pass args to livestreamer?

### ISSUE THREAD

**Issue by Azraelle** [bastimeyer/livestreamer-twitch-gui#88]
With this gui i can't use custom cli parameters, there is only "--player-args" field in the gui.

**Comment by bastimeyer** [comment]
There is no option for setting custom livestreamer parameters (yet).
You have to use the [config file(s)](http://docs.livestreamer.io/cli.html#configuration-file) for all parameters which cannot be set right now.

**Comment by Azraelle** [comment]
Well thats sucks, because i use portable livestreamer and can't even specify non default --config /path/ from the gui.

**Comment by bastimeyer** [comment]
> portable livestreamer

It actually should look up the config files in your home directory, even if you're using a portable installation of livestreamer.

**Comment by Azraelle** [comment]
Thanks, works like a charm.
