### ISSUE TITLE
Problem with the refresh button

### ISSUE THREAD

**Issue by VirtualPorygon** [bastimeyer/livestreamer-twitch-gui#89]
Hi,

I just wanted to say that there is a little problem with the refresh button. If you are on a page of an offline streamer and refresh while the streamer became online it will still tell you that the streamer is offline. However the title is updated, it's not a big deal but I just wanted to warn you about this little issue.

I don't really know the version (at least 0.8) that I am using since I compiled the sources maybe a week ago or more.

**Comment by bastimeyer** [comment]
Hi!
Sounds like a data-binding problem between the channel and channel.index routes. The models themself [should be properly renewed and loaded into the data store](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/21e3bea87655869f57313a05a9fe2894f457b9aa/src/app/routes/ChannelRoute.js#L11) after clicking the reload button. I'll have a look at it tomorrow or so.
Thanks for reporting the issue!

**Comment by VirtualPorygon** [comment]
I had the occasion to test it recently and I confirm the bug is gone.
Thanks for the fix!
