### ISSUE TITLE
Video Player will not start (Usage Error)

### ISSUE THREAD

**Issue by adZiggz** [bastimeyer/livestreamer-twitch-gui#90]
Running on Linux here (Kubuntu 15.04)
Whenever I click to launch a stream I receive the Error: Couldn't launch the stream
usuage: livestreamer [options][url][stream]
![snapshot1](https://cloud.githubusercontent.com/assets/5796109/7736691/a302b9ac-ff13-11e4-8676-e22a76a76e3d.png)

**Comment by bastimeyer** [comment]
Hi...
Which livestreamer version do you use?
`livestreamer --version`
Could this be related to #78?

**Comment by adZiggz** [comment]
Yup, looks like it was the exact same issue
