### ISSUE TITLE
Opening multiple streams

### ISSUE THREAD

**Issue by gizmo1234** [bastimeyer/livestreamer-twitch-gui#92]
Hi I love this program but would love it even more if you could open multiple streams.
At the moment when you try to open another stream, using MPC, it stops the first stream
and tries to run the new stream in the same window. 
Any plans to add this as an option?

**Comment by bastimeyer** [comment]
Hi...
This sounds like a misconfiguration of your MPC. Check for something like `single instance` in the MPC settings and disable it.

**Comment by bastimeyer** [comment]
Added a wiki entry yesterday
https://github.com/bastimeyer/livestreamer-twitch-gui/wiki/Player-configuration#player-configurations
