### ISSUE TITLE
Need to escape curly braces when passing {status}

### ISSUE THREAD

**Issue by Poorchop** [bastimeyer/livestreamer-twitch-gui#94]
If a stream title has curly brackets in it, they need to be escaped at least when passing the title to mpv. I wasn't sure how you would want to handle this - I was thinking of just parsing the title for `{}` and escaping them, but since this might just be a problem with mpv, then it maybe there should first be a check for the default player, which could get more complicated. Or maybe it should just be parsed and escaped as necessary only when `{status}` is passed as a custom player arg.

To escape the curly brackets, just double them. Example: `{random title}` -> `{{random title}}`

**Comment by bastimeyer** [comment]
Why would the curly brackets need to be escaped?
This should actually work fine:
`mpv --title "{foo} {bar}" /path/to/file`

[These](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/25751bc220bddb63eef943a6878981b5fc0c6518/src/app/utils/Substitution.js#L6-L7) are the chars which are being [escaped](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/25751bc220bddb63eef943a6878981b5fc0c6518/src/app/utils/Substitution.js#L44) right now.

**Comment by Poorchop** [comment]
This is actually a livestreamer issue, not an mpv issue. In your livestreamerrc, try `player-args=--title="{Livestreamer}" {filename}` and you will get a KeyError. If you change it to `{{Livestreamer}}` instead, then the stream will launch with the expected title of "{Livestreamer}".

**Comment by bastimeyer** [comment]
Ok, I see, thank you...
