### ISSUE TITLE
Stream is audio-only on linux?

### ISSUE THREAD

**Issue by pipsqueaker** [bastimeyer/livestreamer-twitch-gui#95]
I just downloaded the latest package. However, when I click on a stream, I only get audio. The stream box says that the stream is running, and I can hear the audio, but I have no idea how to access the stream itself. Audio runs, but there's no vlc box that pops up.

Running start.sh from cmd gives the warning

    Syntax error: "(" unexpected (expecting "fi")

and trying to run the executable gives the warning

    [12286:0525/152540:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

In both cases the app seems to work fine, though with the problem I mentioned

**Comment by bastimeyer** [comment]
Hi...
The audio-only issue seems to be related to your video player... Which player do you use? Could you please check if this is happening as well when you try to launch a stream via the shell (using the same player)?
`livestreamer twitch.tv/CHANNEL best -p /path/to/player`

> Syntax error: "(" unexpected (expecting "fi")

[Start.sh](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.9.0/build/resources/linux/start.sh) is actually just a simple bash script which creates a link to a missing library on certain systems. This shouldn't be happening, unless there's something wrong with your bash or system, don't know.

> the executable gives the warning

That's just a generic NW.js warning message and can be ignored. Can't do anything about that...

**Comment by pipsqueaker** [comment]
I did a little bit more digging, and it looks like you were right- my problem is something to do with vlc itself, not livestreamer-twitch-gui. It looks like vlc is failing to create a video output on my computer. I'll fix it and get back to you if interested.

Thanks for maintaining this app! I love its look and I look forward to using it once I get vlc working!
