### ISSUE TITLE
InsecurePlatformWarning: A true SSLContext object is not available

### ISSUE THREAD

**Issue by LaDilettante** [bastimeyer/livestreamer-twitch-gui#96]
I'm using Ubuntu 14.04, Python 2.7.9 :: Anaconda 2.2.0 (64-bit).
I have installed `pip install pyopenssl ndg-httpsclient pyasn1`

However, the warning persists when I tried to open a stream.

**Comment by bastimeyer** [comment]
Well, I don't know how I can help you. It's an issue of a dependency of livestreamer itself, not the GUI.
This issue has already been discussed in #69 

Are those packages installed correctly? What does `pip list` tell you?

**Comment by LaDilettante** [comment]
Right, I realized that it's a `livestreamer` problem, not with your GUI. Those packages are installed correctly, as seen in `pip list`.

```
anh@anh-Latitude-E7240:~$ pip list
...
ndg-httpsclient (0.4.0)
pyasn1 (0.1.7)
pyOpenSSL (0.14)
...
```
I suppose if there's no further insight I'll try to install `livestreamer` with Python 3.x using `virtualenv`.

**Comment by LaDilettante** [comment]
So I installed Python 3 with `virtualenv` and get `livestreamer` to work from the command line. However, `livestreamer-twitch-gui` keeps using the default Python. Is there a way to tell the GUI which Python to use?

**Comment by bastimeyer** [comment]
The GUI is just invoking the livestreamer executable in your $PATH... Either set a custom livestreamer executable location in the GUI settings or change your $PATH.

**Comment by LaDilettante** [comment]
To recap for other googlers:
- Install livestreamer using `virtualenv`. [See livestreamer docs](http://docs.livestreamer.io/install.html#linux-and-bsd-packages)
- Go to `livestreamer-twitch-gui` > `Settings` > `Livestreamer executable path` > Point it towards your livestreamer executable.

Thank you for your help @bastimeyer!
