### ISSUE TITLE
How to set caching in the settings section

### ISSUE THREAD

**Issue by ignarteaga** [bastimeyer/livestreamer-twitch-gui#97]
Hello, today i downloaded the gui and i´m really enjoying it at the moment, but there is one problem im having: when i put the caching options (--file-caching=4000 --network-caching=4000 for example) in the custom parameters section, i cant access any stream and it displays this error

"usage: livestreamer.exe [OPTIONS] [URL] [STREAM]"

is there anything i´m doing wrong or is it just a bug?

**Comment by bastimeyer** [comment]
Hi, thank you!

> --file-caching=4000 --network-caching=4000

I guess, you're trying to set VLC parameters, right? Those are no livestreamer parameters...
You need to set these either in the `--player` or `--player-args` field. Also don't forget to append the required `{filename}` if you're using the player-args field (check the livestreamer docs linked in the GUI).

**Comment by ignarteaga** [comment]
PogChamp IT WORKS PogChamp

Thank you so much :D

**Comment by bastimeyer** [comment]
np, yw :+1:
